/* Generated by tools/genwl.py from abi/wayland/jam-window-memory-v1.xml. Do not edit:
 * change the XML or the generator and run `make wl`.
 *
 * Protocol `jam_window_memory_v1`: per interface its version, opcodes, enums and
 * typed stubs (tools/genwl.py's docstring says what each name is); the
 * tables are in user/lib/jwl_jam_window_memory_v1.c. */
#pragma once

#include <stddef.h>
#include <stdint.h>

#include <jwl.h>
#include <jwl/xdg_shell.h>

extern const struct jwl_interface jwl_jam_window_memory_v1_interface;

/* ---- jam_window_memory_v1, upstream version 1: windows that come back to their places ---- */

#define JWL_JAM_WINDOW_MEMORY_V1_VERSION 1u

/* jam_window_memory_v1 requests: the opcode, and the version each came in. */
#define JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTROY        0u
#define JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTROY_SINCE  1u
#define JWL_JAM_WINDOW_MEMORY_V1_REQ_IDENTIFY       1u
#define JWL_JAM_WINDOW_MEMORY_V1_REQ_IDENTIFY_SINCE 1u
#define JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTRUCTORS    0x00000001u

/* jam_window_memory_v1 events: the opcode, and the version each came in. */
#define JWL_JAM_WINDOW_MEMORY_V1_EV_KEY         0u
#define JWL_JAM_WINDOW_MEMORY_V1_EV_KEY_SINCE   1u
#define JWL_JAM_WINDOW_MEMORY_V1_EV_DESTRUCTORS 0x00000000u

/* What the compositor does with each jam_window_memory_v1 request: one handler per
 * message, or NULL (its dispatcher answers ERR_NOT_SUPPORTED). Each gets
 * the object's data (what libjwl's object map holds for it), its id
 * and the arguments the codec decoded and checked. */
struct jwl_jam_window_memory_v1_requests {
    status_t (*destroy)(void *data, uint32_t self);
    status_t (*identify)(void *data, uint32_t self, uint32_t toplevel, uint32_t key_hi,
                         uint32_t key_lo);
};

/* What a client does with each jam_window_memory_v1 event: one handler per
 * message, or NULL (its dispatcher answers ERR_NOT_SUPPORTED). Each gets
 * the object's data (what libjwl's object map holds for it), its id
 * and the arguments the codec decoded and checked. */
struct jwl_jam_window_memory_v1_events {
    status_t (*key)(void *data, uint32_t self, uint32_t toplevel, uint32_t key_hi, uint32_t key_lo);
};

/* jam_window_memory_v1.destroy, request 0, destroys the object: the object goes */
static inline status_t jwl_jam_window_memory_v1_destroy(struct jwl_conn *c, uint32_t self)
{
    return jwl_send(c, self, JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTROY,
                    &jwl_jam_window_memory_v1_interface.requests[JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTROY],
                    NULL);
}

/* jam_window_memory_v1.identify, request 1: ask a toplevel's key */
static inline status_t jwl_jam_window_memory_v1_identify(struct jwl_conn *c, uint32_t self,
                                                         uint32_t toplevel, uint32_t key_hi,
                                                         uint32_t key_lo)
{
    const union jwl_arg jwl_a[] = {
        { .o = toplevel },
        { .u = key_hi },
        { .u = key_lo },
    };
    return jwl_send(c, self, JWL_JAM_WINDOW_MEMORY_V1_REQ_IDENTIFY,
                    &jwl_jam_window_memory_v1_interface.requests[JWL_JAM_WINDOW_MEMORY_V1_REQ_IDENTIFY],
                    jwl_a);
}

/* jam_window_memory_v1.key, event 0: a toplevel's key */
static inline status_t jwl_jam_window_memory_v1_send_key(struct jwl_conn *c, uint32_t self,
                                                         uint32_t toplevel, uint32_t key_hi,
                                                         uint32_t key_lo)
{
    const union jwl_arg jwl_a[] = {
        { .o = toplevel },
        { .u = key_hi },
        { .u = key_lo },
    };
    return jwl_send(c, self, JWL_JAM_WINDOW_MEMORY_V1_EV_KEY,
                    &jwl_jam_window_memory_v1_interface.events[JWL_JAM_WINDOW_MEMORY_V1_EV_KEY],
                    jwl_a);
}

/* Calls h's handler for jam_window_memory_v1 request `opcode` on object `self`
 * (data: what the object map holds for it) with the arguments a, as
 * the codec decoded them. Returns the handler's status;
 * ERR_NOT_SUPPORTED if h has none for it (handles in a are then
 * still the caller's, to close); ERR_INVALID_ARGS for an opcode jam_window_memory_v1
 * doesn't have. */
static inline status_t jwl_jam_window_memory_v1_dispatch_request(
        const struct jwl_jam_window_memory_v1_requests *h, void *data, uint32_t self,
        uint32_t opcode, const union jwl_arg *a)
{
    switch (opcode) {
    case JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTROY:
        if (!h->destroy)
            return ERR_NOT_SUPPORTED;
        return h->destroy(data, self);
    case JWL_JAM_WINDOW_MEMORY_V1_REQ_IDENTIFY:
        if (!h->identify)
            return ERR_NOT_SUPPORTED;
        return h->identify(data, self, a[0].o, a[1].u, a[2].u);
    }
    return ERR_INVALID_ARGS;
}

/* Calls h's handler for jam_window_memory_v1 event `opcode` on object `self`
 * (data: what the object map holds for it) with the arguments a, as
 * the codec decoded them. Returns the handler's status;
 * ERR_NOT_SUPPORTED if h has none for it (handles in a are then
 * still the caller's, to close); ERR_INVALID_ARGS for an opcode jam_window_memory_v1
 * doesn't have. */
static inline status_t jwl_jam_window_memory_v1_dispatch_event(
        const struct jwl_jam_window_memory_v1_events *h, void *data, uint32_t self, uint32_t opcode,
        const union jwl_arg *a)
{
    switch (opcode) {
    case JWL_JAM_WINDOW_MEMORY_V1_EV_KEY:
        if (!h->key)
            return ERR_NOT_SUPPORTED;
        return h->key(data, self, a[0].o, a[1].u, a[2].u);
    }
    return ERR_INVALID_ARGS;
}
