/* Generated by tools/genidl.py from abi/idl/audioctl.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `audioctl` (id 23). Client: audioctl_<method>(ch, args..., &results...)
 * (and audioctl_<method>_until with a deadline) over drv_channel_call. Server:
 * fill a struct audioctl_ops and run audioctl_serve(ch, &ops, ctx), or
 * audioctl_serve_one / audioctl_dispatch for a loop of your own. */
#pragma once

#include <idl/common.h>

#define AUDIOCTL_PROTOCOL_ID 23u
#define AUDIOCTL_STREAMS          0x00170001u
#define AUDIOCTL_SET_VOLUME       0x00170002u
#define AUDIOCTL_SET_MASTER       0x00170003u
#define AUDIOCTL_DEVICE           0x00170004u

/* Messages (packed: no padding bytes ever cross the channel). */
struct audioctl_streams_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct audioctl_streams_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t count;
    int32_t master;
    uint8_t list[640];
} __attribute__((packed));
struct audioctl_set_volume_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t id;
    int32_t centibels;
} __attribute__((packed));
struct audioctl_set_volume_rep {
    uint32_t txid;
    int32_t  status;
    int32_t centibels;
} __attribute__((packed));
struct audioctl_set_master_req {
    uint32_t txid;
    uint32_t ordinal;
    int32_t centibels;
} __attribute__((packed));
struct audioctl_set_master_rep {
    uint32_t txid;
    int32_t  status;
    int32_t centibels;
} __attribute__((packed));
struct audioctl_device_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t index;
} __attribute__((packed));
struct audioctl_device_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define AUDIOCTL_REQ_MAX 16u   /* bytes: the biggest request */
#define AUDIOCTL_REP_MAX 656u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* Every stream open now, in the order opened: `count` entries of struct
 * mixer_stream_info (<mixer.h>, 40 bytes each) at the start of `list`,
 * the rest zero; `master`, the master volume in centibels. */
static inline status_t audioctl_streams_until(handle_t ch, uint64_t deadline_ns, uint32_t *out_count, int32_t *out_master, uint8_t out_list[640])
{
    struct audioctl_streams_req idl_q;
    struct audioctl_streams_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = AUDIOCTL_STREAMS;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_count)
        *out_count = idl_r.count;
    if (idl_st == OK && out_master)
        *out_master = idl_r.master;
    for (uint32_t idl_i = 0; idl_st == OK && out_list && idl_i < 640; idl_i++)
        out_list[idl_i] = idl_r.list[idl_i];
    return idl_st;
}
static inline status_t audioctl_streams(handle_t ch, uint32_t *out_count, int32_t *out_master, uint8_t out_list[640])
{
    return audioctl_streams_until(ch, DEADLINE_NEVER, out_count, out_master, out_list);
}

/* Stream `id`'s volume in centibels, clamped to [-960, 0] (-960 and below:
 * silence), as audio.set_volume on its own channel. Answers the volume
 * set. ERR_NOT_FOUND: no such stream. */
static inline status_t audioctl_set_volume_until(handle_t ch, uint64_t deadline_ns, uint32_t id, int32_t centibels, int32_t *out_centibels)
{
    struct audioctl_set_volume_req idl_q;
    struct audioctl_set_volume_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = AUDIOCTL_SET_VOLUME;
    idl_q.id = id;
    idl_q.centibels = centibels;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_centibels)
        *out_centibels = idl_r.centibels;
    return idl_st;
}
static inline status_t audioctl_set_volume(handle_t ch, uint32_t id, int32_t centibels, int32_t *out_centibels)
{
    return audioctl_set_volume_until(ch, DEADLINE_NEVER, id, centibels, out_centibels);
}

/* The master volume, applied after the streams are summed, the same way. */
static inline status_t audioctl_set_master_until(handle_t ch, uint64_t deadline_ns, int32_t centibels, int32_t *out_centibels)
{
    struct audioctl_set_master_req idl_q;
    struct audioctl_set_master_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = AUDIOCTL_SET_MASTER;
    idl_q.centibels = centibels;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_centibels)
        *out_centibels = idl_r.centibels;
    return idl_st;
}
static inline status_t audioctl_set_master(handle_t ch, int32_t centibels, int32_t *out_centibels)
{
    return audioctl_set_master_until(ch, DEADLINE_NEVER, centibels, out_centibels);
}

/* The index-th HD Audio driver devmgr runs (from 0, in devmgr's order), as
 * a query channel (hda.idl's `query`): everything the driver answers but
 * open_output, so the shell's `hda` can look and set the gain without
 * taking the output stream the mixer plays through. The caller closes it.
 * ERR_NOT_FOUND: no such driver (index past the last, or no devmgr). */
static inline status_t audioctl_device_until(handle_t ch, uint64_t deadline_ns, uint32_t index, handle_t *out_device)
{
    struct audioctl_device_req idl_q;
    struct audioctl_device_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = AUDIOCTL_DEVICE;
    idl_q.index = index;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                         idl_rh, 1, &idl_rhn, deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_device)
            *out_device = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    return idl_st;
}
static inline status_t audioctl_device(handle_t ch, uint32_t index, handle_t *out_device)
{
    return audioctl_device_until(ch, DEADLINE_NEVER, index, out_device);
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. */
struct audioctl_ops {
    status_t (*streams)(void *ctx, uint32_t *out_count, int32_t *out_master, uint8_t out_list[640]);
    status_t (*set_volume)(void *ctx, uint32_t id, int32_t centibels, int32_t *out_centibels);
    status_t (*set_master)(void *ctx, int32_t centibels, int32_t *out_centibels);
    status_t (*device)(void *ctx, uint32_t index, handle_t *out_device);
};

/* Decode the request of n bytes at req, call its handler, encode the reply
 * into rep (AUDIOCTL_REP_MAX bytes) and the handles it carries into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's length: 0
 * means no reply (the request has no txid). No I/O; the caller sends the
 * reply with the handles, or closes them if it can't. */
static inline uint32_t audioctl_dispatch(const struct audioctl_ops *ops, void *ctx, const void *req, uint32_t n,
                                         void *rep, handle_t *rhs, uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case AUDIOCTL_STREAMS: {
        const struct audioctl_streams_req *idl_q = (const struct audioctl_streams_req *)req;
        struct audioctl_streams_rep *idl_r = (struct audioctl_streams_rep *)rep;
        uint32_t out_count = 0;
        int32_t out_master = 0;
        uint8_t out_list[640];
        for (uint32_t idl_i = 0; idl_i < 640; idl_i++)
            out_list[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->streams) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->streams(ctx, &out_count, &out_master, out_list);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->count = out_count;
        idl_r->master = out_master;
        for (uint32_t idl_i = 0; idl_i < 640; idl_i++)
            idl_r->list[idl_i] = out_list[idl_i];
        return sizeof(*idl_r);
    }
    case AUDIOCTL_SET_VOLUME: {
        const struct audioctl_set_volume_req *idl_q = (const struct audioctl_set_volume_req *)req;
        struct audioctl_set_volume_rep *idl_r = (struct audioctl_set_volume_rep *)rep;
        int32_t out_centibels = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->set_volume) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->set_volume(ctx, idl_q->id, idl_q->centibels, &out_centibels);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->centibels = out_centibels;
        return sizeof(*idl_r);
    }
    case AUDIOCTL_SET_MASTER: {
        const struct audioctl_set_master_req *idl_q = (const struct audioctl_set_master_req *)req;
        struct audioctl_set_master_rep *idl_r = (struct audioctl_set_master_rep *)rep;
        int32_t out_centibels = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->set_master) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->set_master(ctx, idl_q->centibels, &out_centibels);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->centibels = out_centibels;
        return sizeof(*idl_r);
    }
    case AUDIOCTL_DEVICE: {
        const struct audioctl_device_req *idl_q = (const struct audioctl_device_req *)req;
        struct audioctl_device_rep *idl_r = (struct audioctl_device_rep *)rep;
        handle_t out_device = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->device) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->device(ctx, idl_q->index, &out_device);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_device != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_device != HANDLE_INVALID)
                drv_handle_close(out_device);
            return sizeof(*idl_h);
        }
        rhs[0] = out_device;
        *rhn = 1;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t audioctl_serve_one(handle_t ch, const struct audioctl_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[AUDIOCTL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[AUDIOCTL_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = audioctl_dispatch(ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t audioctl_serve(handle_t ch, const struct audioctl_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = audioctl_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
