/* Generated by tools/genidl.py from abi/idl/block.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `block` (id 15). Client: block_<method>(ch, args..., &results...)
 * (and block_<method>_until with a deadline, _within with a timeout), or
 * block_<method>_send and block_<method>_result without waiting. Server:
 * fill a struct block_ops and run block_serve(ch, &ops, ctx), or
 * block_serve_one / block_dispatch_on for a loop of your own;
 * block_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define BLOCK_PROTOCOL_ID 15u
#define BLOCK_INFO             0x000f0001u
#define BLOCK_MAP_BUFFER       0x000f0002u
#define BLOCK_READ             0x000f0003u
#define BLOCK_WRITE            0x000f0004u
#define BLOCK_SYNC             0x000f0005u

/* Messages (packed: no padding bytes ever cross the channel). */
struct block_info_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct block_info_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t block_size;
    uint64_t blocks;
    uint8_t read_only;
} __attribute__((packed));
struct block_map_buffer_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct block_map_buffer_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t size;
} __attribute__((packed));
struct block_read_req {
    uint32_t txid;
    uint32_t ordinal;
    uint64_t lba;
    uint32_t count;
    uint32_t offset;
} __attribute__((packed));
struct block_read_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct block_write_req {
    uint32_t txid;
    uint32_t ordinal;
    uint64_t lba;
    uint32_t count;
    uint32_t offset;
} __attribute__((packed));
struct block_write_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct block_sync_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct block_sync_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define BLOCK_REQ_MAX 24u   /* bytes: the biggest request */
#define BLOCK_REP_MAX 21u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* block_info_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t block_info_call(handle_t ch, bool idl_within, uint64_t idl_t, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only)
{
    struct block_info_req idl_q;
    struct block_info_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = BLOCK_INFO;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_block_size)
        *out_block_size = idl_r.block_size;
    if (idl_st == OK && out_blocks)
        *out_blocks = idl_r.blocks;
    if (idl_st == OK && out_read_only)
        *out_read_only = idl_r.read_only;
    return idl_st;
}
/* Block size in bytes, blocks in the partition, 1 if writes are refused. */
static inline status_t block_info_until(handle_t ch, uint64_t deadline_ns, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only)
{
    return block_info_call(ch, false, deadline_ns, out_block_size, out_blocks, out_read_only);
}
static inline status_t block_info_within(handle_t ch, uint64_t timeout_ns, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only)
{
    return block_info_call(ch, true, timeout_ns, out_block_size, out_blocks, out_read_only);
}
static inline status_t block_info(handle_t ch, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only)
{
    return block_info_call(ch, false, DEADLINE_NEVER, out_block_size, out_blocks, out_read_only);
}

/* block_map_buffer_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t block_map_buffer_call(handle_t ch, bool idl_within, uint64_t idl_t, handle_t *out_buffer, uint32_t *out_size)
{
    struct block_map_buffer_req idl_q;
    struct block_map_buffer_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = BLOCK_MAP_BUFFER;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, idl_rh,
                               1, &idl_rhn, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_buffer)
            *out_buffer = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    return idl_st;
}
/* The buffer transfers use: a VMO of `size` bytes (64 KiB) for the client to
 * map. Once per channel (a second call: ERR_BAD_STATE). */
static inline status_t block_map_buffer_until(handle_t ch, uint64_t deadline_ns, handle_t *out_buffer, uint32_t *out_size)
{
    return block_map_buffer_call(ch, false, deadline_ns, out_buffer, out_size);
}
static inline status_t block_map_buffer_within(handle_t ch, uint64_t timeout_ns, handle_t *out_buffer, uint32_t *out_size)
{
    return block_map_buffer_call(ch, true, timeout_ns, out_buffer, out_size);
}
static inline status_t block_map_buffer(handle_t ch, handle_t *out_buffer, uint32_t *out_size)
{
    return block_map_buffer_call(ch, false, DEADLINE_NEVER, out_buffer, out_size);
}

/* block_read_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t block_read_call(handle_t ch, bool idl_within, uint64_t idl_t, uint64_t lba, uint32_t count, uint32_t offset)
{
    struct block_read_req idl_q;
    struct block_read_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = BLOCK_READ;
    idl_q.lba = lba;
    idl_q.count = count;
    idl_q.offset = offset;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Read `count` blocks from `lba` into the buffer at `offset` (bytes).
 * lba + count past the partition: ERR_OUT_OF_RANGE; a disk error: ERR_IO. */
static inline status_t block_read_until(handle_t ch, uint64_t deadline_ns, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_read_call(ch, false, deadline_ns, lba, count, offset);
}
static inline status_t block_read_within(handle_t ch, uint64_t timeout_ns, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_read_call(ch, true, timeout_ns, lba, count, offset);
}
static inline status_t block_read(handle_t ch, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_read_call(ch, false, DEADLINE_NEVER, lba, count, offset);
}

/* block_write_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t block_write_call(handle_t ch, bool idl_within, uint64_t idl_t, uint64_t lba, uint32_t count, uint32_t offset)
{
    struct block_write_req idl_q;
    struct block_write_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = BLOCK_WRITE;
    idl_q.lba = lba;
    idl_q.count = count;
    idl_q.offset = offset;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Write `count` blocks from the buffer at `offset` to `lba`. Read-only:
 * ERR_ACCESS_DENIED. */
static inline status_t block_write_until(handle_t ch, uint64_t deadline_ns, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_write_call(ch, false, deadline_ns, lba, count, offset);
}
static inline status_t block_write_within(handle_t ch, uint64_t timeout_ns, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_write_call(ch, true, timeout_ns, lba, count, offset);
}
static inline status_t block_write(handle_t ch, uint64_t lba, uint32_t count, uint32_t offset)
{
    return block_write_call(ch, false, DEADLINE_NEVER, lba, count, offset);
}

/* block_sync_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t block_sync_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct block_sync_req idl_q;
    struct block_sync_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = BLOCK_SYNC;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Everything written so far is on the medium (SCSI SYNCHRONIZE CACHE). */
static inline status_t block_sync_until(handle_t ch, uint64_t deadline_ns)
{
    return block_sync_call(ch, false, deadline_ns);
}
static inline status_t block_sync_within(handle_t ch, uint64_t timeout_ns)
{
    return block_sync_call(ch, true, timeout_ns);
}
static inline status_t block_sync(handle_t ch)
{
    return block_sync_call(ch, false, DEADLINE_NEVER);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* block_info without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then block_info_result. */
static inline status_t block_info_send(handle_t ch, uint32_t idl_txid)
{
    struct block_info_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = BLOCK_INFO;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to block_info_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t block_info_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only)
{
    const struct block_info_rep *idl_r = (const struct block_info_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_block_size)
        *out_block_size = idl_r->block_size;
    if (out_blocks)
        *out_blocks = idl_r->blocks;
    if (out_read_only)
        *out_read_only = idl_r->read_only;
    return OK;
}

/* block_map_buffer without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then block_map_buffer_result. */
static inline status_t block_map_buffer_send(handle_t ch, uint32_t idl_txid)
{
    struct block_map_buffer_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = BLOCK_MAP_BUFFER;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to block_map_buffer_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t block_map_buffer_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_buffer, uint32_t *out_size)
{
    const struct block_map_buffer_rep *idl_r = (const struct block_map_buffer_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_buffer)
        *out_buffer = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    if (out_size)
        *out_size = idl_r->size;
    return OK;
}

/* block_read without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then block_read_result. */
static inline status_t block_read_send(handle_t ch, uint32_t idl_txid, uint64_t lba, uint32_t count, uint32_t offset)
{
    struct block_read_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = BLOCK_READ;
    idl_q.lba = lba;
    idl_q.count = count;
    idl_q.offset = offset;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to block_read_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t block_read_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct block_read_rep *idl_r = (const struct block_read_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* block_write without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then block_write_result. */
static inline status_t block_write_send(handle_t ch, uint32_t idl_txid, uint64_t lba, uint32_t count, uint32_t offset)
{
    struct block_write_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = BLOCK_WRITE;
    idl_q.lba = lba;
    idl_q.count = count;
    idl_q.offset = offset;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to block_write_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t block_write_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct block_write_rep *idl_r = (const struct block_write_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* block_sync without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then block_sync_result. */
static inline status_t block_sync_send(handle_t ch, uint32_t idl_txid)
{
    struct block_sync_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = BLOCK_SYNC;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to block_sync_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t block_sync_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct block_sync_rep *idl_r = (const struct block_sync_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with block_reply_<method> (now, or later from anywhere). */
struct block_ops {
    status_t (*info)(void *ctx, uint32_t *out_block_size, uint64_t *out_blocks, uint8_t *out_read_only);
    status_t (*map_buffer)(void *ctx, handle_t *out_buffer, uint32_t *out_size);
    status_t (*read)(void *ctx, uint64_t lba, uint32_t count, uint32_t offset);
    status_t (*write)(void *ctx, uint64_t lba, uint32_t count, uint32_t offset);
    status_t (*sync)(void *ctx);
};

/* Answer the block.info request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t block_reply_info(struct idl_txn idl_txn, status_t idl_st, uint32_t block_size, uint64_t blocks, uint8_t read_only)
{
    struct block_info_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.block_size = block_size;
    idl_r.blocks = blocks;
    idl_r.read_only = read_only;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the block.map_buffer request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t block_reply_map_buffer(struct idl_txn idl_txn, status_t idl_st, handle_t buffer, uint32_t size)
{
    struct block_map_buffer_rep idl_r;
    handle_t idl_hs[1] = { buffer };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(buffer != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    idl_r.size = size;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Answer the block.read request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t block_reply_read(struct idl_txn idl_txn, status_t idl_st)
{
    struct block_read_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the block.write request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t block_reply_write(struct idl_txn idl_txn, status_t idl_st)
{
    struct block_write_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the block.sync request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t block_reply_sync(struct idl_txn idl_txn, status_t idl_st)
{
    struct block_sync_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (BLOCK_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t block_dispatch_on(handle_t ch, const struct block_ops *ops, void *ctx,
                                         const void *req, uint32_t n, void *rep, handle_t *rhs,
                                         uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case BLOCK_INFO: {
        const struct block_info_req *idl_q = (const struct block_info_req *)req;
        struct block_info_rep *idl_r = (struct block_info_rep *)rep;
        uint32_t out_block_size = 0;
        uint64_t out_blocks = 0;
        uint8_t out_read_only = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->info) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->info(ctx, &out_block_size, &out_blocks, &out_read_only);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->block_size = out_block_size;
        idl_r->blocks = out_blocks;
        idl_r->read_only = out_read_only;
        return sizeof(*idl_r);
    }
    case BLOCK_MAP_BUFFER: {
        const struct block_map_buffer_req *idl_q = (const struct block_map_buffer_req *)req;
        struct block_map_buffer_rep *idl_r = (struct block_map_buffer_rep *)rep;
        handle_t out_buffer = HANDLE_INVALID;
        uint32_t out_size = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->map_buffer) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->map_buffer(ctx, &out_buffer, &out_size);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_buffer != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_buffer != HANDLE_INVALID)
                drv_handle_close(out_buffer);
            return sizeof(*idl_h);
        }
        rhs[0] = out_buffer;
        *rhn = 1;
        idl_r->size = out_size;
        return sizeof(*idl_r);
    }
    case BLOCK_READ: {
        const struct block_read_req *idl_q = (const struct block_read_req *)req;
        struct block_read_rep *idl_r = (struct block_read_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->read) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->read(ctx, idl_q->lba, idl_q->count, idl_q->offset);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case BLOCK_WRITE: {
        const struct block_write_req *idl_q = (const struct block_write_req *)req;
        struct block_write_rep *idl_r = (struct block_write_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->write) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->write(ctx, idl_q->lba, idl_q->count, idl_q->offset);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case BLOCK_SYNC: {
        const struct block_sync_req *idl_q = (const struct block_sync_req *)req;
        struct block_sync_rep *idl_r = (struct block_sync_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sync) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sync(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* block_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t block_dispatch(const struct block_ops *ops, void *ctx, const void *req, uint32_t n,
                                      void *rep, handle_t *rhs, uint32_t *rhn)
{
    return block_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t block_serve_one(handle_t ch, const struct block_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[BLOCK_REQ_MAX];
    _Alignas(8) uint8_t idl_r[BLOCK_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = block_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t block_serve(handle_t ch, const struct block_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[BLOCK_REQ_MAX];
    _Alignas(8) uint8_t idl_r[BLOCK_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = block_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
