/* Generated by tools/genidl.py from tools/genidl.py. Do not edit:
 * change the .idl and run `make idl`.
 *
 * What every generated protocol header (<idl/<name>.h>) shares: the
 * message headers and the server's handling of messages no method can
 * take. The format is described at the top of tools/genidl.py. */
#pragma once

#include <jam/driver.h>

/* Every request starts with this, every reply with idl_rep_hdr. */
struct idl_req_hdr {
    uint32_t txid;       /* stamped by channel_call */
    uint32_t ordinal;    /* (protocol id << 16) | method ordinal */
} __attribute__((packed));

struct idl_rep_hdr {
    uint32_t txid;       /* the request's, echoed */
    int32_t  status;     /* OK: the results follow */
} __attribute__((packed));

/* Handles a server reads with a request (all of them are closed: no
 * method takes handle arguments). */
#define IDL_READ_HANDLES 8
/* Handles one reply can carry (methods' handle results). */
#define IDL_REP_HANDLES 8

/* Client: the status of a reply of n bytes to a call that wants `want`
 * bytes back on success. A server that breaks the format (a positive
 * status, a wrong size) is ERR_INTERNAL. */
static inline status_t idl_rep_status(const void *rep, uint32_t n, uint32_t want)
{
    const struct idl_rep_hdr *h = (const struct idl_rep_hdr *)rep;
    if (n < sizeof(*h) || h->status > 0)
        return ERR_INTERNAL;
    if (h->status != OK)
        return n == sizeof(*h) ? h->status : ERR_INTERNAL;
    return n == want ? OK : ERR_INTERNAL;
}

/* Client: one call on ch: the request q (qn bytes) out, the reply into r
 * (rcap bytes, *rn of them) and its handles into rh (rhcap slots, *rhn of
 * them). t is a deadline, or with `within` a timeout from when the call
 * starts, by the kernel's clock (no clock read here). */
static inline status_t idl_call(handle_t ch, void *q, uint32_t qn, void *r, uint32_t rcap,
                                uint32_t *rn, handle_t *rh, uint32_t rhcap, uint32_t *rhn,
                                bool within, uint64_t t)
{
    if (within)
        return drv_channel_call_within(ch, q, qn, r, rcap, rn, rh, rhcap, rhn, t);
    return drv_channel_call_h(ch, q, qn, r, rcap, rn, rh, rhcap, rhn, t);
}

static inline void idl_close_all(const handle_t *hs, uint32_t n)
{
    for (uint32_t idl_i = 0; idl_i < n; idl_i++)
        drv_handle_close(hs[idl_i]);
}

/* Server: answer the request whose first n bytes are at req with a bare
 * status. No txid (n < 4): no reply. A reply that can't be written
 * (the client is gone, or its queue is full) is dropped. */
static inline void idl_reply_status(handle_t ch, const void *req, uint32_t n, status_t st)
{
    if (n < sizeof(uint32_t))
        return;
    struct idl_rep_hdr idl_r;
    idl_r.txid = ((const struct idl_req_hdr *)req)->txid;
    idl_r.status = st;
    drv_channel_write(ch, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Take the next message off ch, which didn't fit the caller's buffers
 * (n bytes, nh handles), and drop it, closing its handles. *txid gets its
 * txid and *got its length (under 4 bytes: no txid, *txid 0). OK, or
 * drv_channel_read's status (ERR_SHOULD_WAIT or ERR_BUFFER_TOO_SMALL:
 * another reader took it meanwhile), or ERR_NO_MEMORY. */
static inline status_t idl_discard(handle_t ch, uint32_t n, uint32_t nh, uint32_t *txid,
                                   uint32_t *got)
{
    uint8_t *idl_b = (uint8_t *)drv_malloc(n ? n : 1);
    handle_t *idl_hs = (handle_t *)drv_malloc(nh ? nh * sizeof(handle_t) : 1);
    status_t idl_st = idl_b && idl_hs ? OK : ERR_NO_MEMORY;
    uint32_t idl_n = 0, idl_nh = 0;
    *txid = 0;
    *got = 0;
    if (idl_st == OK)
        idl_st = drv_channel_read(ch, idl_b, n, &idl_n, idl_hs, nh, &idl_nh);
    if (idl_st == OK) {
        idl_close_all(idl_hs, idl_nh);
        *got = idl_n;
        if (idl_n >= sizeof(uint32_t))
            *txid = ((const struct idl_req_hdr *)idl_b)->txid;
    }
    drv_free(idl_hs);
    drv_free(idl_b);
    return idl_st;
}

/* Server: the next message didn't fit (n bytes, nh handles): bigger than
 * any request of the protocol. Take it off the queue anyway (or it would
 * block every later one), close its handles, answer ERR_INVALID_ARGS. */
static inline status_t idl_drain(handle_t ch, uint32_t n, uint32_t nh)
{
    uint32_t idl_txid = 0, idl_got = 0;
    status_t idl_st = idl_discard(ch, n, nh, &idl_txid, &idl_got);
    if (idl_st == OK && idl_got >= sizeof(uint32_t)) {
        struct idl_rep_hdr idl_r = { idl_txid, ERR_INVALID_ARGS };
        drv_channel_write(ch, &idl_r, sizeof(idl_r), NULL, 0);
    } else if (idl_st == ERR_BUFFER_TOO_SMALL || idl_st == ERR_SHOULD_WAIT) {
        idl_st = OK;   /* another reader took it meanwhile: look again */
    }
    return idl_st;
}

/* ---- serving ----------------------------------------------------------- */

/* A <proto>_serve loop between its system calls: the reply waiting to go
 * out, and the request just taken. */
struct idl_serve {
    handle_t  ch;     /* the channel served (not owned) */
    void     *q;      /* the request buffer: qcap bytes */
    uint32_t  qcap;
    uint32_t  n;      /* the request's bytes, once taken */
    void     *r;      /* the reply: rn bytes, 0 when there is none to send */
    uint32_t  rn;
    handle_t *rhs;    /* the reply's handles: rhn of them, moved once it is sent */
    uint32_t  rhn;
};

/* Server: send the reply waiting in s, if any, and take the next request
 * into s->q, in one system call (drv_channel_reply_wait), waiting for one
 * if none is queued. OK: s->n bytes of a request without handles are in
 * s->q. A request carrying handles, or too big for s->q, is answered
 * ERR_INVALID_ARGS (idl_drain) and the next one taken. A reply that can't
 * go out (the client is gone, or never called) is dropped and its
 * handles closed, as idl_reply_write's. Otherwise the wait's status:
 * ERR_PEER_CLOSED when the client is gone for good and nothing is
 * queued, ERR_CANCELED when the thread is being killed. */
static inline status_t idl_serve_next(struct idl_serve *s)
{
    for (;;) {
        bool idl_reply = s->rn != 0;
        /* The reply's status (1: never a status, the reply wasn't tried)
         * and the request's sizes, in a row: the kernel writes them in one
         * copy. */
        struct { status_t rs; uint32_t n, nh; } idl_o = { 1, 0, 0 };
        /* No room for handles: a request that carries any stays queued
         * (ERR_BUFFER_TOO_SMALL) for idl_drain. */
        struct channel_reply_wait_args idl_a = {
            .h = idl_reply ? s->ch : HANDLE_INVALID,
            .wait = s->ch,
            .bytes = (uint64_t)(uintptr_t)s->q,
            .bytes_cap = s->qcap,
            .actual_bytes = (uint64_t)(uintptr_t)&idl_o.n,
            .actual_handles = (uint64_t)(uintptr_t)&idl_o.nh,
            .deadline_ns = DEADLINE_NEVER,
        };
        if (idl_reply) {
            idl_a.rbytes = (uint64_t)(uintptr_t)s->r;
            idl_a.rn = s->rn;
            idl_a.rh = (uint64_t)(uintptr_t)s->rhs;
            idl_a.rhn = s->rhn;
            idl_a.reply_status = (uint64_t)(uintptr_t)&idl_o.rs;
        }
        status_t idl_st = drv_channel_reply_wait(&idl_a);
        if (idl_o.rs != OK)
            idl_close_all(s->rhs, s->rhn);   /* not sent: they're still ours */
        s->rn = s->rhn = 0;
        if (idl_reply && idl_o.rs != 1 && idl_o.rs != OK && idl_o.rs != ERR_PEER_CLOSED)
            continue;   /* the reply failed and nothing was read: wait again */
        if (idl_st == ERR_BUFFER_TOO_SMALL) {
            idl_st = idl_drain(s->ch, idl_o.n, idl_o.nh);
            if (idl_st == OK)
                continue;
        }
        if (idl_st != OK)
            return idl_st;
        s->n = idl_o.n;
        return OK;
    }
}

/* ---- requests in slots (a server whose requests outlive it) ------------ */

/* A request slot: memory the server chooses (a service's state VMO,
 * <svcstate.h>), which one request is read into and its reply built in,
 * so that the request in progress outlives the process: a successor finds
 * it there and runs it again with the same code (<proto>_run_slot). */
struct idl_slot {
    void     *q;      /* the request: qcap bytes of room, the protocol's REQ_MAX or more */
    uint32_t  qcap;
    uint32_t *n;      /* its length: written by the kernel after its bytes, 0 before */
    uint32_t *nh;     /* how many handles it carried ... */
    handle_t *hs;     /* ... into room for hcap of them (no method takes any) */
    uint32_t  hcap;
    void     *r;      /* its reply: the protocol's REP_MAX bytes of room */
};

/* idl_take's end: what a read into slot that returned st leaves there. */
static inline status_t idl_taken(handle_t ch, const struct idl_slot *slot, status_t st)
{
    if (st == ERR_BUFFER_TOO_SMALL) {
        /* The kernel wrote the size of what stays queued: no request here. */
        uint32_t idl_n = *slot->n, idl_nh = *slot->nh;
        __atomic_store_n(slot->n, 0, __ATOMIC_RELEASE);
        *slot->nh = 0;
        return idl_drain(ch, idl_n, idl_nh);
    }
    if (st == OK && *slot->n < sizeof(uint32_t)) {
        idl_close_all(slot->hs, *slot->nh);
        __atomic_store_n(slot->n, 0, __ATOMIC_RELEASE);
        *slot->nh = 0;
    }
    return st;
}

/* Server: read the next message on ch into slot. Its length (*slot->n) is
 * zeroed first and written by the kernel after the bytes, in the one
 * system call that takes the message off the queue, and a thread finishes
 * the system call it is in before it dies: so a process killed at any
 * point leaves the message either still queued or wholly in the slot.
 * OK: a message was taken. *slot->n 4 or more: a request to run
 * (<proto>_run_slot), with *slot->nh handles in slot->hs, the caller's to
 * close (no method takes any: <proto>_run_slot refuses it). *slot->n 0:
 * nothing to run, the message dealt with as <proto>_serve_one deals with
 * it: one too big for the slot or with more than hcap handles answered
 * ERR_INVALID_ARGS (idl_drain), one under 4 bytes (no txid) dropped, its
 * handles closed. Otherwise channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t idl_take(handle_t ch, const struct idl_slot *slot)
{
    __atomic_store_n(slot->n, 0, __ATOMIC_RELEASE);
    *slot->nh = 0;
    status_t idl_st = drv_channel_read(ch, slot->q, slot->qcap, slot->n, slot->hs,
                                       slot->hcap, slot->nh);
    return idl_taken(ch, slot, idl_st);
}

/* A reply that waits to go out with the server's next system call (a
 * take, idl_take_after; a wait on its port, idl_wait_after; or
 * idl_reply_flush), so that answering costs no system call of its own.
 * The kernel sets *mark (a slot's, <svcstate.h>) once the reply went
 * out, in that same call: a successor knows exactly whether it did. */
struct idl_reply {
    handle_t    ch;      /* the request's channel; HANDLE_INVALID: nothing waits */
    const void *r;       /* the reply (a slot's reply area): rn bytes */
    uint32_t    rn;
    uint32_t    nh;      /* handles in hs: moved once the reply is tried */
    handle_t    hs[IDL_REP_HANDLES];
    uint64_t   *mark;    /* set to 1 by the kernel once it went out; NULL: none */
};

/* The reply half of a channel_reply_wait for the reply waiting in rep (its
 * status into *rs). false: nothing waits (a->h HANDLE_INVALID). */
static inline bool idl_reply_args(const struct idl_reply *rep, struct channel_reply_wait_args *a,
                                  status_t *rs)
{
    a->h = HANDLE_INVALID;
    if (!rep || rep->ch == HANDLE_INVALID)
        return false;
    a->h = rep->ch;
    a->rbytes = (uint64_t)(uintptr_t)rep->r;
    a->rn = rep->rn;
    a->rh = (uint64_t)(uintptr_t)rep->hs;
    a->rhn = rep->nh;
    a->reply_status = (uint64_t)(uintptr_t)rs;
    a->mark = (uint64_t)(uintptr_t)rep->mark;
    return true;
}

/* After a channel_reply_wait that tried rep's reply (its status rs: 1 if
 * the kernel never got to it): nothing waits any more, and handles that
 * didn't go are closed (as idl_reply_write's: a client that is gone, or
 * whose queue is full, loses its reply). true: the reply failed and the
 * call ended there, nothing taken: make it again without the reply. */
static inline bool idl_reply_tried(struct idl_reply *rep, status_t rs)
{
    if (rs != OK)
        idl_close_all(rep->hs, rep->nh);
    rep->ch = HANDLE_INVALID;
    rep->nh = 0;
    return rs != 1 && rs != OK && rs != ERR_PEER_CLOSED;
}

/* Server: idl_take, sending the reply waiting in *rep first in the same
 * system call (channel_reply_wait, its wait 0: it never waits), whatever
 * channel that reply is for. The reply's mark is set once it went out,
 * before the read. Results as idl_take's (ERR_SHOULD_WAIT: nothing is
 * queued, and the reply went out); *rep is empty after. */
static inline status_t idl_take_after(handle_t ch, const struct idl_slot *slot,
                                      struct idl_reply *rep)
{
    for (;;) {
        status_t idl_rs = 1;   /* never a status: the reply wasn't tried */
        __atomic_store_n(slot->n, 0, __ATOMIC_RELEASE);
        *slot->nh = 0;
        struct channel_reply_wait_args idl_a = {
            .wait = ch,
            .bytes = (uint64_t)(uintptr_t)slot->q,
            .bytes_cap = slot->qcap,
            .handles = (uint64_t)(uintptr_t)slot->hs,
            .handles_cap = slot->hcap,
            .actual_bytes = (uint64_t)(uintptr_t)slot->n,
            .actual_handles = (uint64_t)(uintptr_t)slot->nh,
            .flags = CHANNEL_REPLY_WAIT_TIMEOUT,
            .deadline_ns = 0,
        };
        bool idl_reply = idl_reply_args(rep, &idl_a, &idl_rs);
        status_t idl_st = drv_channel_reply_wait(&idl_a);
        if (idl_reply && idl_reply_tried(rep, idl_rs))
            continue;
        if (idl_st == ERR_TIMED_OUT)
            idl_st = ERR_SHOULD_WAIT;   /* a wait of 0: nothing was queued */
        return idl_taken(ch, slot, idl_st);
    }
}

/* Server: drv_port_wait, sending the reply waiting in *rep first in the
 * same system call (channel_reply_wait on the port). Results as
 * port_wait's; *rep is empty after. */
static inline status_t idl_wait_after(handle_t port, uint64_t deadline_ns,
                                      struct port_packet *pkt, struct idl_reply *rep)
{
    for (;;) {
        status_t idl_rs = 1;
        struct channel_reply_wait_args idl_a = {
            .wait = port, .packet = (uint64_t)(uintptr_t)pkt, .deadline_ns = deadline_ns,
        };
        if (!idl_reply_args(rep, &idl_a, &idl_rs))
            return drv_port_wait(port, deadline_ns, pkt);
        status_t idl_st = drv_channel_reply_wait(&idl_a);
        if (!idl_reply_tried(rep, idl_rs))
            return idl_st;
    }
}

/* Server: the reply waiting in *rep (if any) out now, in a system call of
 * its own: a channel_reply_wait on the reply's own channel with no room
 * for a message and a wait of 0, so a request queued there stays queued
 * (but one of 0 bytes and no handles, which no protocol answers, is taken
 * and so dropped). The reply's mark is set once it went out. true: a
 * message may be queued on that channel (or it can't be told: the reply
 * failed); false: nothing is, or nothing waited. */
static inline bool idl_reply_flush(struct idl_reply *rep)
{
    status_t idl_rs = 1;
    struct channel_reply_wait_args idl_a = {
        .flags = CHANNEL_REPLY_WAIT_TIMEOUT, .deadline_ns = 0,
    };
    if (!idl_reply_args(rep, &idl_a, &idl_rs))
        return false;
    idl_a.wait = rep->ch;
    status_t idl_st = drv_channel_reply_wait(&idl_a);
    if (idl_reply_tried(rep, idl_rs))
        return true;
    return idl_st == OK || idl_st == ERR_BUFFER_TOO_SMALL;
}

/* Server: the request in slot carried handles: answered ERR_INVALID_ARGS
 * into slot->r without its handler seeing it. The reply's length. */
static inline uint32_t idl_refuse(const struct idl_slot *slot)
{
    struct idl_rep_hdr *idl_r = (struct idl_rep_hdr *)slot->r;
    idl_r->txid = ((const struct idl_req_hdr *)slot->q)->txid;
    idl_r->status = ERR_INVALID_ARGS;
    return sizeof(*idl_r);
}

/* ---- answering later (a `later` method, or a loop of your own) ------- */

/* A request to be answered later: the channel it came on (not owned:
 * keep it open until the reply is written) and its txid. A `later`
 * method's handler gets it; <proto>_reply_<method> answers it. */
struct idl_txn {
    handle_t ch;
    uint32_t txid;
};

/* What a `later` method's handler returns when it answers with
 * <proto>_reply_<method> (now or later) instead of through its results.
 * Never a status on the wire. */
#define IDL_LATER 1

/* Server: write the reply rep (n bytes; its txid is set here) with nh
 * handles to txn. The handles are moved in every case: sent, or closed
 * when the write fails (ERR_PEER_CLOSED: the client is gone; a client
 * that gave up waiting still gets the reply, as a message of its own). */
static inline status_t idl_reply_write(struct idl_txn txn, void *rep, uint32_t n,
                                       handle_t *hs, uint32_t nh)
{
    ((struct idl_rep_hdr *)rep)->txid = txn.txid;
    status_t idl_st = drv_channel_write(txn.ch, rep, n, hs, nh);
    if (idl_st != OK)
        idl_close_all(hs, nh);
    return idl_st;
}

/* ---- asynchronous calls ------------------------------------------------ */

/* Client: the next txid from the counter *last, never 0. Use one counter
 * per channel end, and only asynchronous calls on that end (a blocking
 * call's txid comes from the kernel and could match one of these). */
static inline uint32_t idl_txid_next(uint32_t *last)
{
    if (++*last == 0)
        ++*last;
    return *last;
}

/* A reply read off a channel, for <proto>_<method>_result. */
struct idl_msg {
    uint32_t txid;                    /* its txid: which call it answers */
    uint32_t n;                       /* its bytes */
    uint32_t nh;                      /* handles in hs, still to be taken */
    handle_t hs[IDL_REP_HANDLES];
};

/* Client: close the handles of a reply nobody takes (its txid matches no
 * call: a reply to a call that gave up). */
static inline void idl_msg_drop(struct idl_msg *m)
{
    idl_close_all(m->hs, m->nh);
    m->nh = 0;
}

/* Client: read the next reply off ch into rep (cap bytes: the protocol's
 * <PROTO>_REP_MAX) and *m, then find its call by m->txid and decode it
 * with that method's <proto>_<method>_result (or idl_msg_drop it).
 * ERR_SHOULD_WAIT: nothing queued; ERR_PEER_CLOSED: the server is gone
 * (every call still waiting fails). A message too big for rep or with
 * more than IDL_REP_HANDLES handles, or without a txid, is no reply of
 * the protocol: dropped, its handles closed, ERR_INTERNAL with m->txid
 * set (0 if it had none) so its call can fail. */
static inline status_t idl_reply_read(handle_t ch, void *rep, uint32_t cap, struct idl_msg *m)
{
    m->txid = m->n = m->nh = 0;
    status_t idl_st = drv_channel_read(ch, rep, cap, &m->n, m->hs, IDL_REP_HANDLES, &m->nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL) {
        uint32_t idl_got = 0;
        idl_st = idl_discard(ch, m->n, m->nh, &m->txid, &idl_got);
        m->n = m->nh = 0;
        return idl_st == ERR_NO_MEMORY ? idl_st : ERR_INTERNAL;
    }
    if (idl_st != OK)
        return idl_st;
    if (m->n < sizeof(uint32_t)) {
        idl_msg_drop(m);
        return ERR_INTERNAL;
    }
    m->txid = ((const struct idl_rep_hdr *)rep)->txid;
    return OK;
}
