/* Generated by tools/genidl.py from abi/idl/dns.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `dns` (id 30). Client: dns_<method>(ch, args..., &results...)
 * (and dns_<method>_until with a deadline, _within with a timeout), or
 * dns_<method>_send and dns_<method>_result without waiting. Server:
 * fill a struct dns_ops and run dns_serve(ch, &ops, ctx), or
 * dns_serve_one / dns_dispatch_on for a loop of your own, or
 * dns_take_slot / dns_run_slot for requests read into slots that outlive
 * the server; dns_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define DNS_PROTOCOL_ID 30u
#define DNS_RESOLVE          0x001e0001u

/* Messages (packed: no padding bytes ever cross the channel). */
struct dns_resolve_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t name[256];
    uint32_t timeout_ms;
} __attribute__((packed));
struct dns_resolve_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t count;
    uint32_t addr0;
    uint32_t addr1;
    uint32_t addr2;
    uint32_t addr3;
    uint32_t ttl;
} __attribute__((packed));

#define DNS_REQ_MAX 268u   /* bytes: the biggest request */
#define DNS_REP_MAX 29u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* dns_resolve_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t dns_resolve_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t name[256], uint32_t timeout_ms, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl)
{
    struct dns_resolve_req idl_q;
    struct dns_resolve_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = DNS_RESOLVE;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    idl_q.timeout_ms = timeout_ms;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_count)
        *out_count = idl_r.count;
    if (idl_st == OK && out_addr0)
        *out_addr0 = idl_r.addr0;
    if (idl_st == OK && out_addr1)
        *out_addr1 = idl_r.addr1;
    if (idl_st == OK && out_addr2)
        *out_addr2 = idl_r.addr2;
    if (idl_st == OK && out_addr3)
        *out_addr3 = idl_r.addr3;
    if (idl_st == OK && out_ttl)
        *out_ttl = idl_r.ttl;
    return idl_st;
}
/* On an opener's channel: the IPv4 addresses of `name` (NUL-terminated in
 * its 256 bytes; a host name, or a dotted IPv4 address, answered as it
 * is), at most four, and how many seconds the answer may be kept (`ttl`).
 * Answered when the answer comes, from the cache at once. Errors:
 * ERR_NOT_FOUND (no such name, or it has no IPv4 address), ERR_TIMED_OUT
 * (no server answered within the resolver's 10 s, or timeout_ms passed:
 * 1..60000), ERR_IO (the servers failed), ERR_NOT_SUPPORTED (the answer
 * needs TCP), ERR_OUT_OF_RANGE (more than 8 CNAMEs); at once:
 * ERR_INVALID_ARGS (not a name, or no NUL; timeout_ms out of range),
 * ERR_BAD_STATE (no DNS servers yet: see `net`), ERR_NO_RESOURCES (too
 * many in flight). */
static inline status_t dns_resolve_until(handle_t ch, uint64_t deadline_ns, const uint8_t name[256], uint32_t timeout_ms, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl)
{
    return dns_resolve_call(ch, false, deadline_ns, name, timeout_ms, out_count, out_addr0, out_addr1, out_addr2, out_addr3, out_ttl);
}
static inline status_t dns_resolve_within(handle_t ch, uint64_t timeout_ns, const uint8_t name[256], uint32_t timeout_ms, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl)
{
    return dns_resolve_call(ch, true, timeout_ns, name, timeout_ms, out_count, out_addr0, out_addr1, out_addr2, out_addr3, out_ttl);
}
static inline status_t dns_resolve(handle_t ch, const uint8_t name[256], uint32_t timeout_ms, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl)
{
    return dns_resolve_call(ch, false, DEADLINE_NEVER, name, timeout_ms, out_count, out_addr0, out_addr1, out_addr2, out_addr3, out_ttl);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* dns_resolve without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then dns_resolve_result. */
static inline status_t dns_resolve_send(handle_t ch, uint32_t idl_txid, const uint8_t name[256], uint32_t timeout_ms)
{
    struct dns_resolve_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = DNS_RESOLVE;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    idl_q.timeout_ms = timeout_ms;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to dns_resolve_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t dns_resolve_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl)
{
    const struct dns_resolve_rep *idl_r = (const struct dns_resolve_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_count)
        *out_count = idl_r->count;
    if (out_addr0)
        *out_addr0 = idl_r->addr0;
    if (out_addr1)
        *out_addr1 = idl_r->addr1;
    if (out_addr2)
        *out_addr2 = idl_r->addr2;
    if (out_addr3)
        *out_addr3 = idl_r->addr3;
    if (out_ttl)
        *out_ttl = idl_r->ttl;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with dns_reply_<method> (now, or later from anywhere). */
struct dns_ops {
    status_t (*resolve)(void *ctx, struct idl_txn idl_txn, const uint8_t name[256], uint32_t timeout_ms, uint8_t *out_count, uint32_t *out_addr0, uint32_t *out_addr1, uint32_t *out_addr2, uint32_t *out_addr3, uint32_t *out_ttl);
};

/* Answer the dns.resolve request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t dns_reply_resolve(struct idl_txn idl_txn, status_t idl_st, uint8_t count, uint32_t addr0, uint32_t addr1, uint32_t addr2, uint32_t addr3, uint32_t ttl)
{
    struct dns_resolve_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.count = count;
    idl_r.addr0 = addr0;
    idl_r.addr1 = addr1;
    idl_r.addr2 = addr2;
    idl_r.addr3 = addr3;
    idl_r.ttl = ttl;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (DNS_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t dns_dispatch_on(handle_t ch, const struct dns_ops *ops, void *ctx,
                                       const void *req, uint32_t n, void *rep, handle_t *rhs,
                                       uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case DNS_RESOLVE: {
        const struct dns_resolve_req *idl_q = (const struct dns_resolve_req *)req;
        struct dns_resolve_rep *idl_r = (struct dns_resolve_rep *)rep;
        uint8_t out_count = 0;
        uint32_t out_addr0 = 0;
        uint32_t out_addr1 = 0;
        uint32_t out_addr2 = 0;
        uint32_t out_addr3 = 0;
        uint32_t out_ttl = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->resolve) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        struct idl_txn idl_txn = { ch, idl_h->txid };
        status_t idl_st = ops->resolve(ctx, idl_txn, idl_q->name, idl_q->timeout_ms, &out_count, &out_addr0, &out_addr1, &out_addr2, &out_addr3, &out_ttl);
        /* IDL_LATER: the handler answers with dns_reply_resolve. */
        if (idl_st == IDL_LATER)
            return 0;
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->count = out_count;
        idl_r->addr0 = out_addr0;
        idl_r->addr1 = out_addr1;
        idl_r->addr2 = out_addr2;
        idl_r->addr3 = out_addr3;
        idl_r->ttl = out_ttl;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* dns_dispatch_on without the channel (a `later` handler's txn then has none: use dns_dispatch_on). */
static inline uint32_t dns_dispatch(const struct dns_ops *ops, void *ctx, const void *req, uint32_t n,
                                    void *rep, handle_t *rhs, uint32_t *rhn)
{
    return dns_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take the next message on ch into slot (idl_take), a slot with room for
 * the protocol's biggest request: ERR_INVALID_ARGS if it has less. */
static inline status_t dns_take_slot(handle_t ch, const struct idl_slot *slot)
{
    if (slot->qcap < DNS_REQ_MAX)
        return ERR_INVALID_ARGS;
    return idl_take(ch, slot);
}

/* Run the request in slot (taken by dns_take_slot, or found there by a
 * successor), which came on ch: as dns_dispatch_on, its reply built
 * in slot->r and the handles that reply carries put into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). A request that carried handles is
 * answered ERR_INVALID_ARGS without its handler seeing it. Returns the
 * reply's length: 0 means no reply (no txid, or a `later` handler
 * answers it itself). No I/O; the caller sends the reply with the handles,
 * or closes them if it can't. */
static inline uint32_t dns_run_slot(handle_t ch, const struct idl_slot *slot,
                                    const struct dns_ops *ops, void *ctx, handle_t *rhs, uint32_t *rhn)
{
    *rhn = 0;
    if (*slot->n >= sizeof(uint32_t) && *slot->nh)
        return idl_refuse(slot);
    return dns_dispatch_on(ch, ops, ctx, slot->q, *slot->n, slot->r, rhs, rhn);
}

/* Is the method with this wire ordinal idempotent (its keyword in the
 * .idl): run again on the state its first run left, it gives the same
 * result and the same answer? A server that keeps nothing across a
 * restart may run such a request again; any other it answers with an
 * error. */
static inline bool dns_idempotent(uint32_t ordinal)
{
    (void)ordinal;
    return false;   /* no method is marked */
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t dns_serve_one(handle_t ch, const struct dns_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[DNS_REQ_MAX];
    _Alignas(8) uint8_t idl_r[DNS_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = dns_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t dns_serve(handle_t ch, const struct dns_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[DNS_REQ_MAX];
    _Alignas(8) uint8_t idl_r[DNS_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = dns_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
