/* Generated by tools/genidl.py from abi/idl/fs.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `fs` (id 16). Client: fs_<method>(ch, args..., &results...)
 * (and fs_<method>_until with a deadline, _within with a timeout), or
 * fs_<method>_send and fs_<method>_result without waiting. Server:
 * fill a struct fs_ops and run fs_serve(ch, &ops, ctx), or
 * fs_serve_one / fs_dispatch_on for a loop of your own;
 * fs_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define FS_PROTOCOL_ID 16u
#define FS_OPEN             0x00100001u
#define FS_STAT             0x00100002u
#define FS_READDIR          0x00100003u
#define FS_MKDIR            0x00100004u
#define FS_UNLINK           0x00100005u
#define FS_RENAME           0x00100006u
#define FS_SYNC             0x00100007u
#define FS_STATFS           0x00100008u
#define FS_VIEW             0x00100009u

/* Messages (packed: no padding bytes ever cross the channel). */
struct fs_open_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[256];
    uint32_t flags;
} __attribute__((packed));
struct fs_open_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t size;
} __attribute__((packed));
struct fs_stat_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[256];
} __attribute__((packed));
struct fs_stat_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t size;
    uint8_t is_dir;
    uint64_t mtime;
} __attribute__((packed));
struct fs_readdir_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[256];
    uint32_t index;
} __attribute__((packed));
struct fs_readdir_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t name[256];
    uint8_t is_dir;
    uint64_t size;
} __attribute__((packed));
struct fs_mkdir_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[256];
} __attribute__((packed));
struct fs_mkdir_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct fs_unlink_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[256];
} __attribute__((packed));
struct fs_unlink_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct fs_rename_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t from[256];
    uint8_t to[256];
} __attribute__((packed));
struct fs_rename_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct fs_sync_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct fs_sync_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct fs_statfs_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct fs_statfs_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t total;
    uint64_t free;
    uint8_t read_only;
    uint8_t label[16];
} __attribute__((packed));
struct fs_view_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t flags;
} __attribute__((packed));
struct fs_view_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define FS_REQ_MAX 520u   /* bytes: the biggest request */
#define FS_REP_MAX 273u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* fs_open_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_open_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[256], uint32_t flags, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size)
{
    struct fs_open_req idl_q;
    struct fs_open_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_OPEN;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.flags = flags;
    handle_t idl_rh[2];
    uint32_t idl_rhn = 0;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, idl_rh,
                               2, &idl_rhn, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 2)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_file)
            *out_file = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK) {
        if (out_buffer)
            *out_buffer = idl_rh[1];
        else
            drv_handle_close(idl_rh[1]);
    }
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    return idl_st;
}
/* Open a file (not a directory). flags: FS_READ 1, FS_WRITE 2, FS_CREATE 4,
 * FS_TRUNCATE 8, FS_APPEND 16, FS_GATHER 32 (<os.h>). `file` speaks the file protocol;
 * `buffer` is the VMO its reads and writes go through; `size` is the file's
 * size now. Closing `file` closes the file. */
static inline status_t fs_open_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[256], uint32_t flags, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size)
{
    return fs_open_call(ch, false, deadline_ns, path, flags, out_file, out_buffer, out_size);
}
static inline status_t fs_open_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[256], uint32_t flags, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size)
{
    return fs_open_call(ch, true, timeout_ns, path, flags, out_file, out_buffer, out_size);
}
static inline status_t fs_open(handle_t ch, const uint8_t path[256], uint32_t flags, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size)
{
    return fs_open_call(ch, false, DEADLINE_NEVER, path, flags, out_file, out_buffer, out_size);
}

/* fs_stat_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_stat_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[256], uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime)
{
    struct fs_stat_req idl_q;
    struct fs_stat_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_STAT;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    if (idl_st == OK && out_is_dir)
        *out_is_dir = idl_r.is_dir;
    if (idl_st == OK && out_mtime)
        *out_mtime = idl_r.mtime;
    return idl_st;
}
/* A file or directory: its size (0 for a directory), 1 if a directory,
 * the modification time (Unix seconds, 0 if unknown). */
static inline status_t fs_stat_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[256], uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime)
{
    return fs_stat_call(ch, false, deadline_ns, path, out_size, out_is_dir, out_mtime);
}
static inline status_t fs_stat_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[256], uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime)
{
    return fs_stat_call(ch, true, timeout_ns, path, out_size, out_is_dir, out_mtime);
}
static inline status_t fs_stat(handle_t ch, const uint8_t path[256], uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime)
{
    return fs_stat_call(ch, false, DEADLINE_NEVER, path, out_size, out_is_dir, out_mtime);
}

/* fs_readdir_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_readdir_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[256], uint32_t index, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size)
{
    struct fs_readdir_req idl_q;
    struct fs_readdir_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_READDIR;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.index = index;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_name && idl_i < 256; idl_i++)
        out_name[idl_i] = idl_r.name[idl_i];
    if (idl_st == OK && out_is_dir)
        *out_is_dir = idl_r.is_dir;
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    return idl_st;
}
/* Entry `index` (0-based) of directory `path`, "." and ".." left out.
 * Past the last: ERR_NOT_FOUND. Entries may shift if the directory changes
 * between calls. Asked in order (0, 1, 2, ...), a listing costs the service
 * one entry read per entry: fat keeps a cursor per directory being listed. */
static inline status_t fs_readdir_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[256], uint32_t index, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size)
{
    return fs_readdir_call(ch, false, deadline_ns, path, index, out_name, out_is_dir, out_size);
}
static inline status_t fs_readdir_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[256], uint32_t index, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size)
{
    return fs_readdir_call(ch, true, timeout_ns, path, index, out_name, out_is_dir, out_size);
}
static inline status_t fs_readdir(handle_t ch, const uint8_t path[256], uint32_t index, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size)
{
    return fs_readdir_call(ch, false, DEADLINE_NEVER, path, index, out_name, out_is_dir, out_size);
}

/* fs_mkdir_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_mkdir_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[256])
{
    struct fs_mkdir_req idl_q;
    struct fs_mkdir_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_MKDIR;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t fs_mkdir_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[256])
{
    return fs_mkdir_call(ch, false, deadline_ns, path);
}
static inline status_t fs_mkdir_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[256])
{
    return fs_mkdir_call(ch, true, timeout_ns, path);
}
static inline status_t fs_mkdir(handle_t ch, const uint8_t path[256])
{
    return fs_mkdir_call(ch, false, DEADLINE_NEVER, path);
}

/* fs_unlink_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_unlink_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[256])
{
    struct fs_unlink_req idl_q;
    struct fs_unlink_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_UNLINK;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Remove a file, or an empty directory. */
static inline status_t fs_unlink_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[256])
{
    return fs_unlink_call(ch, false, deadline_ns, path);
}
static inline status_t fs_unlink_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[256])
{
    return fs_unlink_call(ch, true, timeout_ns, path);
}
static inline status_t fs_unlink(handle_t ch, const uint8_t path[256])
{
    return fs_unlink_call(ch, false, DEADLINE_NEVER, path);
}

/* fs_rename_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_rename_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t from[256], const uint8_t to[256])
{
    struct fs_rename_req idl_q;
    struct fs_rename_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_RENAME;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.from[idl_i] = from[idl_i];
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.to[idl_i] = to[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Rename or move within this filesystem. */
static inline status_t fs_rename_until(handle_t ch, uint64_t deadline_ns, const uint8_t from[256], const uint8_t to[256])
{
    return fs_rename_call(ch, false, deadline_ns, from, to);
}
static inline status_t fs_rename_within(handle_t ch, uint64_t timeout_ns, const uint8_t from[256], const uint8_t to[256])
{
    return fs_rename_call(ch, true, timeout_ns, from, to);
}
static inline status_t fs_rename(handle_t ch, const uint8_t from[256], const uint8_t to[256])
{
    return fs_rename_call(ch, false, DEADLINE_NEVER, from, to);
}

/* fs_sync_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_sync_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct fs_sync_req idl_q;
    struct fs_sync_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_SYNC;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Everything written through this filesystem is on the medium. */
static inline status_t fs_sync_until(handle_t ch, uint64_t deadline_ns)
{
    return fs_sync_call(ch, false, deadline_ns);
}
static inline status_t fs_sync_within(handle_t ch, uint64_t timeout_ns)
{
    return fs_sync_call(ch, true, timeout_ns);
}
static inline status_t fs_sync(handle_t ch)
{
    return fs_sync_call(ch, false, DEADLINE_NEVER);
}

/* fs_statfs_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_statfs_call(handle_t ch, bool idl_within, uint64_t idl_t, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16])
{
    struct fs_statfs_req idl_q;
    struct fs_statfs_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_STATFS;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_total)
        *out_total = idl_r.total;
    if (idl_st == OK && out_free)
        *out_free = idl_r.free;
    if (idl_st == OK && out_read_only)
        *out_read_only = idl_r.read_only;
    for (uint32_t idl_i = 0; idl_st == OK && out_label && idl_i < 16; idl_i++)
        out_label[idl_i] = idl_r.label[idl_i];
    return idl_st;
}
/* Bytes in the filesystem and bytes free, 1 if read-only, and the volume
 * label (NUL-terminated). */
static inline status_t fs_statfs_until(handle_t ch, uint64_t deadline_ns, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16])
{
    return fs_statfs_call(ch, false, deadline_ns, out_total, out_free, out_read_only, out_label);
}
static inline status_t fs_statfs_within(handle_t ch, uint64_t timeout_ns, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16])
{
    return fs_statfs_call(ch, true, timeout_ns, out_total, out_free, out_read_only, out_label);
}
static inline status_t fs_statfs(handle_t ch, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16])
{
    return fs_statfs_call(ch, false, DEADLINE_NEVER, out_total, out_free, out_read_only, out_label);
}

/* fs_view_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t fs_view_call(handle_t ch, bool idl_within, uint64_t idl_t, uint32_t flags, handle_t *out_fs)
{
    struct fs_view_req idl_q;
    struct fs_view_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = FS_VIEW;
    idl_q.flags = flags;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, idl_rh,
                               1, &idl_rhn, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_fs)
            *out_fs = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    return idl_st;
}
/* A narrower channel onto this filesystem (a "view"), for a program that
 * should have less of it than the caller: flags FS_VIEW_READ_ONLY 1 (every
 * request that would change the volume is ERR_ACCESS_DENIED, and statfs
 * says read-only) and FS_VIEW_GUARD_ETC 2 (the same for anything at or
 * under the volume's top-level `etc` directory) (<fsview.h>). The new
 * channel keeps this channel's own flags too, so a view is never wider
 * than the channel it came from. ERR_INVALID_ARGS: an unknown flag;
 * ERR_NO_RESOURCES: the service serves as many channels as it can. */
static inline status_t fs_view_until(handle_t ch, uint64_t deadline_ns, uint32_t flags, handle_t *out_fs)
{
    return fs_view_call(ch, false, deadline_ns, flags, out_fs);
}
static inline status_t fs_view_within(handle_t ch, uint64_t timeout_ns, uint32_t flags, handle_t *out_fs)
{
    return fs_view_call(ch, true, timeout_ns, flags, out_fs);
}
static inline status_t fs_view(handle_t ch, uint32_t flags, handle_t *out_fs)
{
    return fs_view_call(ch, false, DEADLINE_NEVER, flags, out_fs);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* fs_open without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_open_result. */
static inline status_t fs_open_send(handle_t ch, uint32_t idl_txid, const uint8_t path[256], uint32_t flags)
{
    struct fs_open_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_OPEN;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.flags = flags;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_open_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_open_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size)
{
    const struct fs_open_rep *idl_r = (const struct fs_open_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 2)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_file)
        *out_file = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    if (out_buffer)
        *out_buffer = idl_m->hs[1];
    else
        drv_handle_close(idl_m->hs[1]);
    idl_m->nh = 0;
    if (out_size)
        *out_size = idl_r->size;
    return OK;
}

/* fs_stat without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_stat_result. */
static inline status_t fs_stat_send(handle_t ch, uint32_t idl_txid, const uint8_t path[256])
{
    struct fs_stat_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_STAT;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_stat_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_stat_result(const void *idl_rep, struct idl_msg *idl_m, uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime)
{
    const struct fs_stat_rep *idl_r = (const struct fs_stat_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_size)
        *out_size = idl_r->size;
    if (out_is_dir)
        *out_is_dir = idl_r->is_dir;
    if (out_mtime)
        *out_mtime = idl_r->mtime;
    return OK;
}

/* fs_readdir without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_readdir_result. */
static inline status_t fs_readdir_send(handle_t ch, uint32_t idl_txid, const uint8_t path[256], uint32_t index)
{
    struct fs_readdir_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_READDIR;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.index = index;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_readdir_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_readdir_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size)
{
    const struct fs_readdir_rep *idl_r = (const struct fs_readdir_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_name && idl_i < 256; idl_i++)
        out_name[idl_i] = idl_r->name[idl_i];
    if (out_is_dir)
        *out_is_dir = idl_r->is_dir;
    if (out_size)
        *out_size = idl_r->size;
    return OK;
}

/* fs_mkdir without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_mkdir_result. */
static inline status_t fs_mkdir_send(handle_t ch, uint32_t idl_txid, const uint8_t path[256])
{
    struct fs_mkdir_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_MKDIR;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_mkdir_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_mkdir_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct fs_mkdir_rep *idl_r = (const struct fs_mkdir_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* fs_unlink without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_unlink_result. */
static inline status_t fs_unlink_send(handle_t ch, uint32_t idl_txid, const uint8_t path[256])
{
    struct fs_unlink_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_UNLINK;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_unlink_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_unlink_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct fs_unlink_rep *idl_r = (const struct fs_unlink_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* fs_rename without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_rename_result. */
static inline status_t fs_rename_send(handle_t ch, uint32_t idl_txid, const uint8_t from[256], const uint8_t to[256])
{
    struct fs_rename_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_RENAME;
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.from[idl_i] = from[idl_i];
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_q.to[idl_i] = to[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_rename_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_rename_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct fs_rename_rep *idl_r = (const struct fs_rename_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* fs_sync without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_sync_result. */
static inline status_t fs_sync_send(handle_t ch, uint32_t idl_txid)
{
    struct fs_sync_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_SYNC;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_sync_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_sync_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct fs_sync_rep *idl_r = (const struct fs_sync_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* fs_statfs without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_statfs_result. */
static inline status_t fs_statfs_send(handle_t ch, uint32_t idl_txid)
{
    struct fs_statfs_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_STATFS;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_statfs_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_statfs_result(const void *idl_rep, struct idl_msg *idl_m, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16])
{
    const struct fs_statfs_rep *idl_r = (const struct fs_statfs_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_total)
        *out_total = idl_r->total;
    if (out_free)
        *out_free = idl_r->free;
    if (out_read_only)
        *out_read_only = idl_r->read_only;
    for (uint32_t idl_i = 0; out_label && idl_i < 16; idl_i++)
        out_label[idl_i] = idl_r->label[idl_i];
    return OK;
}

/* fs_view without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then fs_view_result. */
static inline status_t fs_view_send(handle_t ch, uint32_t idl_txid, uint32_t flags)
{
    struct fs_view_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = FS_VIEW;
    idl_q.flags = flags;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to fs_view_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t fs_view_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_fs)
{
    const struct fs_view_rep *idl_r = (const struct fs_view_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_fs)
        *out_fs = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with fs_reply_<method> (now, or later from anywhere). */
struct fs_ops {
    status_t (*open)(void *ctx, const uint8_t path[256], uint32_t flags, handle_t *out_file, handle_t *out_buffer, uint64_t *out_size);
    status_t (*stat)(void *ctx, const uint8_t path[256], uint64_t *out_size, uint8_t *out_is_dir, uint64_t *out_mtime);
    status_t (*readdir)(void *ctx, const uint8_t path[256], uint32_t index, uint8_t out_name[256], uint8_t *out_is_dir, uint64_t *out_size);
    status_t (*mkdir)(void *ctx, const uint8_t path[256]);
    status_t (*unlink)(void *ctx, const uint8_t path[256]);
    status_t (*rename)(void *ctx, const uint8_t from[256], const uint8_t to[256]);
    status_t (*sync)(void *ctx);
    status_t (*statfs)(void *ctx, uint64_t *out_total, uint64_t *out_free, uint8_t *out_read_only, uint8_t out_label[16]);
    status_t (*view)(void *ctx, uint32_t flags, handle_t *out_fs);
};

/* Answer the fs.open request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_open(struct idl_txn idl_txn, status_t idl_st, handle_t file, handle_t buffer, uint64_t size)
{
    struct fs_open_rep idl_r;
    handle_t idl_hs[2] = { file, buffer };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(file != HANDLE_INVALID && buffer != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        if (idl_hs[1] != HANDLE_INVALID)
            drv_handle_close(idl_hs[1]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    idl_r.size = size;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 2);
}

/* Answer the fs.stat request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_stat(struct idl_txn idl_txn, status_t idl_st, uint64_t size, uint8_t is_dir, uint64_t mtime)
{
    struct fs_stat_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.size = size;
    idl_r.is_dir = is_dir;
    idl_r.mtime = mtime;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.readdir request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_readdir(struct idl_txn idl_txn, status_t idl_st, const uint8_t name[256], uint8_t is_dir, uint64_t size)
{
    struct fs_readdir_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_r.name[idl_i] = name[idl_i];
    idl_r.is_dir = is_dir;
    idl_r.size = size;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.mkdir request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_mkdir(struct idl_txn idl_txn, status_t idl_st)
{
    struct fs_mkdir_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.unlink request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_unlink(struct idl_txn idl_txn, status_t idl_st)
{
    struct fs_unlink_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.rename request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_rename(struct idl_txn idl_txn, status_t idl_st)
{
    struct fs_rename_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.sync request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_sync(struct idl_txn idl_txn, status_t idl_st)
{
    struct fs_sync_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.statfs request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_statfs(struct idl_txn idl_txn, status_t idl_st, uint64_t total, uint64_t free, uint8_t read_only, const uint8_t label[16])
{
    struct fs_statfs_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.total = total;
    idl_r.free = free;
    idl_r.read_only = read_only;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_r.label[idl_i] = label[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the fs.view request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t fs_reply_view(struct idl_txn idl_txn, status_t idl_st, handle_t fs)
{
    struct fs_view_rep idl_r;
    handle_t idl_hs[1] = { fs };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(fs != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (FS_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t fs_dispatch_on(handle_t ch, const struct fs_ops *ops, void *ctx,
                                      const void *req, uint32_t n, void *rep, handle_t *rhs,
                                      uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case FS_OPEN: {
        const struct fs_open_req *idl_q = (const struct fs_open_req *)req;
        struct fs_open_rep *idl_r = (struct fs_open_rep *)rep;
        handle_t out_file = HANDLE_INVALID;
        handle_t out_buffer = HANDLE_INVALID;
        uint64_t out_size = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->open) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->open(ctx, idl_q->path, idl_q->flags, &out_file, &out_buffer, &out_size);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_file != HANDLE_INVALID && out_buffer != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_file != HANDLE_INVALID)
                drv_handle_close(out_file);
            if (out_buffer != HANDLE_INVALID)
                drv_handle_close(out_buffer);
            return sizeof(*idl_h);
        }
        rhs[0] = out_file;
        rhs[1] = out_buffer;
        *rhn = 2;
        idl_r->size = out_size;
        return sizeof(*idl_r);
    }
    case FS_STAT: {
        const struct fs_stat_req *idl_q = (const struct fs_stat_req *)req;
        struct fs_stat_rep *idl_r = (struct fs_stat_rep *)rep;
        uint64_t out_size = 0;
        uint8_t out_is_dir = 0;
        uint64_t out_mtime = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->stat) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->stat(ctx, idl_q->path, &out_size, &out_is_dir, &out_mtime);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->size = out_size;
        idl_r->is_dir = out_is_dir;
        idl_r->mtime = out_mtime;
        return sizeof(*idl_r);
    }
    case FS_READDIR: {
        const struct fs_readdir_req *idl_q = (const struct fs_readdir_req *)req;
        struct fs_readdir_rep *idl_r = (struct fs_readdir_rep *)rep;
        uint8_t out_name[256];
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            out_name[idl_i] = 0;
        uint8_t out_is_dir = 0;
        uint64_t out_size = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->readdir) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->readdir(ctx, idl_q->path, idl_q->index, out_name, &out_is_dir, &out_size);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            idl_r->name[idl_i] = out_name[idl_i];
        idl_r->is_dir = out_is_dir;
        idl_r->size = out_size;
        return sizeof(*idl_r);
    }
    case FS_MKDIR: {
        const struct fs_mkdir_req *idl_q = (const struct fs_mkdir_req *)req;
        struct fs_mkdir_rep *idl_r = (struct fs_mkdir_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->mkdir) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->mkdir(ctx, idl_q->path);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case FS_UNLINK: {
        const struct fs_unlink_req *idl_q = (const struct fs_unlink_req *)req;
        struct fs_unlink_rep *idl_r = (struct fs_unlink_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->unlink) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->unlink(ctx, idl_q->path);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case FS_RENAME: {
        const struct fs_rename_req *idl_q = (const struct fs_rename_req *)req;
        struct fs_rename_rep *idl_r = (struct fs_rename_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->rename) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->rename(ctx, idl_q->from, idl_q->to);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case FS_SYNC: {
        const struct fs_sync_req *idl_q = (const struct fs_sync_req *)req;
        struct fs_sync_rep *idl_r = (struct fs_sync_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sync) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sync(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case FS_STATFS: {
        const struct fs_statfs_req *idl_q = (const struct fs_statfs_req *)req;
        struct fs_statfs_rep *idl_r = (struct fs_statfs_rep *)rep;
        uint64_t out_total = 0;
        uint64_t out_free = 0;
        uint8_t out_read_only = 0;
        uint8_t out_label[16];
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            out_label[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->statfs) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->statfs(ctx, &out_total, &out_free, &out_read_only, out_label);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->total = out_total;
        idl_r->free = out_free;
        idl_r->read_only = out_read_only;
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            idl_r->label[idl_i] = out_label[idl_i];
        return sizeof(*idl_r);
    }
    case FS_VIEW: {
        const struct fs_view_req *idl_q = (const struct fs_view_req *)req;
        struct fs_view_rep *idl_r = (struct fs_view_rep *)rep;
        handle_t out_fs = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->view) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->view(ctx, idl_q->flags, &out_fs);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_fs != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_fs != HANDLE_INVALID)
                drv_handle_close(out_fs);
            return sizeof(*idl_h);
        }
        rhs[0] = out_fs;
        *rhn = 1;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* fs_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t fs_dispatch(const struct fs_ops *ops, void *ctx, const void *req, uint32_t n,
                                   void *rep, handle_t *rhs, uint32_t *rhn)
{
    return fs_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t fs_serve_one(handle_t ch, const struct fs_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[FS_REQ_MAX];
    _Alignas(8) uint8_t idl_r[FS_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = fs_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t fs_serve(handle_t ch, const struct fs_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[FS_REQ_MAX];
    _Alignas(8) uint8_t idl_r[FS_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = fs_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
