/* Generated by tools/genidl.py from abi/idl/initctl.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `initctl` (id 18). Client: initctl_<method>(ch, args..., &results...)
 * (and initctl_<method>_until with a deadline, _within with a timeout), or
 * initctl_<method>_send and initctl_<method>_result without waiting. Server:
 * fill a struct initctl_ops and run initctl_serve(ch, &ops, ctx), or
 * initctl_serve_one / initctl_dispatch_on for a loop of your own, or
 * initctl_take_slot / initctl_run_slot for requests read into slots that outlive
 * the server; initctl_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define INITCTL_PROTOCOL_ID 18u
#define INITCTL_KILL             0x00120001u
#define INITCTL_SYNC             0x00120002u
#define INITCTL_REBOOT           0x00120003u
#define INITCTL_MOUNT            0x00120004u
#define INITCTL_SHELL_READY      0x00120005u
#define INITCTL_REBOOT_FIRMWARE  0x00120006u
#define INITCTL_KERNEL_LOAD      0x00120007u
#define INITCTL_UPDATE_OFFER     0x00120008u

/* Messages (packed: no padding bytes ever cross the channel). */
struct initctl_kill_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t name[32];
} __attribute__((packed));
struct initctl_kill_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t koid;
} __attribute__((packed));
struct initctl_sync_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_sync_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_reboot_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_reboot_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_mount_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[16];
    uint8_t writable;
} __attribute__((packed));
struct initctl_mount_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_shell_ready_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_shell_ready_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_reboot_firmware_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_reboot_firmware_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_kernel_load_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_kernel_load_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t kernel_bytes;
    uint64_t bootfs_bytes;
    uint32_t read_ms;
} __attribute__((packed));
struct initctl_update_offer_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_update_offer_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define INITCTL_REQ_MAX 40u   /* bytes: the biggest request */
#define INITCTL_REP_MAX 28u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* initctl_kill_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_kill_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t name[32], uint64_t *out_koid)
{
    struct initctl_kill_req idl_q;
    struct initctl_kill_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_KILL;
    for (uint32_t idl_i = 0; idl_i < 32; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_koid)
        *out_koid = idl_r.koid;
    return idl_st;
}
/* Kill the process called `name` (NUL-terminated, no spaces) and answer
 * with its kernel object id once it is dead: a service init runs ("console",
 * "serialin", "devmgr", "bootfs", "mixer", "music", "serve", "logd",
 * "shell"; init
 * starts it again), or
 * what devmgr runs for a USB device: a class driver ("hid-6.1:0",
 * "usb-storage-1:0") or a disk's filesystem service ("fat-data",
 * "fat-usb0"); devmgr
 * restarts it. ERR_NOT_FOUND: no such process; ERR_INVALID_ARGS: not a
 * name; ERR_ACCESS_DENIED: "init" itself. */
static inline status_t initctl_kill_until(handle_t ch, uint64_t deadline_ns, const uint8_t name[32], uint64_t *out_koid)
{
    return initctl_kill_call(ch, false, deadline_ns, name, out_koid);
}
static inline status_t initctl_kill_within(handle_t ch, uint64_t timeout_ns, const uint8_t name[32], uint64_t *out_koid)
{
    return initctl_kill_call(ch, true, timeout_ns, name, out_koid);
}
static inline status_t initctl_kill(handle_t ch, const uint8_t name[32], uint64_t *out_koid)
{
    return initctl_kill_call(ch, false, DEADLINE_NEVER, name, out_koid);
}

/* initctl_sync_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_sync_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct initctl_sync_req idl_q;
    struct initctl_sync_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_SYNC;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Everything written to /data, and to every /usbN, is on its stick
 * (fs.sync), waiting at most 2 s in all. OK also when there is no /data. */
static inline status_t initctl_sync_until(handle_t ch, uint64_t deadline_ns)
{
    return initctl_sync_call(ch, false, deadline_ns);
}
static inline status_t initctl_sync_within(handle_t ch, uint64_t timeout_ns)
{
    return initctl_sync_call(ch, true, timeout_ns);
}
static inline status_t initctl_sync(handle_t ch)
{
    return initctl_sync_call(ch, false, DEADLINE_NEVER);
}

/* initctl_reboot_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_reboot_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct initctl_reboot_req idl_q;
    struct initctl_reboot_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_REBOOT;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Restart: by kexec into a fresh copy of the system (the kernel's stored
 * copy, or /esp's boot/jamos.elf and boot/bootfs.img if they changed since
 * this boot noted them; everything synced, devmgr's drivers stopped, then
 * the jump), or, if any of that fails, through the firmware (sync, then a
 * reset). Answers only if both failed. The caller blanks the screen first
 * (console.blank): nothing is drawn until the next boot's splash. */
static inline status_t initctl_reboot_until(handle_t ch, uint64_t deadline_ns)
{
    return initctl_reboot_call(ch, false, deadline_ns);
}
static inline status_t initctl_reboot_within(handle_t ch, uint64_t timeout_ns)
{
    return initctl_reboot_call(ch, true, timeout_ns);
}
static inline status_t initctl_reboot(handle_t ch)
{
    return initctl_reboot_call(ch, false, DEADLINE_NEVER);
}

/* initctl_mount_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_mount_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t path[16], uint8_t writable)
{
    struct initctl_mount_req idl_q;
    struct initctl_mount_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_MOUNT;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.writable = writable;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* Make the mount `path` ("/usb0"; NUL-terminated) writable (1) or read-only
 * again (0): devmgr restarts its filesystem service on a `block` channel
 * opened that way (DEVMGR_REMOUNT), so the mount goes and comes back, and
 * files open on it fail ERR_PEER_CLOSED. Answers once devmgr has started
 * the service again; the mount is back a moment later. Only another
 * stick's mounts (/usbN) can be changed: anything else, /boot, /esp and
 * /data included, is ERR_ACCESS_DENIED. ERR_NOT_FOUND: no such mount;
 * ERR_BAD_STATE: its service isn't serving; ERR_INVALID_ARGS: not a path. */
static inline status_t initctl_mount_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[16], uint8_t writable)
{
    return initctl_mount_call(ch, false, deadline_ns, path, writable);
}
static inline status_t initctl_mount_within(handle_t ch, uint64_t timeout_ns, const uint8_t path[16], uint8_t writable)
{
    return initctl_mount_call(ch, true, timeout_ns, path, writable);
}
static inline status_t initctl_mount(handle_t ch, const uint8_t path[16], uint8_t writable)
{
    return initctl_mount_call(ch, false, DEADLINE_NEVER, path, writable);
}

/* initctl_shell_ready_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_shell_ready_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct initctl_shell_ready_req idl_q;
    struct initctl_shell_ready_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_SHELL_READY;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* The shell is up: it has written its banner and reads its keys. init
 * tells the boot splash (bin/splash) to hand the screen back to the
 * console; nothing to do if no splash is waiting (a later shell's call). */
static inline status_t initctl_shell_ready_until(handle_t ch, uint64_t deadline_ns)
{
    return initctl_shell_ready_call(ch, false, deadline_ns);
}
static inline status_t initctl_shell_ready_within(handle_t ch, uint64_t timeout_ns)
{
    return initctl_shell_ready_call(ch, true, timeout_ns);
}
static inline status_t initctl_shell_ready(handle_t ch)
{
    return initctl_shell_ready_call(ch, false, DEADLINE_NEVER);
}

/* initctl_reboot_firmware_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_reboot_firmware_call(handle_t ch, bool idl_within, uint64_t idl_t)
{
    struct initctl_reboot_firmware_req idl_q;
    struct initctl_reboot_firmware_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_REBOOT_FIRMWARE;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
/* A reset through the firmware, never kexec (the shell's `reboot -f`):
 * sync, the log flushed, devmgr's drivers stopped in order (as for
 * reboot), then the kernel's reset. Answers only if the reset failed. */
static inline status_t initctl_reboot_firmware_until(handle_t ch, uint64_t deadline_ns)
{
    return initctl_reboot_firmware_call(ch, false, deadline_ns);
}
static inline status_t initctl_reboot_firmware_within(handle_t ch, uint64_t timeout_ns)
{
    return initctl_reboot_firmware_call(ch, true, timeout_ns);
}
static inline status_t initctl_reboot_firmware(handle_t ch)
{
    return initctl_reboot_firmware_call(ch, false, DEADLINE_NEVER);
}

/* initctl_kernel_load_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_kernel_load_call(handle_t ch, bool idl_within, uint64_t idl_t, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms)
{
    struct initctl_kernel_load_req idl_q;
    struct initctl_kernel_load_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_KERNEL_LOAD;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_kernel_bytes)
        *out_kernel_bytes = idl_r.kernel_bytes;
    if (idl_st == OK && out_bootfs_bytes)
        *out_bootfs_bytes = idl_r.bootfs_bytes;
    if (idl_st == OK && out_read_ms)
        *out_read_ms = idl_r.read_ms;
    return idl_st;
}
/* Read /esp's boot/jamos.elf and boot/bootfs.img now and make them the
 * kernel's stored copy (kexec_load), the one `reboot` and a panic start:
 * a freshly flashed stick is loaded before the reboot, which then reads
 * nothing. Answers their sizes and how long the read took, once loaded.
 * ERR_NOT_FOUND: no /esp, or not both files; the kernel's kexec_load
 * errors (ERR_NOT_SUPPORTED: no stored kernel's region, crashkernel=0;
 * ERR_INVALID_ARGS: not a kernel and a boot image); the stored copy is
 * then unchanged. The shell's channel only. */
static inline status_t initctl_kernel_load_until(handle_t ch, uint64_t deadline_ns, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms)
{
    return initctl_kernel_load_call(ch, false, deadline_ns, out_kernel_bytes, out_bootfs_bytes, out_read_ms);
}
static inline status_t initctl_kernel_load_within(handle_t ch, uint64_t timeout_ns, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms)
{
    return initctl_kernel_load_call(ch, true, timeout_ns, out_kernel_bytes, out_bootfs_bytes, out_read_ms);
}
static inline status_t initctl_kernel_load(handle_t ch, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms)
{
    return initctl_kernel_load_call(ch, false, DEADLINE_NEVER, out_kernel_bytes, out_bootfs_bytes, out_read_ms);
}

/* initctl_update_offer_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t initctl_update_offer_call(handle_t ch, bool idl_within, uint64_t idl_t, handle_t *out_offer)
{
    struct initctl_update_offer_req idl_q;
    struct initctl_update_offer_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_UPDATE_OFFER;
    handle_t idl_rh[1];
    uint32_t idl_got[2] = { 0, 0 };   /* bytes, handles: in a row, one copy-out */
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_got[0],
                               idl_rh, 1, &idl_got[1], idl_within, idl_t);
    uint32_t idl_rhn = idl_got[1];
    idl_n = idl_got[0];
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_offer)
            *out_offer = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    return idl_st;
}
/* A channel for one offer of a fetched build (<update.h>): the caller
 * writes one struct update_offer on it with the kernel's and the boot
 * image's VMOs; init checks the manifest's signature with the update key
 * in its own boot image (none: every offer refused), copies both files,
 * checks each length and SHA-256 against the manifest in the offer, makes
 * them the kernel's stored copy
 * (kexec_load, this boot's command line) and notes /esp's files as seen,
 * so `reboot` starts the fetched build; then it writes one struct
 * update_answer and closes the channel. Any refusal leaves the stored
 * kernel as it was. A newer offer channel closes an older one; while an
 * offer is still being checked: ERR_BAD_STATE. An offer with
 * UPDATE_OFFER_CHECK_ONLY is checked and answered, nothing loaded. Nothing
 * is written to the stick unless the offer has UPDATE_OFFER_WRITE: then
 * init, once it has loaded the build, also writes it to the stick's ESP
 * (only init can: devmgr's ESP channel is its alone) and answers when that
 * is done. The shell's channel only (the tests' programs
 * that ask for `svc init`): the shell's `update` hands the channel to
 * bin/update, the fetcher, which holds nothing else of init's. */
static inline status_t initctl_update_offer_until(handle_t ch, uint64_t deadline_ns, handle_t *out_offer)
{
    return initctl_update_offer_call(ch, false, deadline_ns, out_offer);
}
static inline status_t initctl_update_offer_within(handle_t ch, uint64_t timeout_ns, handle_t *out_offer)
{
    return initctl_update_offer_call(ch, true, timeout_ns, out_offer);
}
static inline status_t initctl_update_offer(handle_t ch, handle_t *out_offer)
{
    return initctl_update_offer_call(ch, false, DEADLINE_NEVER, out_offer);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* initctl_kill without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_kill_result. */
static inline status_t initctl_kill_send(handle_t ch, uint32_t idl_txid, const uint8_t name[32])
{
    struct initctl_kill_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_KILL;
    for (uint32_t idl_i = 0; idl_i < 32; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_kill_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_kill_result(const void *idl_rep, struct idl_msg *idl_m, uint64_t *out_koid)
{
    const struct initctl_kill_rep *idl_r = (const struct initctl_kill_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_koid)
        *out_koid = idl_r->koid;
    return OK;
}

/* initctl_sync without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_sync_result. */
static inline status_t initctl_sync_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_sync_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_SYNC;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_sync_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_sync_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct initctl_sync_rep *idl_r = (const struct initctl_sync_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* initctl_reboot without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_reboot_result. */
static inline status_t initctl_reboot_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_reboot_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_REBOOT;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_reboot_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_reboot_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct initctl_reboot_rep *idl_r = (const struct initctl_reboot_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* initctl_mount without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_mount_result. */
static inline status_t initctl_mount_send(handle_t ch, uint32_t idl_txid, const uint8_t path[16], uint8_t writable)
{
    struct initctl_mount_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_MOUNT;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.writable = writable;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_mount_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_mount_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct initctl_mount_rep *idl_r = (const struct initctl_mount_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* initctl_shell_ready without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_shell_ready_result. */
static inline status_t initctl_shell_ready_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_shell_ready_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_SHELL_READY;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_shell_ready_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_shell_ready_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct initctl_shell_ready_rep *idl_r = (const struct initctl_shell_ready_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* initctl_reboot_firmware without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_reboot_firmware_result. */
static inline status_t initctl_reboot_firmware_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_reboot_firmware_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_REBOOT_FIRMWARE;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_reboot_firmware_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_reboot_firmware_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct initctl_reboot_firmware_rep *idl_r = (const struct initctl_reboot_firmware_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* initctl_kernel_load without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_kernel_load_result. */
static inline status_t initctl_kernel_load_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_kernel_load_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_KERNEL_LOAD;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_kernel_load_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_kernel_load_result(const void *idl_rep, struct idl_msg *idl_m, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms)
{
    const struct initctl_kernel_load_rep *idl_r = (const struct initctl_kernel_load_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_kernel_bytes)
        *out_kernel_bytes = idl_r->kernel_bytes;
    if (out_bootfs_bytes)
        *out_bootfs_bytes = idl_r->bootfs_bytes;
    if (out_read_ms)
        *out_read_ms = idl_r->read_ms;
    return OK;
}

/* initctl_update_offer without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then initctl_update_offer_result. */
static inline status_t initctl_update_offer_send(handle_t ch, uint32_t idl_txid)
{
    struct initctl_update_offer_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = INITCTL_UPDATE_OFFER;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to initctl_update_offer_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t initctl_update_offer_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_offer)
{
    const struct initctl_update_offer_rep *idl_r = (const struct initctl_update_offer_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_offer)
        *out_offer = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with initctl_reply_<method> (now, or later from anywhere). */
struct initctl_ops {
    status_t (*kill)(void *ctx, const uint8_t name[32], uint64_t *out_koid);
    status_t (*sync)(void *ctx);
    status_t (*reboot)(void *ctx);
    status_t (*mount)(void *ctx, const uint8_t path[16], uint8_t writable);
    status_t (*shell_ready)(void *ctx);
    status_t (*reboot_firmware)(void *ctx);
    status_t (*kernel_load)(void *ctx, uint64_t *out_kernel_bytes, uint64_t *out_bootfs_bytes, uint32_t *out_read_ms);
    status_t (*update_offer)(void *ctx, handle_t *out_offer);
};

/* Answer the initctl.kill request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_kill(struct idl_txn idl_txn, status_t idl_st, uint64_t koid)
{
    struct initctl_kill_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.koid = koid;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.sync request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_sync(struct idl_txn idl_txn, status_t idl_st)
{
    struct initctl_sync_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.reboot request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_reboot(struct idl_txn idl_txn, status_t idl_st)
{
    struct initctl_reboot_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.mount request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_mount(struct idl_txn idl_txn, status_t idl_st)
{
    struct initctl_mount_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.shell_ready request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_shell_ready(struct idl_txn idl_txn, status_t idl_st)
{
    struct initctl_shell_ready_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.reboot_firmware request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_reboot_firmware(struct idl_txn idl_txn, status_t idl_st)
{
    struct initctl_reboot_firmware_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.kernel_load request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_kernel_load(struct idl_txn idl_txn, status_t idl_st, uint64_t kernel_bytes, uint64_t bootfs_bytes, uint32_t read_ms)
{
    struct initctl_kernel_load_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.kernel_bytes = kernel_bytes;
    idl_r.bootfs_bytes = bootfs_bytes;
    idl_r.read_ms = read_ms;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the initctl.update_offer request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t initctl_reply_update_offer(struct idl_txn idl_txn, status_t idl_st, handle_t offer)
{
    struct initctl_update_offer_rep idl_r;
    handle_t idl_hs[1] = { offer };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(offer != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (INITCTL_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t initctl_dispatch_on(handle_t ch, const struct initctl_ops *ops, void *ctx,
                                           const void *req, uint32_t n, void *rep, handle_t *rhs,
                                           uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case INITCTL_KILL: {
        const struct initctl_kill_req *idl_q = (const struct initctl_kill_req *)req;
        struct initctl_kill_rep *idl_r = (struct initctl_kill_rep *)rep;
        uint64_t out_koid = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->kill) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->kill(ctx, idl_q->name, &out_koid);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->koid = out_koid;
        return sizeof(*idl_r);
    }
    case INITCTL_SYNC: {
        const struct initctl_sync_req *idl_q = (const struct initctl_sync_req *)req;
        struct initctl_sync_rep *idl_r = (struct initctl_sync_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sync) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sync(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_REBOOT: {
        const struct initctl_reboot_req *idl_q = (const struct initctl_reboot_req *)req;
        struct initctl_reboot_rep *idl_r = (struct initctl_reboot_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->reboot) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->reboot(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_MOUNT: {
        const struct initctl_mount_req *idl_q = (const struct initctl_mount_req *)req;
        struct initctl_mount_rep *idl_r = (struct initctl_mount_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->mount) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->mount(ctx, idl_q->path, idl_q->writable);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_SHELL_READY: {
        const struct initctl_shell_ready_req *idl_q = (const struct initctl_shell_ready_req *)req;
        struct initctl_shell_ready_rep *idl_r = (struct initctl_shell_ready_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->shell_ready) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->shell_ready(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_REBOOT_FIRMWARE: {
        const struct initctl_reboot_firmware_req *idl_q = (const struct initctl_reboot_firmware_req *)req;
        struct initctl_reboot_firmware_rep *idl_r = (struct initctl_reboot_firmware_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->reboot_firmware) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->reboot_firmware(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_KERNEL_LOAD: {
        const struct initctl_kernel_load_req *idl_q = (const struct initctl_kernel_load_req *)req;
        struct initctl_kernel_load_rep *idl_r = (struct initctl_kernel_load_rep *)rep;
        uint64_t out_kernel_bytes = 0;
        uint64_t out_bootfs_bytes = 0;
        uint32_t out_read_ms = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->kernel_load) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->kernel_load(ctx, &out_kernel_bytes, &out_bootfs_bytes, &out_read_ms);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->kernel_bytes = out_kernel_bytes;
        idl_r->bootfs_bytes = out_bootfs_bytes;
        idl_r->read_ms = out_read_ms;
        return sizeof(*idl_r);
    }
    case INITCTL_UPDATE_OFFER: {
        const struct initctl_update_offer_req *idl_q = (const struct initctl_update_offer_req *)req;
        struct initctl_update_offer_rep *idl_r = (struct initctl_update_offer_rep *)rep;
        handle_t out_offer = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->update_offer) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->update_offer(ctx, &out_offer);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_offer != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_offer != HANDLE_INVALID)
                drv_handle_close(out_offer);
            return sizeof(*idl_h);
        }
        rhs[0] = out_offer;
        *rhn = 1;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* initctl_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t initctl_dispatch(const struct initctl_ops *ops, void *ctx, const void *req, uint32_t n,
                                        void *rep, handle_t *rhs, uint32_t *rhn)
{
    return initctl_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take the next message on ch into slot (idl_take), a slot with room for
 * the protocol's biggest request: ERR_INVALID_ARGS if it has less. */
static inline status_t initctl_take_slot(handle_t ch, const struct idl_slot *slot)
{
    if (slot->qcap < INITCTL_REQ_MAX)
        return ERR_INVALID_ARGS;
    return idl_take(ch, slot);
}

/* Run the request in slot (taken by initctl_take_slot, or found there by a
 * successor), which came on ch: as initctl_dispatch_on, its reply built
 * in slot->r and the handles that reply carries put into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). A request that carried handles is
 * answered ERR_INVALID_ARGS without its handler seeing it. Returns the
 * reply's length: 0 means no reply (no txid, or a `later` handler
 * answers it itself). No I/O; the caller sends the reply with the handles,
 * or closes them if it can't. */
static inline uint32_t initctl_run_slot(handle_t ch, const struct idl_slot *slot,
                                        const struct initctl_ops *ops, void *ctx, handle_t *rhs, uint32_t *rhn)
{
    *rhn = 0;
    if (*slot->n >= sizeof(uint32_t) && *slot->nh)
        return idl_refuse(slot);
    return initctl_dispatch_on(ch, ops, ctx, slot->q, *slot->n, slot->r, rhs, rhn);
}

/* Is the method with this wire ordinal idempotent (its keyword in the
 * .idl): run again on the state its first run left, it gives the same
 * result and the same answer? A server that keeps nothing across a
 * restart may run such a request again; any other it answers with an
 * error. */
static inline bool initctl_idempotent(uint32_t ordinal)
{
    (void)ordinal;
    return false;   /* no method is marked */
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t initctl_serve_one(handle_t ch, const struct initctl_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[INITCTL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[INITCTL_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = initctl_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t initctl_serve(handle_t ch, const struct initctl_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[INITCTL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[INITCTL_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = initctl_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
