/* Generated by tools/genidl.py from abi/idl/initctl.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `initctl` (id 18). Client: initctl_<method>(ch, args..., &results...)
 * (and initctl_<method>_until with a deadline) over drv_channel_call. Server:
 * fill a struct initctl_ops and run initctl_serve(ch, &ops, ctx), or
 * initctl_serve_one / initctl_dispatch for a loop of your own. */
#pragma once

#include <idl/common.h>

#define INITCTL_PROTOCOL_ID 18u
#define INITCTL_KILL             0x00120001u
#define INITCTL_SYNC             0x00120002u
#define INITCTL_REBOOT           0x00120003u
#define INITCTL_MOUNT            0x00120004u

/* Messages (packed: no padding bytes ever cross the channel). */
struct initctl_kill_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t name[32];
} __attribute__((packed));
struct initctl_kill_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t koid;
} __attribute__((packed));
struct initctl_sync_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_sync_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_reboot_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct initctl_reboot_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct initctl_mount_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t path[16];
    uint8_t writable;
} __attribute__((packed));
struct initctl_mount_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define INITCTL_REQ_MAX 40u   /* bytes: the biggest request */
#define INITCTL_REP_MAX 16u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* Kill the process called `name` (NUL-terminated, no spaces) and answer
 * with its kernel object id once it is dead: a service init runs ("console",
 * "serialin", "devmgr", "bootfs", "logd", "shell"; init starts it again), or
 * what devmgr runs for a USB device: a class driver ("hid-6.1:0",
 * "usb-storage-1:0") or a disk's filesystem service ("fat-data",
 * "fat-usb0"); devmgr
 * restarts it. ERR_NOT_FOUND: no such process; ERR_INVALID_ARGS: not a
 * name; ERR_ACCESS_DENIED: "init" itself. */
static inline status_t initctl_kill_until(handle_t ch, uint64_t deadline_ns, const uint8_t name[32], uint64_t *out_koid)
{
    struct initctl_kill_req idl_q;
    struct initctl_kill_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_KILL;
    for (uint32_t idl_i = 0; idl_i < 32; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_koid)
        *out_koid = idl_r.koid;
    return idl_st;
}
static inline status_t initctl_kill(handle_t ch, const uint8_t name[32], uint64_t *out_koid)
{
    return initctl_kill_until(ch, DEADLINE_NEVER, name, out_koid);
}

/* Everything written to /data, and to every /usbN, is on its stick
 * (fs.sync), waiting at most 2 s in all. OK also when there is no /data. */
static inline status_t initctl_sync_until(handle_t ch, uint64_t deadline_ns)
{
    struct initctl_sync_req idl_q;
    struct initctl_sync_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_SYNC;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t initctl_sync(handle_t ch)
{
    return initctl_sync_until(ch, DEADLINE_NEVER);
}

/* sync, then reset the machine. Answers only if the reset failed. */
static inline status_t initctl_reboot_until(handle_t ch, uint64_t deadline_ns)
{
    struct initctl_reboot_req idl_q;
    struct initctl_reboot_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_REBOOT;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t initctl_reboot(handle_t ch)
{
    return initctl_reboot_until(ch, DEADLINE_NEVER);
}

/* Make the mount `path` ("/usb0"; NUL-terminated) writable (1) or read-only
 * again (0): devmgr restarts its filesystem service on a `block` channel
 * opened that way (DEVMGR_REMOUNT), so the mount goes and comes back, and
 * files open on it fail ERR_PEER_CLOSED. Answers once devmgr has started
 * the service again; the mount is back a moment later. Only another
 * stick's mounts (/usbN) can be changed: anything else, /boot, /esp and
 * /data included, is ERR_ACCESS_DENIED. ERR_NOT_FOUND: no such mount;
 * ERR_BAD_STATE: its service isn't serving; ERR_INVALID_ARGS: not a path. */
static inline status_t initctl_mount_until(handle_t ch, uint64_t deadline_ns, const uint8_t path[16], uint8_t writable)
{
    struct initctl_mount_req idl_q;
    struct initctl_mount_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = INITCTL_MOUNT;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.path[idl_i] = path[idl_i];
    idl_q.writable = writable;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t initctl_mount(handle_t ch, const uint8_t path[16], uint8_t writable)
{
    return initctl_mount_until(ch, DEADLINE_NEVER, path, writable);
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. */
struct initctl_ops {
    status_t (*kill)(void *ctx, const uint8_t name[32], uint64_t *out_koid);
    status_t (*sync)(void *ctx);
    status_t (*reboot)(void *ctx);
    status_t (*mount)(void *ctx, const uint8_t path[16], uint8_t writable);
};

/* Decode the request of n bytes at req, call its handler, encode the reply
 * into rep (INITCTL_REP_MAX bytes) and the handles it carries into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's length: 0
 * means no reply (the request has no txid). No I/O; the caller sends the
 * reply with the handles, or closes them if it can't. */
static inline uint32_t initctl_dispatch(const struct initctl_ops *ops, void *ctx, const void *req, uint32_t n,
                                        void *rep, handle_t *rhs, uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case INITCTL_KILL: {
        const struct initctl_kill_req *idl_q = (const struct initctl_kill_req *)req;
        struct initctl_kill_rep *idl_r = (struct initctl_kill_rep *)rep;
        uint64_t out_koid = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->kill) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->kill(ctx, idl_q->name, &out_koid);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->koid = out_koid;
        return sizeof(*idl_r);
    }
    case INITCTL_SYNC: {
        const struct initctl_sync_req *idl_q = (const struct initctl_sync_req *)req;
        struct initctl_sync_rep *idl_r = (struct initctl_sync_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sync) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sync(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_REBOOT: {
        const struct initctl_reboot_req *idl_q = (const struct initctl_reboot_req *)req;
        struct initctl_reboot_rep *idl_r = (struct initctl_reboot_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->reboot) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->reboot(ctx);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case INITCTL_MOUNT: {
        const struct initctl_mount_req *idl_q = (const struct initctl_mount_req *)req;
        struct initctl_mount_rep *idl_r = (struct initctl_mount_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->mount) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->mount(ctx, idl_q->path, idl_q->writable);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t initctl_serve_one(handle_t ch, const struct initctl_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[INITCTL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[INITCTL_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = initctl_dispatch(ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t initctl_serve(handle_t ch, const struct initctl_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = initctl_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
