/* Generated by tools/genidl.py from abi/idl/net.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `net` (id 29). Client: net_<method>(ch, args..., &results...)
 * (and net_<method>_until with a deadline) over drv_channel_call, or
 * net_<method>_send and net_<method>_result without waiting. Server:
 * fill a struct net_ops and run net_serve(ch, &ops, ctx), or
 * net_serve_one / net_dispatch_on for a loop of your own;
 * net_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define NET_PROTOCOL_ID 29u
#define NET_IFACE            0x001d0001u
#define NET_WAIT_CHANGE      0x001d0002u
#define NET_COUNTS           0x001d0003u
#define NET_CHIP_COUNTS      0x001d0004u
#define NET_UDP              0x001d0005u
#define NET_ECHO             0x001d0006u
#define NET_SOCK_SEND_TO     0x001d0010u
#define NET_SOCK_RECV        0x001d0011u
#define NET_SOCK_CONNECT     0x001d0012u
#define NET_SOCK_STATE       0x001d0013u

/* Messages (packed: no padding bytes ever cross the channel). */
struct net_iface_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct net_iface_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t address;
    uint32_t mask;
    uint32_t gateway;
    uint32_t dns1;
    uint32_t dns2;
    uint8_t mac[6];
    uint8_t device;
    uint8_t link;
    uint16_t vlan;
    uint32_t speed;
    uint32_t version;
} __attribute__((packed));
struct net_wait_change_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t version;
    uint32_t timeout_ms;
} __attribute__((packed));
struct net_wait_change_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t version;
} __attribute__((packed));
struct net_counts_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct net_counts_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t counts[256];
} __attribute__((packed));
struct net_chip_counts_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct net_chip_counts_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t counts[256];
} __attribute__((packed));
struct net_udp_req {
    uint32_t txid;
    uint32_t ordinal;
    uint16_t port;
} __attribute__((packed));
struct net_udp_rep {
    uint32_t txid;
    int32_t  status;
    uint16_t port;
} __attribute__((packed));
struct net_echo_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t address;
    uint16_t seq;
    uint16_t size;
    uint32_t timeout_ms;
} __attribute__((packed));
struct net_echo_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t rtt_us;
    uint8_t ttl;
    uint16_t size;
} __attribute__((packed));
struct net_sock_send_to_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t address;
    uint16_t port;
    uint16_t len;
    uint8_t data[1472];
} __attribute__((packed));
struct net_sock_send_to_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct net_sock_recv_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t timeout_ms;
} __attribute__((packed));
struct net_sock_recv_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t address;
    uint16_t port;
    uint16_t len;
    uint32_t dropped;
    uint8_t data[1472];
} __attribute__((packed));
struct net_sock_connect_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t address;
    uint16_t port;
} __attribute__((packed));
struct net_sock_connect_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct net_sock_state_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct net_sock_state_rep {
    uint32_t txid;
    int32_t  status;
    uint16_t port;
    uint32_t peer;
    uint16_t peer_port;
    uint32_t queued;
    uint32_t dropped;
} __attribute__((packed));

#define NET_REQ_MAX 1488u   /* bytes: the biggest request */
#define NET_REP_MAX 1492u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* On an opener's channel (or the shared one): the interface. Its address,
 * mask and gateway (0: none), the DNS servers (0: none), its MAC address;
 * `device` 1 while a network card's driver has a session with netstack,
 * `link` 1 while its link is up; the VLAN every frame is tagged with (0
 * without a card), the link speed in Mb/s (0 while down); `version` counts
 * the changes to the address, gateway and DNS servers since netstack
 * started (1 at the start): pass it to wait_change. */
static inline status_t net_iface_until(handle_t ch, uint64_t deadline_ns, uint32_t *out_address, uint32_t *out_mask, uint32_t *out_gateway, uint32_t *out_dns1, uint32_t *out_dns2, uint8_t out_mac[6], uint8_t *out_device, uint8_t *out_link, uint16_t *out_vlan, uint32_t *out_speed, uint32_t *out_version)
{
    struct net_iface_req idl_q;
    struct net_iface_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_IFACE;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_address)
        *out_address = idl_r.address;
    if (idl_st == OK && out_mask)
        *out_mask = idl_r.mask;
    if (idl_st == OK && out_gateway)
        *out_gateway = idl_r.gateway;
    if (idl_st == OK && out_dns1)
        *out_dns1 = idl_r.dns1;
    if (idl_st == OK && out_dns2)
        *out_dns2 = idl_r.dns2;
    for (uint32_t idl_i = 0; idl_st == OK && out_mac && idl_i < 6; idl_i++)
        out_mac[idl_i] = idl_r.mac[idl_i];
    if (idl_st == OK && out_device)
        *out_device = idl_r.device;
    if (idl_st == OK && out_link)
        *out_link = idl_r.link;
    if (idl_st == OK && out_vlan)
        *out_vlan = idl_r.vlan;
    if (idl_st == OK && out_speed)
        *out_speed = idl_r.speed;
    if (idl_st == OK && out_version)
        *out_version = idl_r.version;
    return idl_st;
}
static inline status_t net_iface(handle_t ch, uint32_t *out_address, uint32_t *out_mask, uint32_t *out_gateway, uint32_t *out_dns1, uint32_t *out_dns2, uint8_t out_mac[6], uint8_t *out_device, uint8_t *out_link, uint16_t *out_vlan, uint32_t *out_speed, uint32_t *out_version)
{
    return net_iface_until(ch, DEADLINE_NEVER, out_address, out_mask, out_gateway, out_dns1, out_dns2, out_mac, out_device, out_link, out_vlan, out_speed, out_version);
}

/* On an opener's channel: answered when iface's `version` is no longer
 * `version` (at once if it isn't), with the new one; ERR_TIMED_OUT after
 * timeout_ms (NET_WAIT_FOREVER: no timeout). How a program waits for an
 * address (<net.h> net_wait_up) or for new DNS servers. */
static inline status_t net_wait_change_until(handle_t ch, uint64_t deadline_ns, uint32_t version, uint32_t timeout_ms, uint32_t *out_version)
{
    struct net_wait_change_req idl_q;
    struct net_wait_change_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_WAIT_CHANGE;
    idl_q.version = version;
    idl_q.timeout_ms = timeout_ms;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_version)
        *out_version = idl_r.version;
    return idl_st;
}
static inline status_t net_wait_change(handle_t ch, uint32_t version, uint32_t timeout_ms, uint32_t *out_version)
{
    return net_wait_change_until(ch, DEADLINE_NEVER, version, timeout_ms, out_version);
}

/* On an opener's channel (or the shared one): netstack's counts, as
 * <net.h>'s struct net_counters (little-endian, its reserved fields 0). */
static inline status_t net_counts_until(handle_t ch, uint64_t deadline_ns, uint8_t out_counts[256])
{
    struct net_counts_req idl_q;
    struct net_counts_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_COUNTS;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r.counts[idl_i];
    return idl_st;
}
static inline status_t net_counts(handle_t ch, uint8_t out_counts[256])
{
    return net_counts_until(ch, DEADLINE_NEVER, out_counts);
}

/* On an opener's channel: the network card's own counts, as the driver
 * answers netdev.stats (<jam/netdev.h> struct netdev_stats). ERR_NOT_FOUND:
 * no session with a card's driver; ERR_PEER_CLOSED: the session ended
 * before the driver answered. */
static inline status_t net_chip_counts_until(handle_t ch, uint64_t deadline_ns, uint8_t out_counts[256])
{
    struct net_chip_counts_req idl_q;
    struct net_chip_counts_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_CHIP_COUNTS;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r.counts[idl_i];
    return idl_st;
}
static inline status_t net_chip_counts(handle_t ch, uint8_t out_counts[256])
{
    return net_chip_counts_until(ch, DEADLINE_NEVER, out_counts);
}

/* On an opener's channel: a UDP socket on local port `port`, any local
 * address. port 0: netstack picks one (49152 and up). Results: `socket`,
 * a channel of its own that speaks the sock_* methods (closing it closes
 * the socket), and its port. ERR_ACCESS_DENIED: a port below 1024 (only
 * netctl's DHCP socket has one); ERR_ALREADY_BOUND: the port is taken;
 * ERR_NO_RESOURCES: the opener has NET_SOCKETS_PER_OPENER sockets, or
 * NET_SOCKETS_MAX are open. */
static inline status_t net_udp_until(handle_t ch, uint64_t deadline_ns, uint16_t port, handle_t *out_socket, uint16_t *out_port)
{
    struct net_udp_req idl_q;
    struct net_udp_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_UDP;
    idl_q.port = port;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                         idl_rh, 1, &idl_rhn, deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_socket)
            *out_socket = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK && out_port)
        *out_port = idl_r.port;
    return idl_st;
}
static inline status_t net_udp(handle_t ch, uint16_t port, handle_t *out_socket, uint16_t *out_port)
{
    return net_udp_until(ch, DEADLINE_NEVER, port, out_socket, out_port);
}

/* On an opener's channel: an ICMP echo request (a ping) to `address` with
 * `size` bytes of data (0..NET_DGRAM_MAX) and sequence number `seq`, from
 * the opener's own echo id (netstack picks it: no opener sees another's
 * replies). Answered when the reply comes: the round trip in microseconds,
 * the reply's TTL and its data's size; ERR_TIMED_OUT after timeout_ms
 * (1..60000); ERR_NOT_FOUND: a router or the host said it is unreachable
 * (ICMP destination unreachable). At once: ERR_INVALID_ARGS (not a unicast
 * address, a size or timeout out of range), ERR_BAD_STATE (no address, the
 * link down, no route; or an echo with this seq to this address is in
 * flight), ERR_NO_RESOURCES (NET_LATER_PER_OPENER in flight already). */
static inline status_t net_echo_until(handle_t ch, uint64_t deadline_ns, uint32_t address, uint16_t seq, uint16_t size, uint32_t timeout_ms, uint32_t *out_rtt_us, uint8_t *out_ttl, uint16_t *out_size)
{
    struct net_echo_req idl_q;
    struct net_echo_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_ECHO;
    idl_q.address = address;
    idl_q.seq = seq;
    idl_q.size = size;
    idl_q.timeout_ms = timeout_ms;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_rtt_us)
        *out_rtt_us = idl_r.rtt_us;
    if (idl_st == OK && out_ttl)
        *out_ttl = idl_r.ttl;
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    return idl_st;
}
static inline status_t net_echo(handle_t ch, uint32_t address, uint16_t seq, uint16_t size, uint32_t timeout_ms, uint32_t *out_rtt_us, uint8_t *out_ttl, uint16_t *out_size)
{
    return net_echo_until(ch, DEADLINE_NEVER, address, seq, size, timeout_ms, out_rtt_us, out_ttl, out_size);
}

/* On a socket's channel: send `len` bytes of `data` (the rest is ignored)
 * to address:port. Address 0 and port 0: the peer sock_connect set
 * (ERR_BAD_STATE if none). ERR_INVALID_ARGS: len over NET_DGRAM_MAX, port
 * 0, or an address a program can't send to (0.0.0.0/8, 127.0.0.0/8,
 * multicast, 240.0.0.0/4, a broadcast address: only the DHCP socket sends
 * to 255.255.255.255, and only to port 67); ERR_BAD_STATE: no address, the
 * link down, no route; ERR_NO_MEMORY: netstack's buffers are full;
 * ERR_NO_RESOURCES: the card's transmit ring was full. OK means the
 * datagram went to the card (or waits for the peer's ARP answer), not
 * that it arrived. */
static inline status_t net_sock_send_to_until(handle_t ch, uint64_t deadline_ns, uint32_t address, uint16_t port, uint16_t len, const uint8_t data[1472])
{
    struct net_sock_send_to_req idl_q;
    struct net_sock_send_to_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_SOCK_SEND_TO;
    idl_q.address = address;
    idl_q.port = port;
    idl_q.len = len;
    for (uint32_t idl_i = 0; idl_i < 1472; idl_i++)
        idl_q.data[idl_i] = data[idl_i];
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t net_sock_send_to(handle_t ch, uint32_t address, uint16_t port, uint16_t len, const uint8_t data[1472])
{
    return net_sock_send_to_until(ch, DEADLINE_NEVER, address, port, len, data);
}

/* On a socket's channel: the next datagram queued for this socket: who
 * sent it, its port, its length and bytes (the rest of `data` is 0), and
 * `dropped`, datagrams this socket has dropped (its queue was full) since
 * it opened. Waits up to timeout_ms (0: ERR_SHOULD_WAIT at once if none is
 * queued; NET_WAIT_FOREVER: no timeout); ERR_TIMED_OUT then. One sock_recv
 * waits at a time: ERR_BAD_STATE for a second. */
static inline status_t net_sock_recv_until(handle_t ch, uint64_t deadline_ns, uint32_t timeout_ms, uint32_t *out_address, uint16_t *out_port, uint16_t *out_len, uint32_t *out_dropped, uint8_t out_data[1472])
{
    struct net_sock_recv_req idl_q;
    struct net_sock_recv_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_SOCK_RECV;
    idl_q.timeout_ms = timeout_ms;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_address)
        *out_address = idl_r.address;
    if (idl_st == OK && out_port)
        *out_port = idl_r.port;
    if (idl_st == OK && out_len)
        *out_len = idl_r.len;
    if (idl_st == OK && out_dropped)
        *out_dropped = idl_r.dropped;
    for (uint32_t idl_i = 0; idl_st == OK && out_data && idl_i < 1472; idl_i++)
        out_data[idl_i] = idl_r.data[idl_i];
    return idl_st;
}
static inline status_t net_sock_recv(handle_t ch, uint32_t timeout_ms, uint32_t *out_address, uint16_t *out_port, uint16_t *out_len, uint32_t *out_dropped, uint8_t out_data[1472])
{
    return net_sock_recv_until(ch, DEADLINE_NEVER, timeout_ms, out_address, out_port, out_len, out_dropped, out_data);
}

/* On a socket's channel: from now on only datagrams from address:port are
 * queued (others are dropped, not counted as dropped), and sock_send_to to
 * 0:0 goes there. Address 0 and port 0: any sender again. Datagrams queued
 * already stay. ERR_INVALID_ARGS: an address sock_send_to refuses;
 * ERR_NOT_SUPPORTED on the DHCP socket. */
static inline status_t net_sock_connect_until(handle_t ch, uint64_t deadline_ns, uint32_t address, uint16_t port)
{
    struct net_sock_connect_req idl_q;
    struct net_sock_connect_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_SOCK_CONNECT;
    idl_q.address = address;
    idl_q.port = port;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    return idl_st;
}
static inline status_t net_sock_connect(handle_t ch, uint32_t address, uint16_t port)
{
    return net_sock_connect_until(ch, DEADLINE_NEVER, address, port);
}

/* On a socket's channel: its local port, the peer sock_connect set (0: none),
 * datagrams queued now, and dropped since it opened (its queue was full). */
static inline status_t net_sock_state_until(handle_t ch, uint64_t deadline_ns, uint16_t *out_port, uint32_t *out_peer, uint16_t *out_peer_port, uint32_t *out_queued, uint32_t *out_dropped)
{
    struct net_sock_state_req idl_q;
    struct net_sock_state_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NET_SOCK_STATE;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_port)
        *out_port = idl_r.port;
    if (idl_st == OK && out_peer)
        *out_peer = idl_r.peer;
    if (idl_st == OK && out_peer_port)
        *out_peer_port = idl_r.peer_port;
    if (idl_st == OK && out_queued)
        *out_queued = idl_r.queued;
    if (idl_st == OK && out_dropped)
        *out_dropped = idl_r.dropped;
    return idl_st;
}
static inline status_t net_sock_state(handle_t ch, uint16_t *out_port, uint32_t *out_peer, uint16_t *out_peer_port, uint32_t *out_queued, uint32_t *out_dropped)
{
    return net_sock_state_until(ch, DEADLINE_NEVER, out_port, out_peer, out_peer_port, out_queued, out_dropped);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* net_iface without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_iface_result. */
static inline status_t net_iface_send(handle_t ch, uint32_t idl_txid)
{
    struct net_iface_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_IFACE;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_iface_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_iface_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_address, uint32_t *out_mask, uint32_t *out_gateway, uint32_t *out_dns1, uint32_t *out_dns2, uint8_t out_mac[6], uint8_t *out_device, uint8_t *out_link, uint16_t *out_vlan, uint32_t *out_speed, uint32_t *out_version)
{
    const struct net_iface_rep *idl_r = (const struct net_iface_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_address)
        *out_address = idl_r->address;
    if (out_mask)
        *out_mask = idl_r->mask;
    if (out_gateway)
        *out_gateway = idl_r->gateway;
    if (out_dns1)
        *out_dns1 = idl_r->dns1;
    if (out_dns2)
        *out_dns2 = idl_r->dns2;
    for (uint32_t idl_i = 0; out_mac && idl_i < 6; idl_i++)
        out_mac[idl_i] = idl_r->mac[idl_i];
    if (out_device)
        *out_device = idl_r->device;
    if (out_link)
        *out_link = idl_r->link;
    if (out_vlan)
        *out_vlan = idl_r->vlan;
    if (out_speed)
        *out_speed = idl_r->speed;
    if (out_version)
        *out_version = idl_r->version;
    return OK;
}

/* net_wait_change without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_wait_change_result. */
static inline status_t net_wait_change_send(handle_t ch, uint32_t idl_txid, uint32_t version, uint32_t timeout_ms)
{
    struct net_wait_change_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_WAIT_CHANGE;
    idl_q.version = version;
    idl_q.timeout_ms = timeout_ms;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_wait_change_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_wait_change_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_version)
{
    const struct net_wait_change_rep *idl_r = (const struct net_wait_change_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_version)
        *out_version = idl_r->version;
    return OK;
}

/* net_counts without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_counts_result. */
static inline status_t net_counts_send(handle_t ch, uint32_t idl_txid)
{
    struct net_counts_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_COUNTS;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_counts_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_counts_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_counts[256])
{
    const struct net_counts_rep *idl_r = (const struct net_counts_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r->counts[idl_i];
    return OK;
}

/* net_chip_counts without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_chip_counts_result. */
static inline status_t net_chip_counts_send(handle_t ch, uint32_t idl_txid)
{
    struct net_chip_counts_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_CHIP_COUNTS;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_chip_counts_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_chip_counts_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_counts[256])
{
    const struct net_chip_counts_rep *idl_r = (const struct net_chip_counts_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r->counts[idl_i];
    return OK;
}

/* net_udp without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_udp_result. */
static inline status_t net_udp_send(handle_t ch, uint32_t idl_txid, uint16_t port)
{
    struct net_udp_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_UDP;
    idl_q.port = port;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_udp_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_udp_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_socket, uint16_t *out_port)
{
    const struct net_udp_rep *idl_r = (const struct net_udp_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_socket)
        *out_socket = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    if (out_port)
        *out_port = idl_r->port;
    return OK;
}

/* net_echo without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_echo_result. */
static inline status_t net_echo_send(handle_t ch, uint32_t idl_txid, uint32_t address, uint16_t seq, uint16_t size, uint32_t timeout_ms)
{
    struct net_echo_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_ECHO;
    idl_q.address = address;
    idl_q.seq = seq;
    idl_q.size = size;
    idl_q.timeout_ms = timeout_ms;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_echo_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_echo_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_rtt_us, uint8_t *out_ttl, uint16_t *out_size)
{
    const struct net_echo_rep *idl_r = (const struct net_echo_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_rtt_us)
        *out_rtt_us = idl_r->rtt_us;
    if (out_ttl)
        *out_ttl = idl_r->ttl;
    if (out_size)
        *out_size = idl_r->size;
    return OK;
}

/* net_sock_send_to without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_sock_send_to_result. */
static inline status_t net_sock_send_to_send(handle_t ch, uint32_t idl_txid, uint32_t address, uint16_t port, uint16_t len, const uint8_t data[1472])
{
    struct net_sock_send_to_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_SOCK_SEND_TO;
    idl_q.address = address;
    idl_q.port = port;
    idl_q.len = len;
    for (uint32_t idl_i = 0; idl_i < 1472; idl_i++)
        idl_q.data[idl_i] = data[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_sock_send_to_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_sock_send_to_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct net_sock_send_to_rep *idl_r = (const struct net_sock_send_to_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* net_sock_recv without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_sock_recv_result. */
static inline status_t net_sock_recv_send(handle_t ch, uint32_t idl_txid, uint32_t timeout_ms)
{
    struct net_sock_recv_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_SOCK_RECV;
    idl_q.timeout_ms = timeout_ms;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_sock_recv_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_sock_recv_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_address, uint16_t *out_port, uint16_t *out_len, uint32_t *out_dropped, uint8_t out_data[1472])
{
    const struct net_sock_recv_rep *idl_r = (const struct net_sock_recv_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_address)
        *out_address = idl_r->address;
    if (out_port)
        *out_port = idl_r->port;
    if (out_len)
        *out_len = idl_r->len;
    if (out_dropped)
        *out_dropped = idl_r->dropped;
    for (uint32_t idl_i = 0; out_data && idl_i < 1472; idl_i++)
        out_data[idl_i] = idl_r->data[idl_i];
    return OK;
}

/* net_sock_connect without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_sock_connect_result. */
static inline status_t net_sock_connect_send(handle_t ch, uint32_t idl_txid, uint32_t address, uint16_t port)
{
    struct net_sock_connect_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_SOCK_CONNECT;
    idl_q.address = address;
    idl_q.port = port;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_sock_connect_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_sock_connect_result(const void *idl_rep, struct idl_msg *idl_m)
{
    const struct net_sock_connect_rep *idl_r = (const struct net_sock_connect_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    (void)idl_r;
    return OK;
}

/* net_sock_state without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then net_sock_state_result. */
static inline status_t net_sock_state_send(handle_t ch, uint32_t idl_txid)
{
    struct net_sock_state_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NET_SOCK_STATE;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to net_sock_state_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t net_sock_state_result(const void *idl_rep, struct idl_msg *idl_m, uint16_t *out_port, uint32_t *out_peer, uint16_t *out_peer_port, uint32_t *out_queued, uint32_t *out_dropped)
{
    const struct net_sock_state_rep *idl_r = (const struct net_sock_state_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_port)
        *out_port = idl_r->port;
    if (out_peer)
        *out_peer = idl_r->peer;
    if (out_peer_port)
        *out_peer_port = idl_r->peer_port;
    if (out_queued)
        *out_queued = idl_r->queued;
    if (out_dropped)
        *out_dropped = idl_r->dropped;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with net_reply_<method> (now, or later from anywhere). */
struct net_ops {
    status_t (*iface)(void *ctx, uint32_t *out_address, uint32_t *out_mask, uint32_t *out_gateway, uint32_t *out_dns1, uint32_t *out_dns2, uint8_t out_mac[6], uint8_t *out_device, uint8_t *out_link, uint16_t *out_vlan, uint32_t *out_speed, uint32_t *out_version);
    status_t (*wait_change)(void *ctx, struct idl_txn idl_txn, uint32_t version, uint32_t timeout_ms, uint32_t *out_version);
    status_t (*counts)(void *ctx, uint8_t out_counts[256]);
    status_t (*chip_counts)(void *ctx, struct idl_txn idl_txn, uint8_t out_counts[256]);
    status_t (*udp)(void *ctx, uint16_t port, handle_t *out_socket, uint16_t *out_port);
    status_t (*echo)(void *ctx, struct idl_txn idl_txn, uint32_t address, uint16_t seq, uint16_t size, uint32_t timeout_ms, uint32_t *out_rtt_us, uint8_t *out_ttl, uint16_t *out_size);
    status_t (*sock_send_to)(void *ctx, uint32_t address, uint16_t port, uint16_t len, const uint8_t data[1472]);
    status_t (*sock_recv)(void *ctx, struct idl_txn idl_txn, uint32_t timeout_ms, uint32_t *out_address, uint16_t *out_port, uint16_t *out_len, uint32_t *out_dropped, uint8_t out_data[1472]);
    status_t (*sock_connect)(void *ctx, uint32_t address, uint16_t port);
    status_t (*sock_state)(void *ctx, uint16_t *out_port, uint32_t *out_peer, uint16_t *out_peer_port, uint32_t *out_queued, uint32_t *out_dropped);
};

/* Answer the net.iface request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_iface(struct idl_txn idl_txn, status_t idl_st, uint32_t address, uint32_t mask, uint32_t gateway, uint32_t dns1, uint32_t dns2, const uint8_t mac[6], uint8_t device, uint8_t link, uint16_t vlan, uint32_t speed, uint32_t version)
{
    struct net_iface_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.address = address;
    idl_r.mask = mask;
    idl_r.gateway = gateway;
    idl_r.dns1 = dns1;
    idl_r.dns2 = dns2;
    for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
        idl_r.mac[idl_i] = mac[idl_i];
    idl_r.device = device;
    idl_r.link = link;
    idl_r.vlan = vlan;
    idl_r.speed = speed;
    idl_r.version = version;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.wait_change request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_wait_change(struct idl_txn idl_txn, status_t idl_st, uint32_t version)
{
    struct net_wait_change_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.version = version;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.counts request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_counts(struct idl_txn idl_txn, status_t idl_st, const uint8_t counts[256])
{
    struct net_counts_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_r.counts[idl_i] = counts[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.chip_counts request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_chip_counts(struct idl_txn idl_txn, status_t idl_st, const uint8_t counts[256])
{
    struct net_chip_counts_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_r.counts[idl_i] = counts[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.udp request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_udp(struct idl_txn idl_txn, status_t idl_st, handle_t socket, uint16_t port)
{
    struct net_udp_rep idl_r;
    handle_t idl_hs[1] = { socket };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(socket != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    idl_r.port = port;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Answer the net.echo request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_echo(struct idl_txn idl_txn, status_t idl_st, uint32_t rtt_us, uint8_t ttl, uint16_t size)
{
    struct net_echo_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.rtt_us = rtt_us;
    idl_r.ttl = ttl;
    idl_r.size = size;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.sock_send_to request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_sock_send_to(struct idl_txn idl_txn, status_t idl_st)
{
    struct net_sock_send_to_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.sock_recv request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_sock_recv(struct idl_txn idl_txn, status_t idl_st, uint32_t address, uint16_t port, uint16_t len, uint32_t dropped, const uint8_t data[1472])
{
    struct net_sock_recv_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.address = address;
    idl_r.port = port;
    idl_r.len = len;
    idl_r.dropped = dropped;
    for (uint32_t idl_i = 0; idl_i < 1472; idl_i++)
        idl_r.data[idl_i] = data[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.sock_connect request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_sock_connect(struct idl_txn idl_txn, status_t idl_st)
{
    struct net_sock_connect_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the net.sock_state request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t net_reply_sock_state(struct idl_txn idl_txn, status_t idl_st, uint16_t port, uint32_t peer, uint16_t peer_port, uint32_t queued, uint32_t dropped)
{
    struct net_sock_state_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.port = port;
    idl_r.peer = peer;
    idl_r.peer_port = peer_port;
    idl_r.queued = queued;
    idl_r.dropped = dropped;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (NET_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t net_dispatch_on(handle_t ch, const struct net_ops *ops, void *ctx,
                                       const void *req, uint32_t n, void *rep, handle_t *rhs,
                                       uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case NET_IFACE: {
        const struct net_iface_req *idl_q = (const struct net_iface_req *)req;
        struct net_iface_rep *idl_r = (struct net_iface_rep *)rep;
        uint32_t out_address = 0;
        uint32_t out_mask = 0;
        uint32_t out_gateway = 0;
        uint32_t out_dns1 = 0;
        uint32_t out_dns2 = 0;
        uint8_t out_mac[6];
        for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
            out_mac[idl_i] = 0;
        uint8_t out_device = 0;
        uint8_t out_link = 0;
        uint16_t out_vlan = 0;
        uint32_t out_speed = 0;
        uint32_t out_version = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->iface) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->iface(ctx, &out_address, &out_mask, &out_gateway, &out_dns1, &out_dns2, out_mac, &out_device, &out_link, &out_vlan, &out_speed, &out_version);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->address = out_address;
        idl_r->mask = out_mask;
        idl_r->gateway = out_gateway;
        idl_r->dns1 = out_dns1;
        idl_r->dns2 = out_dns2;
        for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
            idl_r->mac[idl_i] = out_mac[idl_i];
        idl_r->device = out_device;
        idl_r->link = out_link;
        idl_r->vlan = out_vlan;
        idl_r->speed = out_speed;
        idl_r->version = out_version;
        return sizeof(*idl_r);
    }
    case NET_WAIT_CHANGE: {
        const struct net_wait_change_req *idl_q = (const struct net_wait_change_req *)req;
        struct net_wait_change_rep *idl_r = (struct net_wait_change_rep *)rep;
        uint32_t out_version = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->wait_change) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        struct idl_txn idl_txn = { ch, idl_h->txid };
        status_t idl_st = ops->wait_change(ctx, idl_txn, idl_q->version, idl_q->timeout_ms, &out_version);
        /* IDL_LATER: the handler answers with net_reply_wait_change. */
        if (idl_st == IDL_LATER)
            return 0;
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->version = out_version;
        return sizeof(*idl_r);
    }
    case NET_COUNTS: {
        const struct net_counts_req *idl_q = (const struct net_counts_req *)req;
        struct net_counts_rep *idl_r = (struct net_counts_rep *)rep;
        uint8_t out_counts[256];
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            out_counts[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->counts) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->counts(ctx, out_counts);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            idl_r->counts[idl_i] = out_counts[idl_i];
        return sizeof(*idl_r);
    }
    case NET_CHIP_COUNTS: {
        const struct net_chip_counts_req *idl_q = (const struct net_chip_counts_req *)req;
        struct net_chip_counts_rep *idl_r = (struct net_chip_counts_rep *)rep;
        uint8_t out_counts[256];
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            out_counts[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->chip_counts) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        struct idl_txn idl_txn = { ch, idl_h->txid };
        status_t idl_st = ops->chip_counts(ctx, idl_txn, out_counts);
        /* IDL_LATER: the handler answers with net_reply_chip_counts. */
        if (idl_st == IDL_LATER)
            return 0;
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            idl_r->counts[idl_i] = out_counts[idl_i];
        return sizeof(*idl_r);
    }
    case NET_UDP: {
        const struct net_udp_req *idl_q = (const struct net_udp_req *)req;
        struct net_udp_rep *idl_r = (struct net_udp_rep *)rep;
        handle_t out_socket = HANDLE_INVALID;
        uint16_t out_port = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->udp) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->udp(ctx, idl_q->port, &out_socket, &out_port);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_socket != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_socket != HANDLE_INVALID)
                drv_handle_close(out_socket);
            return sizeof(*idl_h);
        }
        rhs[0] = out_socket;
        *rhn = 1;
        idl_r->port = out_port;
        return sizeof(*idl_r);
    }
    case NET_ECHO: {
        const struct net_echo_req *idl_q = (const struct net_echo_req *)req;
        struct net_echo_rep *idl_r = (struct net_echo_rep *)rep;
        uint32_t out_rtt_us = 0;
        uint8_t out_ttl = 0;
        uint16_t out_size = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->echo) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        struct idl_txn idl_txn = { ch, idl_h->txid };
        status_t idl_st = ops->echo(ctx, idl_txn, idl_q->address, idl_q->seq, idl_q->size, idl_q->timeout_ms, &out_rtt_us, &out_ttl, &out_size);
        /* IDL_LATER: the handler answers with net_reply_echo. */
        if (idl_st == IDL_LATER)
            return 0;
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->rtt_us = out_rtt_us;
        idl_r->ttl = out_ttl;
        idl_r->size = out_size;
        return sizeof(*idl_r);
    }
    case NET_SOCK_SEND_TO: {
        const struct net_sock_send_to_req *idl_q = (const struct net_sock_send_to_req *)req;
        struct net_sock_send_to_rep *idl_r = (struct net_sock_send_to_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sock_send_to) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sock_send_to(ctx, idl_q->address, idl_q->port, idl_q->len, idl_q->data);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case NET_SOCK_RECV: {
        const struct net_sock_recv_req *idl_q = (const struct net_sock_recv_req *)req;
        struct net_sock_recv_rep *idl_r = (struct net_sock_recv_rep *)rep;
        uint32_t out_address = 0;
        uint16_t out_port = 0;
        uint16_t out_len = 0;
        uint32_t out_dropped = 0;
        uint8_t out_data[1472];
        for (uint32_t idl_i = 0; idl_i < 1472; idl_i++)
            out_data[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sock_recv) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        struct idl_txn idl_txn = { ch, idl_h->txid };
        status_t idl_st = ops->sock_recv(ctx, idl_txn, idl_q->timeout_ms, &out_address, &out_port, &out_len, &out_dropped, out_data);
        /* IDL_LATER: the handler answers with net_reply_sock_recv. */
        if (idl_st == IDL_LATER)
            return 0;
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->address = out_address;
        idl_r->port = out_port;
        idl_r->len = out_len;
        idl_r->dropped = out_dropped;
        for (uint32_t idl_i = 0; idl_i < 1472; idl_i++)
            idl_r->data[idl_i] = out_data[idl_i];
        return sizeof(*idl_r);
    }
    case NET_SOCK_CONNECT: {
        const struct net_sock_connect_req *idl_q = (const struct net_sock_connect_req *)req;
        struct net_sock_connect_rep *idl_r = (struct net_sock_connect_rep *)rep;
        (void)idl_r;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sock_connect) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sock_connect(ctx, idl_q->address, idl_q->port);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        return sizeof(*idl_r);
    }
    case NET_SOCK_STATE: {
        const struct net_sock_state_req *idl_q = (const struct net_sock_state_req *)req;
        struct net_sock_state_rep *idl_r = (struct net_sock_state_rep *)rep;
        uint16_t out_port = 0;
        uint32_t out_peer = 0;
        uint16_t out_peer_port = 0;
        uint32_t out_queued = 0;
        uint32_t out_dropped = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->sock_state) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->sock_state(ctx, &out_port, &out_peer, &out_peer_port, &out_queued, &out_dropped);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->port = out_port;
        idl_r->peer = out_peer;
        idl_r->peer_port = out_peer_port;
        idl_r->queued = out_queued;
        idl_r->dropped = out_dropped;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* net_dispatch_on without the channel (a `later` handler's txn then has none: use net_dispatch_on). */
static inline uint32_t net_dispatch(const struct net_ops *ops, void *ctx, const void *req, uint32_t n,
                                    void *rep, handle_t *rhs, uint32_t *rhn)
{
    return net_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t net_serve_one(handle_t ch, const struct net_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[NET_REQ_MAX];
    _Alignas(8) uint8_t idl_r[NET_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = net_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t net_serve(handle_t ch, const struct net_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = net_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
