/* Generated by tools/genidl.py from abi/idl/netdev.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `netdev` (id 27). Client: netdev_<method>(ch, args..., &results...)
 * (and netdev_<method>_until with a deadline) over drv_channel_call, or
 * netdev_<method>_send and netdev_<method>_result without waiting. Server:
 * fill a struct netdev_ops and run netdev_serve(ch, &ops, ctx), or
 * netdev_serve_one / netdev_dispatch_on for a loop of your own;
 * netdev_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define NETDEV_PROTOCOL_ID 27u
#define NETDEV_INFO             0x001b0001u
#define NETDEV_STATS            0x001b0002u
#define NETDEV_OPEN             0x001b0003u

/* Messages (packed: no padding bytes ever cross the channel). */
struct netdev_info_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct netdev_info_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t mac[6];
    uint16_t vlan;
    uint16_t mtu;
    uint32_t link;
    uint32_t speed;
    uint32_t changes;
    uint8_t chip[16];
} __attribute__((packed));
struct netdev_stats_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct netdev_stats_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t counts[256];
} __attribute__((packed));
struct netdev_open_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct netdev_open_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define NETDEV_REQ_MAX 8u   /* bytes: the biggest request */
#define NETDEV_REP_MAX 264u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* The card. mac: its address (6 bytes, as on the wire). vlan: the mode,
 * the VLAN every frame is tagged with and the only one received
 * (1..4094), or 0x1000 (NETFRAME_MODE_UNTAGGED, <jam/netframe.h>): no
 * frame tagged, only untagged ones received (a driver with the network
 * off doesn't serve). mtu: the largest payload, 1500
 * (NETDEV_MTU: frames of 14..1514 bytes). link: NETDEV_LINK_* bits (up,
 * full duplex). speed: Mb/s, 0 while down. changes: link changes since
 * the driver started (each also signals NETDEV_SIG_LINK on the session's
 * to_stack event): compare with the count you saw last. chip: its name
 * (printable ASCII, NUL-padded), e.g. "RTL8125B", "82574L". */
static inline status_t netdev_info_until(handle_t ch, uint64_t deadline_ns, uint8_t out_mac[6], uint16_t *out_vlan, uint16_t *out_mtu, uint32_t *out_link, uint32_t *out_speed, uint32_t *out_changes, uint8_t out_chip[16])
{
    struct netdev_info_req idl_q;
    struct netdev_info_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NETDEV_INFO;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_mac && idl_i < 6; idl_i++)
        out_mac[idl_i] = idl_r.mac[idl_i];
    if (idl_st == OK && out_vlan)
        *out_vlan = idl_r.vlan;
    if (idl_st == OK && out_mtu)
        *out_mtu = idl_r.mtu;
    if (idl_st == OK && out_link)
        *out_link = idl_r.link;
    if (idl_st == OK && out_speed)
        *out_speed = idl_r.speed;
    if (idl_st == OK && out_changes)
        *out_changes = idl_r.changes;
    for (uint32_t idl_i = 0; idl_st == OK && out_chip && idl_i < 16; idl_i++)
        out_chip[idl_i] = idl_r.chip[idl_i];
    return idl_st;
}
static inline status_t netdev_info(handle_t ch, uint8_t out_mac[6], uint16_t *out_vlan, uint16_t *out_mtu, uint32_t *out_link, uint32_t *out_speed, uint32_t *out_changes, uint8_t out_chip[16])
{
    return netdev_info_until(ch, DEADLINE_NEVER, out_mac, out_vlan, out_mtu, out_link, out_speed, out_changes, out_chip);
}

/* The counts, as <jam/netdev.h>'s struct netdev_stats (little-endian, its
 * reserved fields 0): the driver's since it started, and the chip's own. */
static inline status_t netdev_stats_until(handle_t ch, uint64_t deadline_ns, uint8_t out_counts[256])
{
    struct netdev_stats_req idl_q;
    struct netdev_stats_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NETDEV_STATS;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r.counts[idl_i];
    return idl_st;
}
static inline status_t netdev_stats(handle_t ch, uint8_t out_counts[256])
{
    return netdev_stats_until(ch, DEADLINE_NEVER, out_counts);
}

/* A session: the rings and events of <jam/netdev.h>. Results: `session`,
 * a channel of its own (closing it ends the session; info and stats work
 * on it too, open is refused there with ERR_NOT_SUPPORTED); `tx` and `rx`,
 * the two ring VMOs (NETDEV_RING_BYTES each, NETDEV_RING_RIGHTS: map them
 * read-write and check their headers, netdev_end_attach); `to_driver`
 * (NETDEV_TO_DRIVER_RIGHTS: signal NETDEV_SIG_TX on it) and `to_stack`
 * (NETDEV_TO_STACK_RIGHTS: wait on it for NETDEV_SIG_RX, _TX_ROOM and
 * _LINK, and clear them). Both rings start empty, counts 0. One session at
 * a time: ERR_BAD_STATE while another's channel is open (the driver looks
 * first: a session whose opener has gone is ended then, so a restarted
 * netstack can open at once). ERR_NO_MEMORY: no memory for the rings. */
static inline status_t netdev_open_until(handle_t ch, uint64_t deadline_ns, handle_t *out_session, handle_t *out_tx, handle_t *out_rx, handle_t *out_to_driver, handle_t *out_to_stack)
{
    struct netdev_open_req idl_q;
    struct netdev_open_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NETDEV_OPEN;
    handle_t idl_rh[5];
    uint32_t idl_rhn = 0;
    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                         idl_rh, 5, &idl_rhn, deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 5)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_session)
            *out_session = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK) {
        if (out_tx)
            *out_tx = idl_rh[1];
        else
            drv_handle_close(idl_rh[1]);
    }
    if (idl_st == OK) {
        if (out_rx)
            *out_rx = idl_rh[2];
        else
            drv_handle_close(idl_rh[2]);
    }
    if (idl_st == OK) {
        if (out_to_driver)
            *out_to_driver = idl_rh[3];
        else
            drv_handle_close(idl_rh[3]);
    }
    if (idl_st == OK) {
        if (out_to_stack)
            *out_to_stack = idl_rh[4];
        else
            drv_handle_close(idl_rh[4]);
    }
    return idl_st;
}
static inline status_t netdev_open(handle_t ch, handle_t *out_session, handle_t *out_tx, handle_t *out_rx, handle_t *out_to_driver, handle_t *out_to_stack)
{
    return netdev_open_until(ch, DEADLINE_NEVER, out_session, out_tx, out_rx, out_to_driver, out_to_stack);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* netdev_info without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then netdev_info_result. */
static inline status_t netdev_info_send(handle_t ch, uint32_t idl_txid)
{
    struct netdev_info_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NETDEV_INFO;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to netdev_info_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t netdev_info_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_mac[6], uint16_t *out_vlan, uint16_t *out_mtu, uint32_t *out_link, uint32_t *out_speed, uint32_t *out_changes, uint8_t out_chip[16])
{
    const struct netdev_info_rep *idl_r = (const struct netdev_info_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_mac && idl_i < 6; idl_i++)
        out_mac[idl_i] = idl_r->mac[idl_i];
    if (out_vlan)
        *out_vlan = idl_r->vlan;
    if (out_mtu)
        *out_mtu = idl_r->mtu;
    if (out_link)
        *out_link = idl_r->link;
    if (out_speed)
        *out_speed = idl_r->speed;
    if (out_changes)
        *out_changes = idl_r->changes;
    for (uint32_t idl_i = 0; out_chip && idl_i < 16; idl_i++)
        out_chip[idl_i] = idl_r->chip[idl_i];
    return OK;
}

/* netdev_stats without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then netdev_stats_result. */
static inline status_t netdev_stats_send(handle_t ch, uint32_t idl_txid)
{
    struct netdev_stats_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NETDEV_STATS;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to netdev_stats_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t netdev_stats_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_counts[256])
{
    const struct netdev_stats_rep *idl_r = (const struct netdev_stats_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_counts && idl_i < 256; idl_i++)
        out_counts[idl_i] = idl_r->counts[idl_i];
    return OK;
}

/* netdev_open without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then netdev_open_result. */
static inline status_t netdev_open_send(handle_t ch, uint32_t idl_txid)
{
    struct netdev_open_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NETDEV_OPEN;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to netdev_open_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t netdev_open_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_session, handle_t *out_tx, handle_t *out_rx, handle_t *out_to_driver, handle_t *out_to_stack)
{
    const struct netdev_open_rep *idl_r = (const struct netdev_open_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 5)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_session)
        *out_session = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    if (out_tx)
        *out_tx = idl_m->hs[1];
    else
        drv_handle_close(idl_m->hs[1]);
    if (out_rx)
        *out_rx = idl_m->hs[2];
    else
        drv_handle_close(idl_m->hs[2]);
    if (out_to_driver)
        *out_to_driver = idl_m->hs[3];
    else
        drv_handle_close(idl_m->hs[3]);
    if (out_to_stack)
        *out_to_stack = idl_m->hs[4];
    else
        drv_handle_close(idl_m->hs[4]);
    idl_m->nh = 0;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with netdev_reply_<method> (now, or later from anywhere). */
struct netdev_ops {
    status_t (*info)(void *ctx, uint8_t out_mac[6], uint16_t *out_vlan, uint16_t *out_mtu, uint32_t *out_link, uint32_t *out_speed, uint32_t *out_changes, uint8_t out_chip[16]);
    status_t (*stats)(void *ctx, uint8_t out_counts[256]);
    status_t (*open)(void *ctx, handle_t *out_session, handle_t *out_tx, handle_t *out_rx, handle_t *out_to_driver, handle_t *out_to_stack);
};

/* Answer the netdev.info request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t netdev_reply_info(struct idl_txn idl_txn, status_t idl_st, const uint8_t mac[6], uint16_t vlan, uint16_t mtu, uint32_t link, uint32_t speed, uint32_t changes, const uint8_t chip[16])
{
    struct netdev_info_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
        idl_r.mac[idl_i] = mac[idl_i];
    idl_r.vlan = vlan;
    idl_r.mtu = mtu;
    idl_r.link = link;
    idl_r.speed = speed;
    idl_r.changes = changes;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_r.chip[idl_i] = chip[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the netdev.stats request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t netdev_reply_stats(struct idl_txn idl_txn, status_t idl_st, const uint8_t counts[256])
{
    struct netdev_stats_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
        idl_r.counts[idl_i] = counts[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the netdev.open request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t netdev_reply_open(struct idl_txn idl_txn, status_t idl_st, handle_t session, handle_t tx, handle_t rx, handle_t to_driver, handle_t to_stack)
{
    struct netdev_open_rep idl_r;
    handle_t idl_hs[5] = { session, tx, rx, to_driver, to_stack };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(session != HANDLE_INVALID && tx != HANDLE_INVALID && rx != HANDLE_INVALID && to_driver != HANDLE_INVALID && to_stack != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        if (idl_hs[1] != HANDLE_INVALID)
            drv_handle_close(idl_hs[1]);
        if (idl_hs[2] != HANDLE_INVALID)
            drv_handle_close(idl_hs[2]);
        if (idl_hs[3] != HANDLE_INVALID)
            drv_handle_close(idl_hs[3]);
        if (idl_hs[4] != HANDLE_INVALID)
            drv_handle_close(idl_hs[4]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 5);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (NETDEV_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t netdev_dispatch_on(handle_t ch, const struct netdev_ops *ops, void *ctx,
                                          const void *req, uint32_t n, void *rep, handle_t *rhs,
                                          uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case NETDEV_INFO: {
        const struct netdev_info_req *idl_q = (const struct netdev_info_req *)req;
        struct netdev_info_rep *idl_r = (struct netdev_info_rep *)rep;
        uint8_t out_mac[6];
        for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
            out_mac[idl_i] = 0;
        uint16_t out_vlan = 0;
        uint16_t out_mtu = 0;
        uint32_t out_link = 0;
        uint32_t out_speed = 0;
        uint32_t out_changes = 0;
        uint8_t out_chip[16];
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            out_chip[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->info) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->info(ctx, out_mac, &out_vlan, &out_mtu, &out_link, &out_speed, &out_changes, out_chip);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 6; idl_i++)
            idl_r->mac[idl_i] = out_mac[idl_i];
        idl_r->vlan = out_vlan;
        idl_r->mtu = out_mtu;
        idl_r->link = out_link;
        idl_r->speed = out_speed;
        idl_r->changes = out_changes;
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            idl_r->chip[idl_i] = out_chip[idl_i];
        return sizeof(*idl_r);
    }
    case NETDEV_STATS: {
        const struct netdev_stats_req *idl_q = (const struct netdev_stats_req *)req;
        struct netdev_stats_rep *idl_r = (struct netdev_stats_rep *)rep;
        uint8_t out_counts[256];
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            out_counts[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->stats) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->stats(ctx, out_counts);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 256; idl_i++)
            idl_r->counts[idl_i] = out_counts[idl_i];
        return sizeof(*idl_r);
    }
    case NETDEV_OPEN: {
        const struct netdev_open_req *idl_q = (const struct netdev_open_req *)req;
        struct netdev_open_rep *idl_r = (struct netdev_open_rep *)rep;
        handle_t out_session = HANDLE_INVALID;
        handle_t out_tx = HANDLE_INVALID;
        handle_t out_rx = HANDLE_INVALID;
        handle_t out_to_driver = HANDLE_INVALID;
        handle_t out_to_stack = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->open) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->open(ctx, &out_session, &out_tx, &out_rx, &out_to_driver, &out_to_stack);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_session != HANDLE_INVALID && out_tx != HANDLE_INVALID && out_rx != HANDLE_INVALID && out_to_driver != HANDLE_INVALID && out_to_stack != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_session != HANDLE_INVALID)
                drv_handle_close(out_session);
            if (out_tx != HANDLE_INVALID)
                drv_handle_close(out_tx);
            if (out_rx != HANDLE_INVALID)
                drv_handle_close(out_rx);
            if (out_to_driver != HANDLE_INVALID)
                drv_handle_close(out_to_driver);
            if (out_to_stack != HANDLE_INVALID)
                drv_handle_close(out_to_stack);
            return sizeof(*idl_h);
        }
        rhs[0] = out_session;
        rhs[1] = out_tx;
        rhs[2] = out_rx;
        rhs[3] = out_to_driver;
        rhs[4] = out_to_stack;
        *rhn = 5;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* netdev_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t netdev_dispatch(const struct netdev_ops *ops, void *ctx, const void *req, uint32_t n,
                                       void *rep, handle_t *rhs, uint32_t *rhn)
{
    return netdev_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t netdev_serve_one(handle_t ch, const struct netdev_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[NETDEV_REQ_MAX];
    _Alignas(8) uint8_t idl_r[NETDEV_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = netdev_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t netdev_serve(handle_t ch, const struct netdev_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = netdev_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
