/* Generated by tools/genidl.py from abi/idl/null.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `null` (id 1). Client: null_<method>(ch, args..., &results...)
 * (and null_<method>_until with a deadline) over drv_channel_call. Server:
 * fill a struct null_ops and run null_serve(ch, &ops, ctx), or
 * null_serve_one / null_dispatch for a loop of your own. */
#pragma once

#include <idl/common.h>

#define NULL_PROTOCOL_ID 1u
#define NULL_PING             0x00010001u
#define NULL_ADD              0x00010002u
#define NULL_REVERSE          0x00010003u
#define NULL_MAKE_VMO         0x00010004u

/* Messages (packed: no padding bytes ever cross the channel). */
struct null_ping_req {
    uint32_t txid;
    uint32_t ordinal;
    uint64_t value;
} __attribute__((packed));
struct null_ping_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t value;
} __attribute__((packed));
struct null_add_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t a;
    uint32_t b;
} __attribute__((packed));
struct null_add_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t sum;
} __attribute__((packed));
struct null_reverse_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t data[16];
} __attribute__((packed));
struct null_reverse_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t data[16];
} __attribute__((packed));
struct null_make_vmo_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t size;
    uint8_t fill;
} __attribute__((packed));
struct null_make_vmo_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t size_back;
} __attribute__((packed));

#define NULL_REQ_MAX 24u   /* bytes: the biggest request */
#define NULL_REP_MAX 24u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

static inline status_t null_ping_until(handle_t ch, uint64_t deadline_ns, uint64_t value, uint64_t *out_value)
{
    struct null_ping_req idl_q;
    struct null_ping_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_PING;
    idl_q.value = value;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_value)
        *out_value = idl_r.value;
    return idl_st;
}
static inline status_t null_ping(handle_t ch, uint64_t value, uint64_t *out_value)
{
    return null_ping_until(ch, DEADLINE_NEVER, value, out_value);
}

static inline status_t null_add_until(handle_t ch, uint64_t deadline_ns, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    struct null_add_req idl_q;
    struct null_add_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_ADD;
    idl_q.a = a;
    idl_q.b = b;
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_sum)
        *out_sum = idl_r.sum;
    return idl_st;
}
static inline status_t null_add(handle_t ch, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    return null_add_until(ch, DEADLINE_NEVER, a, b, out_sum);
}

/* A fixed-size byte array each way: the reply is the request reversed. */
static inline status_t null_reverse_until(handle_t ch, uint64_t deadline_ns, const uint8_t data[16], uint8_t out_data[16])
{
    struct null_reverse_req idl_q;
    struct null_reverse_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_REVERSE;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.data[idl_i] = data[idl_i];
    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                       deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_data && idl_i < 16; idl_i++)
        out_data[idl_i] = idl_r.data[idl_i];
    return idl_st;
}
static inline status_t null_reverse(handle_t ch, const uint8_t data[16], uint8_t out_data[16])
{
    return null_reverse_until(ch, DEADLINE_NEVER, data, out_data);
}

/* A handle result (M7): a new VMO of `size` bytes (1..65536) whose first
 * byte is `fill`, and its size back. size 0 or too big: ERR_INVALID_ARGS
 * and no handle. */
static inline status_t null_make_vmo_until(handle_t ch, uint64_t deadline_ns, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    struct null_make_vmo_req idl_q;
    struct null_make_vmo_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_MAKE_VMO;
    idl_q.size = size;
    idl_q.fill = fill;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                         idl_rh, 1, &idl_rhn, deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_vmo)
            *out_vmo = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK && out_size_back)
        *out_size_back = idl_r.size_back;
    return idl_st;
}
static inline status_t null_make_vmo(handle_t ch, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    return null_make_vmo_until(ch, DEADLINE_NEVER, size, fill, out_vmo, out_size_back);
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. */
struct null_ops {
    status_t (*ping)(void *ctx, uint64_t value, uint64_t *out_value);
    status_t (*add)(void *ctx, uint32_t a, uint32_t b, uint32_t *out_sum);
    status_t (*reverse)(void *ctx, const uint8_t data[16], uint8_t out_data[16]);
    status_t (*make_vmo)(void *ctx, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back);
};

/* Decode the request of n bytes at req, call its handler, encode the reply
 * into rep (NULL_REP_MAX bytes) and the handles it carries into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's length: 0
 * means no reply (the request has no txid). No I/O; the caller sends the
 * reply with the handles, or closes them if it can't. */
static inline uint32_t null_dispatch(const struct null_ops *ops, void *ctx, const void *req, uint32_t n,
                                     void *rep, handle_t *rhs, uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case NULL_PING: {
        const struct null_ping_req *idl_q = (const struct null_ping_req *)req;
        struct null_ping_rep *idl_r = (struct null_ping_rep *)rep;
        uint64_t out_value = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->ping) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->ping(ctx, idl_q->value, &out_value);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->value = out_value;
        return sizeof(*idl_r);
    }
    case NULL_ADD: {
        const struct null_add_req *idl_q = (const struct null_add_req *)req;
        struct null_add_rep *idl_r = (struct null_add_rep *)rep;
        uint32_t out_sum = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->add) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->add(ctx, idl_q->a, idl_q->b, &out_sum);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->sum = out_sum;
        return sizeof(*idl_r);
    }
    case NULL_REVERSE: {
        const struct null_reverse_req *idl_q = (const struct null_reverse_req *)req;
        struct null_reverse_rep *idl_r = (struct null_reverse_rep *)rep;
        uint8_t out_data[16];
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            out_data[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->reverse) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->reverse(ctx, idl_q->data, out_data);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            idl_r->data[idl_i] = out_data[idl_i];
        return sizeof(*idl_r);
    }
    case NULL_MAKE_VMO: {
        const struct null_make_vmo_req *idl_q = (const struct null_make_vmo_req *)req;
        struct null_make_vmo_rep *idl_r = (struct null_make_vmo_rep *)rep;
        handle_t out_vmo = HANDLE_INVALID;
        uint64_t out_size_back = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->make_vmo) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->make_vmo(ctx, idl_q->size, idl_q->fill, &out_vmo, &out_size_back);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_vmo != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_vmo != HANDLE_INVALID)
                drv_handle_close(out_vmo);
            return sizeof(*idl_h);
        }
        rhs[0] = out_vmo;
        *rhn = 1;
        idl_r->size_back = out_size_back;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t null_serve_one(handle_t ch, const struct null_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[NULL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[NULL_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = null_dispatch(ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t null_serve(handle_t ch, const struct null_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = null_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
