/* Generated by tools/genidl.py from abi/idl/null.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `null` (id 1). Client: null_<method>(ch, args..., &results...)
 * (and null_<method>_until with a deadline, _within with a timeout), or
 * null_<method>_send and null_<method>_result without waiting. Server:
 * fill a struct null_ops and run null_serve(ch, &ops, ctx), or
 * null_serve_one / null_dispatch_on for a loop of your own, or
 * null_take_slot / null_run_slot for requests read into slots that outlive
 * the server; null_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define NULL_PROTOCOL_ID 1u
#define NULL_PING             0x00010001u
#define NULL_ADD              0x00010002u
#define NULL_REVERSE          0x00010003u
#define NULL_MAKE_VMO         0x00010004u

/* Messages (packed: no padding bytes ever cross the channel). */
struct null_ping_req {
    uint32_t txid;
    uint32_t ordinal;
    uint64_t value;
} __attribute__((packed));
struct null_ping_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t value;
} __attribute__((packed));
struct null_add_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t a;
    uint32_t b;
} __attribute__((packed));
struct null_add_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t sum;
} __attribute__((packed));
struct null_reverse_req {
    uint32_t txid;
    uint32_t ordinal;
    uint8_t data[16];
} __attribute__((packed));
struct null_reverse_rep {
    uint32_t txid;
    int32_t  status;
    uint8_t data[16];
} __attribute__((packed));
struct null_make_vmo_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t size;
    uint8_t fill;
} __attribute__((packed));
struct null_make_vmo_rep {
    uint32_t txid;
    int32_t  status;
    uint64_t size_back;
} __attribute__((packed));

#define NULL_REQ_MAX 24u   /* bytes: the biggest request */
#define NULL_REP_MAX 24u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* null_ping_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t null_ping_call(handle_t ch, bool idl_within, uint64_t idl_t, uint64_t value, uint64_t *out_value)
{
    struct null_ping_req idl_q;
    struct null_ping_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_PING;
    idl_q.value = value;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_value)
        *out_value = idl_r.value;
    return idl_st;
}
static inline status_t null_ping_until(handle_t ch, uint64_t deadline_ns, uint64_t value, uint64_t *out_value)
{
    return null_ping_call(ch, false, deadline_ns, value, out_value);
}
static inline status_t null_ping_within(handle_t ch, uint64_t timeout_ns, uint64_t value, uint64_t *out_value)
{
    return null_ping_call(ch, true, timeout_ns, value, out_value);
}
static inline status_t null_ping(handle_t ch, uint64_t value, uint64_t *out_value)
{
    return null_ping_call(ch, false, DEADLINE_NEVER, value, out_value);
}

/* null_add_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t null_add_call(handle_t ch, bool idl_within, uint64_t idl_t, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    struct null_add_req idl_q;
    struct null_add_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_ADD;
    idl_q.a = a;
    idl_q.b = b;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_sum)
        *out_sum = idl_r.sum;
    return idl_st;
}
static inline status_t null_add_until(handle_t ch, uint64_t deadline_ns, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    return null_add_call(ch, false, deadline_ns, a, b, out_sum);
}
static inline status_t null_add_within(handle_t ch, uint64_t timeout_ns, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    return null_add_call(ch, true, timeout_ns, a, b, out_sum);
}
static inline status_t null_add(handle_t ch, uint32_t a, uint32_t b, uint32_t *out_sum)
{
    return null_add_call(ch, false, DEADLINE_NEVER, a, b, out_sum);
}

/* null_reverse_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t null_reverse_call(handle_t ch, bool idl_within, uint64_t idl_t, const uint8_t data[16], uint8_t out_data[16])
{
    struct null_reverse_req idl_q;
    struct null_reverse_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_REVERSE;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.data[idl_i] = data[idl_i];
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    for (uint32_t idl_i = 0; idl_st == OK && out_data && idl_i < 16; idl_i++)
        out_data[idl_i] = idl_r.data[idl_i];
    return idl_st;
}
/* A fixed-size byte array each way: the reply is the request reversed. */
static inline status_t null_reverse_until(handle_t ch, uint64_t deadline_ns, const uint8_t data[16], uint8_t out_data[16])
{
    return null_reverse_call(ch, false, deadline_ns, data, out_data);
}
static inline status_t null_reverse_within(handle_t ch, uint64_t timeout_ns, const uint8_t data[16], uint8_t out_data[16])
{
    return null_reverse_call(ch, true, timeout_ns, data, out_data);
}
static inline status_t null_reverse(handle_t ch, const uint8_t data[16], uint8_t out_data[16])
{
    return null_reverse_call(ch, false, DEADLINE_NEVER, data, out_data);
}

/* null_make_vmo_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t null_make_vmo_call(handle_t ch, bool idl_within, uint64_t idl_t, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    struct null_make_vmo_req idl_q;
    struct null_make_vmo_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = NULL_MAKE_VMO;
    idl_q.size = size;
    idl_q.fill = fill;
    handle_t idl_rh[1];
    uint32_t idl_got[2] = { 0, 0 };   /* bytes, handles: in a row, one copy-out */
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_got[0],
                               idl_rh, 1, &idl_got[1], idl_within, idl_t);
    uint32_t idl_rhn = idl_got[1];
    idl_n = idl_got[0];
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_vmo)
            *out_vmo = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    if (idl_st == OK && out_size_back)
        *out_size_back = idl_r.size_back;
    return idl_st;
}
/* A handle result: a new VMO of `size` bytes (1..65536) whose first
 * byte is `fill`, and its size back. size 0 or too big: ERR_INVALID_ARGS
 * and no handle. */
static inline status_t null_make_vmo_until(handle_t ch, uint64_t deadline_ns, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    return null_make_vmo_call(ch, false, deadline_ns, size, fill, out_vmo, out_size_back);
}
static inline status_t null_make_vmo_within(handle_t ch, uint64_t timeout_ns, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    return null_make_vmo_call(ch, true, timeout_ns, size, fill, out_vmo, out_size_back);
}
static inline status_t null_make_vmo(handle_t ch, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back)
{
    return null_make_vmo_call(ch, false, DEADLINE_NEVER, size, fill, out_vmo, out_size_back);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* null_ping without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then null_ping_result. */
static inline status_t null_ping_send(handle_t ch, uint32_t idl_txid, uint64_t value)
{
    struct null_ping_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NULL_PING;
    idl_q.value = value;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to null_ping_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t null_ping_result(const void *idl_rep, struct idl_msg *idl_m, uint64_t *out_value)
{
    const struct null_ping_rep *idl_r = (const struct null_ping_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_value)
        *out_value = idl_r->value;
    return OK;
}

/* null_add without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then null_add_result. */
static inline status_t null_add_send(handle_t ch, uint32_t idl_txid, uint32_t a, uint32_t b)
{
    struct null_add_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NULL_ADD;
    idl_q.a = a;
    idl_q.b = b;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to null_add_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t null_add_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_sum)
{
    const struct null_add_rep *idl_r = (const struct null_add_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_sum)
        *out_sum = idl_r->sum;
    return OK;
}

/* null_reverse without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then null_reverse_result. */
static inline status_t null_reverse_send(handle_t ch, uint32_t idl_txid, const uint8_t data[16])
{
    struct null_reverse_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NULL_REVERSE;
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_q.data[idl_i] = data[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to null_reverse_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t null_reverse_result(const void *idl_rep, struct idl_msg *idl_m, uint8_t out_data[16])
{
    const struct null_reverse_rep *idl_r = (const struct null_reverse_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    for (uint32_t idl_i = 0; out_data && idl_i < 16; idl_i++)
        out_data[idl_i] = idl_r->data[idl_i];
    return OK;
}

/* null_make_vmo without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then null_make_vmo_result. */
static inline status_t null_make_vmo_send(handle_t ch, uint32_t idl_txid, uint32_t size, uint8_t fill)
{
    struct null_make_vmo_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = NULL_MAKE_VMO;
    idl_q.size = size;
    idl_q.fill = fill;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to null_make_vmo_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t null_make_vmo_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_vmo, uint64_t *out_size_back)
{
    const struct null_make_vmo_rep *idl_r = (const struct null_make_vmo_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_vmo)
        *out_vmo = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    if (out_size_back)
        *out_size_back = idl_r->size_back;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with null_reply_<method> (now, or later from anywhere). */
struct null_ops {
    status_t (*ping)(void *ctx, uint64_t value, uint64_t *out_value);
    status_t (*add)(void *ctx, uint32_t a, uint32_t b, uint32_t *out_sum);
    status_t (*reverse)(void *ctx, const uint8_t data[16], uint8_t out_data[16]);
    status_t (*make_vmo)(void *ctx, uint32_t size, uint8_t fill, handle_t *out_vmo, uint64_t *out_size_back);
};

/* Answer the null.ping request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t null_reply_ping(struct idl_txn idl_txn, status_t idl_st, uint64_t value)
{
    struct null_ping_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.value = value;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the null.add request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t null_reply_add(struct idl_txn idl_txn, status_t idl_st, uint32_t sum)
{
    struct null_add_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.sum = sum;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the null.reverse request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t null_reply_reverse(struct idl_txn idl_txn, status_t idl_st, const uint8_t data[16])
{
    struct null_reverse_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
        idl_r.data[idl_i] = data[idl_i];
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the null.make_vmo request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t null_reply_make_vmo(struct idl_txn idl_txn, status_t idl_st, handle_t vmo, uint64_t size_back)
{
    struct null_make_vmo_rep idl_r;
    handle_t idl_hs[1] = { vmo };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(vmo != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    idl_r.size_back = size_back;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (NULL_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t null_dispatch_on(handle_t ch, const struct null_ops *ops, void *ctx,
                                        const void *req, uint32_t n, void *rep, handle_t *rhs,
                                        uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case NULL_PING: {
        const struct null_ping_req *idl_q = (const struct null_ping_req *)req;
        struct null_ping_rep *idl_r = (struct null_ping_rep *)rep;
        uint64_t out_value = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->ping) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->ping(ctx, idl_q->value, &out_value);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->value = out_value;
        return sizeof(*idl_r);
    }
    case NULL_ADD: {
        const struct null_add_req *idl_q = (const struct null_add_req *)req;
        struct null_add_rep *idl_r = (struct null_add_rep *)rep;
        uint32_t out_sum = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->add) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->add(ctx, idl_q->a, idl_q->b, &out_sum);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->sum = out_sum;
        return sizeof(*idl_r);
    }
    case NULL_REVERSE: {
        const struct null_reverse_req *idl_q = (const struct null_reverse_req *)req;
        struct null_reverse_rep *idl_r = (struct null_reverse_rep *)rep;
        uint8_t out_data[16];
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            out_data[idl_i] = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->reverse) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->reverse(ctx, idl_q->data, out_data);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        for (uint32_t idl_i = 0; idl_i < 16; idl_i++)
            idl_r->data[idl_i] = out_data[idl_i];
        return sizeof(*idl_r);
    }
    case NULL_MAKE_VMO: {
        const struct null_make_vmo_req *idl_q = (const struct null_make_vmo_req *)req;
        struct null_make_vmo_rep *idl_r = (struct null_make_vmo_rep *)rep;
        handle_t out_vmo = HANDLE_INVALID;
        uint64_t out_size_back = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->make_vmo) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->make_vmo(ctx, idl_q->size, idl_q->fill, &out_vmo, &out_size_back);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_vmo != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_vmo != HANDLE_INVALID)
                drv_handle_close(out_vmo);
            return sizeof(*idl_h);
        }
        rhs[0] = out_vmo;
        *rhn = 1;
        idl_r->size_back = out_size_back;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* null_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t null_dispatch(const struct null_ops *ops, void *ctx, const void *req, uint32_t n,
                                     void *rep, handle_t *rhs, uint32_t *rhn)
{
    return null_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take the next message on ch into slot (idl_take), a slot with room for
 * the protocol's biggest request (ERR_INVALID_ARGS if it has less). The
 * reply waiting in *rep (NULL or empty: none) goes out first in the same
 * system call (idl_take_after). It never waits: ERR_SHOULD_WAIT when
 * nothing is queued. */
static inline status_t null_take_slot(handle_t ch, const struct idl_slot *slot,
                                      struct idl_reply *rep)
{
    if (slot->qcap < NULL_REQ_MAX)
        return ERR_INVALID_ARGS;
    if (rep && rep->ch != HANDLE_INVALID)
        return idl_take_after(ch, slot, rep);
    return idl_take(ch, slot);
}

/* Run the request in slot (taken by null_take_slot, or found there by a
 * successor), which came on ch: as null_dispatch_on, its reply built
 * in slot->r and the handles that reply carries put into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). A request that carried handles is
 * answered ERR_INVALID_ARGS without its handler seeing it. Returns the
 * reply's length: 0 means no reply (no txid, or a `later` handler
 * answers it itself). No I/O; the caller sends the reply with the handles,
 * or closes them if it can't. */
static inline uint32_t null_run_slot(handle_t ch, const struct idl_slot *slot,
                                     const struct null_ops *ops, void *ctx, handle_t *rhs, uint32_t *rhn)
{
    *rhn = 0;
    if (*slot->n >= sizeof(uint32_t) && *slot->nh)
        return idl_refuse(slot);
    return null_dispatch_on(ch, ops, ctx, slot->q, *slot->n, slot->r, rhs, rhn);
}

/* Is the method with this wire ordinal idempotent (its keyword in the
 * .idl): run again on the state its first run left, it gives the same
 * result and the same answer? A server that keeps nothing across a
 * restart may run such a request again; any other it answers with an
 * error. */
static inline bool null_idempotent(uint32_t ordinal)
{
    (void)ordinal;
    return false;   /* no method is marked */
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t null_serve_one(handle_t ch, const struct null_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[NULL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[NULL_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = null_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t null_serve(handle_t ch, const struct null_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[NULL_REQ_MAX];
    _Alignas(8) uint8_t idl_r[NULL_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = null_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
