/* Generated by tools/genidl.py from abi/idl/serve.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `serve` (id 31). Client: serve_<method>(ch, args..., &results...)
 * (and serve_<method>_until with a deadline, _within with a timeout), or
 * serve_<method>_send and serve_<method>_result without waiting. Server:
 * fill a struct serve_ops and run serve_serve(ch, &ops, ctx), or
 * serve_serve_one / serve_dispatch_on for a loop of your own;
 * serve_reply_<method> answers a request later. */
#pragma once

#include <idl/common.h>

#define SERVE_PROTOCOL_ID 31u
#define SERVE_SHARE            0x001f0001u
#define SERVE_INFO             0x001f0002u
#define SERVE_STOP             0x001f0003u

/* Messages (packed: no padding bytes ever cross the channel). */
struct serve_share_req {
    uint32_t txid;
    uint32_t ordinal;
    uint16_t port;
    uint8_t name[128];
} __attribute__((packed));
struct serve_share_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));
struct serve_info_req {
    uint32_t txid;
    uint32_t ordinal;
    uint32_t index;
} __attribute__((packed));
struct serve_info_rep {
    uint32_t txid;
    int32_t  status;
    uint16_t port;
    uint8_t name[128];
    uint64_t size;
    uint32_t clients;
    uint64_t requests;
    uint64_t bytes;
} __attribute__((packed));
struct serve_stop_req {
    uint32_t txid;
    uint32_t ordinal;
    uint16_t port;
} __attribute__((packed));
struct serve_stop_rep {
    uint32_t txid;
    int32_t  status;
    uint32_t stopped;
} __attribute__((packed));

#define SERVE_REQ_MAX 138u   /* bytes: the biggest request */
#define SERVE_REP_MAX 166u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* serve_share_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t serve_share_call(handle_t ch, bool idl_within, uint64_t idl_t, uint16_t port, const uint8_t name[128], handle_t *out_give)
{
    struct serve_share_req idl_q;
    struct serve_share_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = SERVE_SHARE;
    idl_q.port = port;
    for (uint32_t idl_i = 0; idl_i < 128; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, idl_rh,
                               1, &idl_rhn, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_give)
            *out_give = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    return idl_st;
}
/* Serve a file on `port` (SERVE_PORT_MIN and up: any port, the server has
 * the permission for those below 1024 too). `name` is the file's path
 * as the owner gave it (NUL-terminated): for `info`, the log and the
 * Content-Type, never opened by the server. Answers at once with a channel
 * `give`: the caller writes one message on it, struct serve_give with the
 * file's two handles (file_give: its `file` channel, open to read, and its
 * transfer buffer), and then reads one answer there, struct serve_answer:
 * OK once the server listens (it serves that file and nothing else, to
 * every path asked), else why not (ERR_ACCESS_DENIED: the server has no
 * listen permission; ERR_ALREADY_BOUND: another program has the port;
 * ERR_BAD_STATE: no network address yet (it waits 5 s for one);
 * netstack's other errors; ERR_INVALID_ARGS: a wrong message). The server
 * closes `give` after its answer, or if nothing comes on it in
 * SERVE_GIVE_WAIT. ERR_NO_RESOURCES: SERVE_SHARES files served (or
 * waiting for their file) already; ERR_ALREADY_EXISTS: that port is served
 * already; ERR_OUT_OF_RANGE: a port below SERVE_PORT_MIN; ERR_INVALID_ARGS:
 * no name. */
static inline status_t serve_share_until(handle_t ch, uint64_t deadline_ns, uint16_t port, const uint8_t name[128], handle_t *out_give)
{
    return serve_share_call(ch, false, deadline_ns, port, name, out_give);
}
static inline status_t serve_share_within(handle_t ch, uint64_t timeout_ns, uint16_t port, const uint8_t name[128], handle_t *out_give)
{
    return serve_share_call(ch, true, timeout_ns, port, name, out_give);
}
static inline status_t serve_share(handle_t ch, uint16_t port, const uint8_t name[128], handle_t *out_give)
{
    return serve_share_call(ch, false, DEADLINE_NEVER, port, name, out_give);
}

/* serve_info_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t serve_info_call(handle_t ch, bool idl_within, uint64_t idl_t, uint32_t index, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes)
{
    struct serve_info_req idl_q;
    struct serve_info_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = SERVE_INFO;
    idl_q.index = index;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_port)
        *out_port = idl_r.port;
    for (uint32_t idl_i = 0; idl_st == OK && out_name && idl_i < 128; idl_i++)
        out_name[idl_i] = idl_r.name[idl_i];
    if (idl_st == OK && out_size)
        *out_size = idl_r.size;
    if (idl_st == OK && out_clients)
        *out_clients = idl_r.clients;
    if (idl_st == OK && out_requests)
        *out_requests = idl_r.requests;
    if (idl_st == OK && out_bytes)
        *out_bytes = idl_r.bytes;
    return idl_st;
}
/* What is served: the `index`-th file (0, 1, ...): its port, its name as
 * `share` was given it, its size, the clients connected now, and the
 * requests answered and file bytes sent since it was shared.
 * ERR_NOT_FOUND: past the last. */
static inline status_t serve_info_until(handle_t ch, uint64_t deadline_ns, uint32_t index, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes)
{
    return serve_info_call(ch, false, deadline_ns, index, out_port, out_name, out_size, out_clients, out_requests, out_bytes);
}
static inline status_t serve_info_within(handle_t ch, uint64_t timeout_ns, uint32_t index, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes)
{
    return serve_info_call(ch, true, timeout_ns, index, out_port, out_name, out_size, out_clients, out_requests, out_bytes);
}
static inline status_t serve_info(handle_t ch, uint32_t index, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes)
{
    return serve_info_call(ch, false, DEADLINE_NEVER, index, out_port, out_name, out_size, out_clients, out_requests, out_bytes);
}

/* serve_stop_until and _within: idl_t is a deadline, or with idl_within a
 * timeout from when the call starts (the kernel's clock). */
static inline status_t serve_stop_call(handle_t ch, bool idl_within, uint64_t idl_t, uint16_t port, uint32_t *out_stopped)
{
    struct serve_stop_req idl_q;
    struct serve_stop_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = SERVE_STOP;
    idl_q.port = port;
    status_t idl_st = idl_call(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n, NULL, 0,
                               NULL, idl_within, idl_t);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && out_stopped)
        *out_stopped = idl_r.stopped;
    return idl_st;
}
/* Stop serving the file on `port` (0: every file): its listener closed and
 * its clients cut off. Answers how many stopped (0: none was served there). */
static inline status_t serve_stop_until(handle_t ch, uint64_t deadline_ns, uint16_t port, uint32_t *out_stopped)
{
    return serve_stop_call(ch, false, deadline_ns, port, out_stopped);
}
static inline status_t serve_stop_within(handle_t ch, uint64_t timeout_ns, uint16_t port, uint32_t *out_stopped)
{
    return serve_stop_call(ch, true, timeout_ns, port, out_stopped);
}
static inline status_t serve_stop(handle_t ch, uint16_t port, uint32_t *out_stopped)
{
    return serve_stop_call(ch, false, DEADLINE_NEVER, port, out_stopped);
}

/* ---- client, asynchronous (tools/genidl.py) --------------------------- */

/* serve_share without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then serve_share_result. */
static inline status_t serve_share_send(handle_t ch, uint32_t idl_txid, uint16_t port, const uint8_t name[128])
{
    struct serve_share_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = SERVE_SHARE;
    idl_q.port = port;
    for (uint32_t idl_i = 0; idl_i < 128; idl_i++)
        idl_q.name[idl_i] = name[idl_i];
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to serve_share_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t serve_share_result(const void *idl_rep, struct idl_msg *idl_m, handle_t *out_give)
{
    const struct serve_share_rep *idl_r = (const struct serve_share_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    if (out_give)
        *out_give = idl_m->hs[0];
    else
        drv_handle_close(idl_m->hs[0]);
    idl_m->nh = 0;
    return OK;
}

/* serve_info without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then serve_info_result. */
static inline status_t serve_info_send(handle_t ch, uint32_t idl_txid, uint32_t index)
{
    struct serve_info_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = SERVE_INFO;
    idl_q.index = index;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to serve_info_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t serve_info_result(const void *idl_rep, struct idl_msg *idl_m, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes)
{
    const struct serve_info_rep *idl_r = (const struct serve_info_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_port)
        *out_port = idl_r->port;
    for (uint32_t idl_i = 0; out_name && idl_i < 128; idl_i++)
        out_name[idl_i] = idl_r->name[idl_i];
    if (out_size)
        *out_size = idl_r->size;
    if (out_clients)
        *out_clients = idl_r->clients;
    if (out_requests)
        *out_requests = idl_r->requests;
    if (out_bytes)
        *out_bytes = idl_r->bytes;
    return OK;
}

/* serve_stop without waiting: the request, with the caller's txid (not 0).
 * The reply comes on ch: idl_reply_read, then serve_stop_result. */
static inline status_t serve_stop_send(handle_t ch, uint32_t idl_txid, uint16_t port)
{
    struct serve_stop_req idl_q;
    if (!idl_txid)
        return ERR_INVALID_ARGS;
    idl_q.txid = idl_txid;
    idl_q.ordinal = SERVE_STOP;
    idl_q.port = port;
    return drv_channel_write(ch, &idl_q, sizeof(idl_q), NULL, 0);
}

/* The status and results of a reply to serve_stop_send (read with
 * idl_reply_read). The reply's handles are taken in every case: moved to
 * the results, or closed (on a failure, or for a NULL result). */
static inline status_t serve_stop_result(const void *idl_rep, struct idl_msg *idl_m, uint32_t *out_stopped)
{
    const struct serve_stop_rep *idl_r = (const struct serve_stop_rep *)idl_rep;
    status_t idl_st = idl_rep_status(idl_rep, idl_m->n, sizeof(*idl_r));
    if (idl_st == OK && idl_m->nh != 0)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK) {
        idl_msg_drop(idl_m);
        return idl_st;
    }
    idl_m->nh = 0;
    if (out_stopped)
        *out_stopped = idl_r->stopped;
    return OK;
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. A `later` method's handler
 * also gets the request's txn, and may return IDL_LATER and answer it
 * with serve_reply_<method> (now, or later from anywhere). */
struct serve_ops {
    status_t (*share)(void *ctx, uint16_t port, const uint8_t name[128], handle_t *out_give);
    status_t (*info)(void *ctx, uint32_t index, uint16_t *out_port, uint8_t out_name[128], uint64_t *out_size, uint32_t *out_clients, uint64_t *out_requests, uint64_t *out_bytes);
    status_t (*stop)(void *ctx, uint16_t port, uint32_t *out_stopped);
};

/* Answer the serve.share request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t serve_reply_share(struct idl_txn idl_txn, status_t idl_st, handle_t give)
{
    struct serve_share_rep idl_r;
    handle_t idl_hs[1] = { give };
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    if (idl_st == OK && !(give != HANDLE_INVALID))
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK) {
        if (idl_hs[0] != HANDLE_INVALID)
            drv_handle_close(idl_hs[0]);
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    }
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), idl_hs, 1);
}

/* Answer the serve.info request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t serve_reply_info(struct idl_txn idl_txn, status_t idl_st, uint16_t port, const uint8_t name[128], uint64_t size, uint32_t clients, uint64_t requests, uint64_t bytes)
{
    struct serve_info_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.port = port;
    for (uint32_t idl_i = 0; idl_i < 128; idl_i++)
        idl_r.name[idl_i] = name[idl_i];
    idl_r.size = size;
    idl_r.clients = clients;
    idl_r.requests = requests;
    idl_r.bytes = bytes;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Answer the serve.stop request kept in txn: idl_st and, if it is OK, the
 * results (handles are moved in every case: sent, or closed). A positive
 * status is ERR_INTERNAL, and so is OK with a handle result left
 * HANDLE_INVALID. Returns the write's status (idl_reply_write). */
static inline status_t serve_reply_stop(struct idl_txn idl_txn, status_t idl_st, uint32_t stopped)
{
    struct serve_stop_rep idl_r;
    if (idl_st > 0)
        idl_st = ERR_INTERNAL;
    idl_r.status = idl_st;
    if (idl_st != OK)
        return idl_reply_write(idl_txn, &idl_r, sizeof(struct idl_rep_hdr), NULL, 0);
    idl_r.stopped = stopped;
    return idl_reply_write(idl_txn, &idl_r, sizeof(idl_r), NULL, 0);
}

/* Decode the request of n bytes at req, which came on ch, call its handler,
 * encode the reply into rep (SERVE_REP_MAX bytes) and the handles it carries
 * into rhs (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's
 * length: 0 means no reply (the request has no txid, or a `later`
 * handler answers it itself). No I/O; the caller sends the reply with the
 * handles, or closes them if it can't. */
static inline uint32_t serve_dispatch_on(handle_t ch, const struct serve_ops *ops, void *ctx,
                                         const void *req, uint32_t n, void *rep, handle_t *rhs,
                                         uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    (void)ch;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case SERVE_SHARE: {
        const struct serve_share_req *idl_q = (const struct serve_share_req *)req;
        struct serve_share_rep *idl_r = (struct serve_share_rep *)rep;
        handle_t out_give = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->share) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->share(ctx, idl_q->port, idl_q->name, &out_give);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_give != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_give != HANDLE_INVALID)
                drv_handle_close(out_give);
            return sizeof(*idl_h);
        }
        rhs[0] = out_give;
        *rhn = 1;
        return sizeof(*idl_r);
    }
    case SERVE_INFO: {
        const struct serve_info_req *idl_q = (const struct serve_info_req *)req;
        struct serve_info_rep *idl_r = (struct serve_info_rep *)rep;
        uint16_t out_port = 0;
        uint8_t out_name[128];
        for (uint32_t idl_i = 0; idl_i < 128; idl_i++)
            out_name[idl_i] = 0;
        uint64_t out_size = 0;
        uint32_t out_clients = 0;
        uint64_t out_requests = 0;
        uint64_t out_bytes = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->info) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->info(ctx, idl_q->index, &out_port, out_name, &out_size, &out_clients, &out_requests, &out_bytes);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->port = out_port;
        for (uint32_t idl_i = 0; idl_i < 128; idl_i++)
            idl_r->name[idl_i] = out_name[idl_i];
        idl_r->size = out_size;
        idl_r->clients = out_clients;
        idl_r->requests = out_requests;
        idl_r->bytes = out_bytes;
        return sizeof(*idl_r);
    }
    case SERVE_STOP: {
        const struct serve_stop_req *idl_q = (const struct serve_stop_req *)req;
        struct serve_stop_rep *idl_r = (struct serve_stop_rep *)rep;
        uint32_t out_stopped = 0;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->stop) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->stop(ctx, idl_q->port, &out_stopped);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status != OK)
            return sizeof(*idl_h);
        idl_r->stopped = out_stopped;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* serve_dispatch_on without the channel (the protocol has no `later` method). */
static inline uint32_t serve_dispatch(const struct serve_ops *ops, void *ctx, const void *req, uint32_t n,
                                      void *rep, handle_t *rhs, uint32_t *rhn)
{
    return serve_dispatch_on(HANDLE_INVALID, ops, ctx, req, n, rep, rhs, rhn);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t serve_serve_one(handle_t ch, const struct serve_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[SERVE_REQ_MAX];
    _Alignas(8) uint8_t idl_r[SERVE_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = serve_dispatch_on(ch, ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). Each reply
 * goes out in the system call that takes the next request
 * (idl_serve_next). */
static inline status_t serve_serve(handle_t ch, const struct serve_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[SERVE_REQ_MAX];
    _Alignas(8) uint8_t idl_r[SERVE_REP_MAX];
    handle_t idl_rhs[IDL_REP_HANDLES];
    struct idl_serve idl_s = {
        .ch = ch, .q = idl_q, .qcap = sizeof(idl_q), .r = idl_r, .rhs = idl_rhs,
    };
    for (;;) {
        status_t idl_st = idl_serve_next(&idl_s);
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != OK)
            return idl_st;
        idl_s.rn = serve_dispatch_on(ch, ops, ctx, idl_q, idl_s.n, idl_r, idl_rhs, &idl_s.rhn);
    }
}
