/* Generated by tools/genidl.py from abi/idl/svc.idl. Do not edit:
 * change the .idl and run `make idl`.
 *
 * Protocol `svc` (id 25). Client: svc_<method>(ch, args..., &results...)
 * (and svc_<method>_until with a deadline) over drv_channel_call. Server:
 * fill a struct svc_ops and run svc_serve(ch, &ops, ctx), or
 * svc_serve_one / svc_dispatch for a loop of your own. */
#pragma once

#include <idl/common.h>

#define SVC_PROTOCOL_ID 25u
#define SVC_CONNECT          0x00190001u

/* Messages (packed: no padding bytes ever cross the channel). */
struct svc_connect_req {
    uint32_t txid;
    uint32_t ordinal;
} __attribute__((packed));
struct svc_connect_rep {
    uint32_t txid;
    int32_t  status;
} __attribute__((packed));

#define SVC_REQ_MAX 8u   /* bytes: the biggest request */
#define SVC_REP_MAX 8u   /* bytes: the biggest reply */

/* ---- client ---------------------------------------------------------- */

/* A new channel to this service, for the caller alone.
 * ERR_NO_RESOURCES: the service serves as many as it can. */
static inline status_t svc_connect_until(handle_t ch, uint64_t deadline_ns, handle_t *out_channel)
{
    struct svc_connect_req idl_q;
    struct svc_connect_rep idl_r;
    uint32_t idl_n = 0;
    idl_q.txid = 0;
    idl_q.ordinal = SVC_CONNECT;
    handle_t idl_rh[1];
    uint32_t idl_rhn = 0;
    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, sizeof(idl_r), &idl_n,
                                         idl_rh, 1, &idl_rhn, deadline_ns);
    if (idl_st == OK)
        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));
    if (idl_st == OK && idl_rhn != 1)
        idl_st = ERR_INTERNAL;
    if (idl_st != OK)
        idl_close_all(idl_rh, idl_rhn);
    if (idl_st == OK) {
        if (out_channel)
            *out_channel = idl_rh[0];
        else
            drv_handle_close(idl_rh[0]);
    }
    return idl_st;
}
static inline status_t svc_connect(handle_t ch, handle_t *out_channel)
{
    return svc_connect_until(ch, DEADLINE_NEVER, out_channel);
}

/* ---- server ---------------------------------------------------------- */

/* Handlers: return OK and fill the results, or an ERR_* for the client.
 * A NULL handler answers ERR_NOT_SUPPORTED. */
struct svc_ops {
    status_t (*connect)(void *ctx, handle_t *out_channel);
};

/* Decode the request of n bytes at req, call its handler, encode the reply
 * into rep (SVC_REP_MAX bytes) and the handles it carries into rhs
 * (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's length: 0
 * means no reply (the request has no txid). No I/O; the caller sends the
 * reply with the handles, or closes them if it can't. */
static inline uint32_t svc_dispatch(const struct svc_ops *ops, void *ctx, const void *req, uint32_t n,
                                    void *rep, handle_t *rhs, uint32_t *rhn)
{
    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;
    *rhn = 0;
    (void)rhs;
    if (n < sizeof(uint32_t))
        return 0;
    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;
    idl_h->status = ERR_INVALID_ARGS;
    if (n < sizeof(struct idl_req_hdr))
        return sizeof(*idl_h);
    switch (((const struct idl_req_hdr *)req)->ordinal) {
    case SVC_CONNECT: {
        const struct svc_connect_req *idl_q = (const struct svc_connect_req *)req;
        struct svc_connect_rep *idl_r = (struct svc_connect_rep *)rep;
        handle_t out_channel = HANDLE_INVALID;
        if (n != sizeof(*idl_q))
            return sizeof(*idl_h);
        if (!ops->connect) {
            idl_h->status = ERR_NOT_SUPPORTED;
            return sizeof(*idl_h);
        }
        status_t idl_st = ops->connect(ctx, &out_channel);
        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;
        if (idl_h->status == OK && !(out_channel != HANDLE_INVALID))
            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */
        if (idl_h->status != OK) {
            if (out_channel != HANDLE_INVALID)
                drv_handle_close(out_channel);
            return sizeof(*idl_h);
        }
        rhs[0] = out_channel;
        *rhn = 1;
        return sizeof(*idl_r);
    }
    }
    idl_h->status = ERR_NOT_SUPPORTED;
    return sizeof(*idl_h);
}

/* Take one message off ch and answer it. OK once a message was handled
 * (its reply may still have been dropped: the client is gone, or never
 * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when
 * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */
static inline status_t svc_serve_one(handle_t ch, const struct svc_ops *ops, void *ctx)
{
    _Alignas(8) uint8_t idl_q[SVC_REQ_MAX];
    _Alignas(8) uint8_t idl_r[SVC_REP_MAX];
    handle_t idl_hs[IDL_READ_HANDLES];
    uint32_t idl_n = 0, idl_nh = 0;
    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, IDL_READ_HANDLES,
                                       &idl_nh);
    if (idl_st == ERR_BUFFER_TOO_SMALL)
        return idl_drain(ch, idl_n, idl_nh);
    if (idl_st != OK)
        return idl_st;
    if (idl_nh) {
        idl_close_all(idl_hs, idl_nh);
        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);
        return OK;
    }
    handle_t idl_rhs[IDL_REP_HANDLES];
    uint32_t idl_rhn = 0;
    uint32_t idl_rn = svc_dispatch(ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);
    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)
        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */
    return OK;
}

/* Serve ch until the client closes it (OK), or a wait or read fails
 * (that status: ERR_CANCELED when the driver is being killed). */
static inline status_t svc_serve(handle_t ch, const struct svc_ops *ops, void *ctx)
{
    for (;;) {
        status_t idl_st = svc_serve_one(ch, ops, ctx);
        if (idl_st == OK)
            continue;
        if (idl_st == ERR_PEER_CLOSED)
            return OK;
        if (idl_st != ERR_SHOULD_WAIT)
            return idl_st;
        signals_t idl_seen = 0;
        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,
                                     &idl_seen);
        if (idl_st != OK)
            return idl_st;
    }
}
