/* Generated by tools/genwl.py from abi/wayland/jam-window-memory-v1.xml. Do not edit:
 * change the XML or the generator and run `make wl`.
 *
 * Protocol `jam_window_memory_v1`'s tables: per interface its name, upstream's
 * version and messages; per message its name, signature and argument
 * interfaces (<jwl.h> says how libjwl's codec reads them). */
#include <stddef.h>

#include <jwl.h>
#include <jwl/jam_window_memory_v1.h>

/* For the messages with no object or new_id argument. */
static const struct jwl_interface *const no_types[3] = { NULL };

/* jam_window_memory_v1 */
static const struct jwl_interface *const types_jam_window_memory_v1_identify[] = {
    &jwl_xdg_toplevel_interface,
    NULL,
    NULL,
};
static const struct jwl_message requests_jam_window_memory_v1[] = {
    { .name = "destroy", .signature = "", .types = no_types },
    { .name = "identify", .signature = "ouu", .types = types_jam_window_memory_v1_identify },
};
static const struct jwl_interface *const types_jam_window_memory_v1_key[] = {
    &jwl_xdg_toplevel_interface,
    NULL,
    NULL,
};
static const struct jwl_message events_jam_window_memory_v1[] = {
    { .name = "key", .signature = "?ouu", .types = types_jam_window_memory_v1_key },
};
const struct jwl_interface jwl_jam_window_memory_v1_interface = {
    .name = "jam_window_memory_v1",
    .version = 1,
    .nrequests = 2,
    .nevents = 1,
    .requests = requests_jam_window_memory_v1,
    .events = events_jam_window_memory_v1,
    .request_destructors = JWL_JAM_WINDOW_MEMORY_V1_REQ_DESTRUCTORS,
    .event_destructors = JWL_JAM_WINDOW_MEMORY_V1_EV_DESTRUCTORS,
};
