/* Generated by tools/genwl.py from third_party/wayland-protocols/cursor-shape-v1.xml. Do not
 * edit:
 * change the XML or the generator and run `make wl`.
 *
 * Protocol `cursor_shape_v1`'s tables: per interface its name, upstream's
 * version and messages; per message its name, signature and argument
 * interfaces (<jwl.h> says how libjwl's codec reads them).
 *
 * Upstream's copyright and licence (the XML's own, kept here as its
 * licence asks):
 *
 * Copyright 2018 The Chromium Authors
 * Copyright 2023 Simon Ser
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. */
#include <stddef.h>

#include <jwl.h>
#include <jwl/cursor_shape_v1.h>

/* For the messages with no object or new_id argument. */
static const struct jwl_interface *const no_types[2] = { NULL };

/* wp_cursor_shape_manager_v1 */
static const struct jwl_interface *const types_wp_cursor_shape_manager_v1_get_pointer[] = {
    &jwl_wp_cursor_shape_device_v1_interface,
    &jwl_wl_pointer_interface,
};
static const struct jwl_interface *const types_wp_cursor_shape_manager_v1_get_tablet_tool_v2[] = {
    &jwl_wp_cursor_shape_device_v1_interface,
    NULL,
};
static const struct jwl_message requests_wp_cursor_shape_manager_v1[] = {
    { .name = "destroy", .signature = "", .types = no_types },
    { .name = "get_pointer", .signature = "no",
      .types = types_wp_cursor_shape_manager_v1_get_pointer },
    { .name = "get_tablet_tool_v2", .signature = "no",
      .types = types_wp_cursor_shape_manager_v1_get_tablet_tool_v2 },
};
const struct jwl_interface jwl_wp_cursor_shape_manager_v1_interface = {
    .name = "wp_cursor_shape_manager_v1",
    .version = 2,
    .nrequests = 3,
    .nevents = 0,
    .requests = requests_wp_cursor_shape_manager_v1,
    .events = NULL,
    .request_destructors = JWL_WP_CURSOR_SHAPE_MANAGER_V1_REQ_DESTRUCTORS,
    .event_destructors = 0,
};

/* wp_cursor_shape_device_v1 */
static const struct jwl_message requests_wp_cursor_shape_device_v1[] = {
    { .name = "destroy", .signature = "", .types = no_types },
    { .name = "set_shape", .signature = "uu", .types = no_types },
};
const struct jwl_interface jwl_wp_cursor_shape_device_v1_interface = {
    .name = "wp_cursor_shape_device_v1",
    .version = 2,
    .nrequests = 2,
    .nevents = 0,
    .requests = requests_wp_cursor_shape_device_v1,
    .events = NULL,
    .request_destructors = JWL_WP_CURSOR_SHAPE_DEVICE_V1_REQ_DESTRUCTORS,
    .event_destructors = 0,
};
