#!/usr/bin/env python3
"""Convert an 8x16 BDF font into a C glyph table (ASCII 0x20-0x7E, '?' for the rest)."""
import sys

src, dst = sys.argv[1], sys.argv[2]
glyphs, enc, rows, in_bitmap = {}, None, [], False
for line in open(src, encoding="latin-1"):
    line = line.strip()
    if line.startswith("ENCODING "):
        enc = int(line.split()[1])
    elif line.startswith("BBX "):
        w, h = int(line.split()[1]), int(line.split()[2])
        if (w, h) != (8, 16):
            sys.exit(f"glyph {enc}: expected 8x16 BBX, got {w}x{h}")
    elif line == "BITMAP":
        in_bitmap, rows = True, []
    elif line == "ENDCHAR":
        in_bitmap = False
        if enc is not None and enc < 128:
            glyphs[enc] = [int(r, 16) for r in rows]
    elif in_bitmap:
        rows.append(line)

with open(dst, "w") as out:
    out.write("/* Generated by tools/bdf2c.py from third_party/spleen/spleen-8x16.bdf.\n")
    out.write(" * Spleen is (c) Frederic Cambus, BSD 2-Clause; see third_party/spleen/LICENSE. */\n")
    out.write("#include <stdint.h>\n\nconst uint8_t font_8x16[128][16] = {\n")
    for c in range(128):
        g = glyphs.get(c) or glyphs[ord("?")]
        out.write("    [%d] = {%s},\n" % (c, ", ".join("0x%02x" % b for b in g)))
    out.write("};\n")
