#!/usr/bin/env python3
"""Convert an 8x16 BDF font into a C glyph table.

    bdf2c.py <font.bdf> <out.c>            ASCII 0x20-0x7E ('?' for the rest):
                                           font_8x16[128][16], the console's
    bdf2c.py <font.bdf> <out.c> --latin    U+00A0-U+017F (Latin-1 Supplement and
                                           Latin Extended-A): font_latin[224][16],
                                           libfun's text for names like JAY-Z with
                                           a diaeresis (a glyph the font lacks: '?')
"""
import sys

src, dst = sys.argv[1], sys.argv[2]
latin = len(sys.argv) > 3 and sys.argv[3] == "--latin"
FIRST, COUNT = (0xA0, 224) if latin else (0, 128)
glyphs, enc, rows, in_bitmap = {}, None, [], False
for line in open(src, encoding="latin-1"):
    line = line.strip()
    if line.startswith("ENCODING "):
        enc = int(line.split()[1])
    elif line.startswith("BBX "):
        w, h = int(line.split()[1]), int(line.split()[2])
        if (w, h) != (8, 16):
            sys.exit(f"glyph {enc}: expected 8x16 BBX, got {w}x{h}")
    elif line == "BITMAP":
        in_bitmap, rows = True, []
    elif line == "ENDCHAR":
        in_bitmap = False
        if enc is not None and (enc < 128 or FIRST <= enc < FIRST + COUNT):
            glyphs[enc] = [int(r, 16) for r in rows]
    elif in_bitmap:
        rows.append(line)

name = "font_latin" if latin else "font_8x16"
with open(dst, "w") as out:
    out.write("/* Generated by tools/bdf2c.py from third_party/spleen/spleen-8x16.bdf.\n")
    out.write(" * Spleen is (c) Frederic Cambus, BSD 2-Clause; see third_party/spleen/LICENSE. */\n")
    if latin:
        out.write("/* U+00A0 .. U+017F: entry i is the code point 0xA0 + i. */\n")
    out.write("#include <stdint.h>\n\nconst uint8_t %s[%d][16] = {\n" % (name, COUNT))
    for c in range(FIRST, FIRST + COUNT):
        g = glyphs.get(c) or glyphs[ord("?")]
        out.write("    [%d] = {%s},\n" % (c - FIRST, ", ".join("0x%02x" % b for b in g)))
    out.write("};\n")
