#!/usr/bin/env python3
"""The driver build check (M6, ARCHITECTURE.md "The migration rule").

    checkdriver.py <nm> <driver> <object> -- <header>...
    checkdriver.py table <out.c> <driver>...

The second form writes the kernel's table of built-in drivers (struct
kdriver kdrivers[], <jam/driver_kernel.h>), only if it changed.

The first form fails (exit 1, naming every offender) if the driver's object uses a symbol
it may not. A driver is compiled with nothing but <jam/driver.h>,
<jam/abi.h>, <jam/status.h>, the generated <idl/*.h> and the compiler's
freestanding headers on its include path (-nostdinc), so a kernel header
can't even be included; this check closes the other door: declaring a
kernel function yourself (`void *kmalloc(size_t);`) and calling it, or
calling into another driver. The Makefile links each driver's objects into
one relocatable object first (`ld -r`), so references between the
driver's own files are resolved and only what it needs from outside is
left undefined.

Allowed undefined symbols:
  - every function declared (not defined) in the given headers: driver.h's
    drv_* and driver_main, status.h's status_str; parsed from the headers,
    so the list can't drift from the surface;
  - memcpy, memmove, memset, memcmp: GCC may emit calls to these for
    struct copies, initialisers and loops even with -ffreestanding
    -fno-builtin (they are the freestanding environment's contract), and
    both builds provide them. No allowed header declares them, and an
    implicit declaration is an error, so a driver can't call them by name
    by accident.
Nothing else: no libgcc helpers (the kernel doesn't link libgcc), no
__stack_chk_fail (drivers build with -fno-stack-protector).

A driver also may not define a function of that surface itself (it would
shadow the real one in the process build)."""
import re
import subprocess
import sys

COMPILER_HELPERS = {"memcpy", "memmove", "memset", "memcmp"}

# Sections a driver object may have. Anything else (.ktests, __ex_table,
# .limine_requests, .init_array, ...) could be KEEP()'d into a kernel table
# by kernel/linker.ld whatever objcopy does to the symbols, and so be run or
# obeyed by the kernel outside the driver's process. (Review of M6 phase 1.)
ALLOWED_SECTION = re.compile(
    r"^(\.(text|rodata|data|bss)(\..*)?|\.debug_.*|\.comment|\.eh_frame|"
    r"\.note\.GNU-stack|\.note\.gnu\.property|\.group)$")


def declared_functions(path):
    """Names of the functions a header declares (prototypes, not inline
    definitions or macros)."""
    text = open(path).read()
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    # Drop preprocessor lines (with continuations).
    text = re.sub(r"^[ \t]*#(?:[^\n]*\\\n)*[^\n]*", " ", text, flags=re.M)
    # Drop the bodies of inline functions, structs and unions.
    while True:
        new = re.sub(r"\{[^{}]*\}", ";", text)
        if new == text:
            break
        text = new
    names = set()
    for stmt in text.split(";"):
        stmt = " ".join(stmt.split())
        if "(" not in stmt or re.match(r"(typedef|static|extern\s+inline)\b", stmt):
            continue   # types, and inline definitions (their bodies are gone)
        # The declarator's name: the identifier before the first '(' that
        # opens a parameter list (skipping __attribute__ and the like).
        m = re.match(r"^(?:[A-Za-z_][A-Za-z0-9_]*[\s\*]+)+\**\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(", stmt)
        if m and not m.group(1).startswith("__"):
            names.add(m.group(1))
    return names


def sections(nm_tool, obj):
    """Section names of obj, read with the objdump next to nm_tool."""
    tool = nm_tool[:-2] + "objdump" if nm_tool.endswith("nm") else "objdump"
    r = subprocess.run([tool, "-h", "-w", obj], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"checkdriver: {tool} -h {obj} failed:\n{r.stderr}")
    names = []
    for line in r.stdout.splitlines():
        f = line.split()
        if len(f) > 2 and f[0].isdigit():
            names.append(f[1])
    return names


def nm(tool, obj, *flags):
    r = subprocess.run([tool, *flags, obj], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"checkdriver: {tool} {' '.join(flags)} {obj} failed:\n{r.stderr}")
    return r.stdout.splitlines()


def c_name(driver):
    return re.sub(r"[^A-Za-z0-9_]", "_", driver)


def write_table(out, drivers):
    lines = ["/* Generated by tools/checkdriver.py (the Makefile's driver list): the",
             " * drivers built into the kernel. */",
             "#include <stddef.h>",
             "#include <jam/driver_kernel.h>", ""]
    lines += [f"int driver_main__{c_name(d)}(const struct driver_start *s);" for d in drivers]
    lines += ["", "const struct kdriver kdrivers[] = {"]
    lines += [f'    {{ "{d}", driver_main__{c_name(d)} }},' for d in drivers]
    lines += ["    { NULL, NULL },", "};", ""]
    text = "\n".join(lines)
    try:
        if open(out).read() == text:
            return
    except FileNotFoundError:
        pass
    open(out, "w").write(text)


def main():
    if len(sys.argv) >= 3 and sys.argv[1] == "table":
        write_table(sys.argv[2], sys.argv[3:])
        return
    if len(sys.argv) < 6 or "--" not in sys.argv:
        sys.exit(__doc__)
    sep = sys.argv.index("--")
    tool, driver, objs, headers = sys.argv[1], sys.argv[2], sys.argv[3:sep], sys.argv[sep + 1:]
    if not objs or not headers:
        sys.exit(__doc__)
    surface = set()
    for h in headers:
        surface |= declared_functions(h)
    if "drv_log" not in surface or "driver_main" not in surface:
        sys.exit(f"checkdriver: couldn't read the driver surface from {' '.join(headers)}")
    allowed = surface | COMPILER_HELPERS
    bad = []
    for obj in objs:
        for sec in sections(tool, obj):
            if not ALLOWED_SECTION.match(sec):
                bad.append(f"  {obj}: has section '{sec}' (drivers get .text/.rodata/.data/.bss only)")
        for line in nm(tool, obj, "-u"):
            sym = line.split()[-1]
            if sym not in allowed:
                bad.append(f"  {obj}: uses '{sym}', which <jam/driver.h> doesn't provide")
        for line in nm(tool, obj, "-g", "--defined-only"):
            sym = line.split()[-1]
            if sym in surface and sym != "driver_main":
                bad.append(f"  {obj}: defines '{sym}' itself (it belongs to <jam/driver.h>)")
    if bad:
        sys.exit(f"checkdriver: driver '{driver}' breaks the driver rules "
                 "(ARCHITECTURE.md, \"The migration rule\"):\n" + "\n".join(bad))


if __name__ == "__main__":
    main()
