#!/usr/bin/env python3
"""Generate protocol code from abi/idl/*.idl (M6: ARCHITECTURE.md "IPC").

    genidl.py gen     write the generated headers
    genidl.py check   exit 1 (and name them) if any is missing, stale or
                      left over from a protocol that no longer exists

Outputs, committed like the syscall glue (so they can be read and grepped):
    drivers/include/idl/common.h    what every protocol shares
    drivers/include/idl/<name>.h    one per protocol: message structs,
                                    client stubs, server dispatch

Everything is `static inline` in the headers, over <jam/driver.h>'s
drv_channel_* calls only, so the same header works in a driver (either
build: drivers see nothing but driver.h and these), in an ordinary user
program (libos implements drv_*) and in kernel code running in a kernel
process.

The language, one statement per line, `#` starts a comment (comment lines
right above a method are copied into the header):

    protocol <name> <id>
    <ordinal> <method> (<type> <arg>, ...) -> (<type> <result>, ...)

name, method, arg, result   C identifiers (lower case by convention)
id                          1..65535, unique over all protocols
ordinal                     1..65535, unique in the protocol
type                        u8 u16 u32 u64 i8 i16 i32 i64, or u8[N] (a
                            fixed-size byte array, 1 <= N <= 4096), or
                            `handle` (RESULTS only, at most 8 per method)

Either list may be empty: `()`.

Handles (M7) travel only server -> client, in replies: the server's
handler fills `handle_t *out_x` and the reply moves the handles to the
client (drv_channel_call_h reserves their slots before the request goes
out, so a full handle table fails the call up front). A reply with the
wrong number of handles is ERR_INTERNAL and whatever arrived is closed; a
failed reply closes the server's handles; a client passing NULL for a
handle result gets it closed. Handle ARGUMENTS are refused: if a call
fails, it can't tell whether the kernel already moved them, so ownership
would be ambiguous. Pass handles with channel_write or as results.

Wire format (packed little-endian structs, no padding):
    request  u32 txid (channel_call stamps it), u32 ordinal, the args
    reply    u32 txid (echoed), i32 status, then the results only if
             status is OK
The ordinal on the wire is (id << 16) | ordinal, so a request sent to a
server of another protocol fails with ERR_NOT_SUPPORTED instead of being
taken for a different method. A request of the wrong size, one carrying
handles, or one too big for any method gets ERR_INVALID_ARGS; one shorter
than 4 bytes (no txid) is dropped without a reply.

Run from the repository root (the Makefile does)."""
import glob
import os
import re
import sys

IDL_DIR = "abi/idl"
OUT_DIR = "drivers/include/idl"
IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*$")
SCALARS = {"u8": ("uint8_t", 1), "u16": ("uint16_t", 2), "u32": ("uint32_t", 4),
           "u64": ("uint64_t", 8), "i8": ("int8_t", 1), "i16": ("int16_t", 2),
           "i32": ("int32_t", 4), "i64": ("int64_t", 8)}
ARRAY = re.compile(r"u8\[(\d+)\]$")
ARRAY_MAX = 4096
MSG_MAX = 8192          # bytes of one request or reply: both sit on a kernel stack
HDR = 8                 # txid + ordinal / txid + status
RESERVED = {"ch", "deadline_ns", "ctx", "ops"}
C_KEYWORDS = set("""auto break case char const continue default do double else enum extern
    float for goto if inline int long register restrict return short signed sizeof static
    struct switch typedef union unsigned void volatile while _Bool _Alignas _Alignof _Atomic
    _Noreturn _Static_assert _Thread_local bool true false NULL""".split())
BANNER = "Generated by tools/genidl.py from {src}. Do not edit:\n" \
         " * change the .idl and run `make idl`."


REP_HANDLES_MAX = 8


class Field:
    def __init__(self, ctype, name, size, array, handle=False):
        self.ctype, self.name, self.size, self.array = ctype, name, size, array
        self.handle = handle

    def member(self):
        return f"{self.ctype} {self.name}[{self.array}];" if self.array else \
               f"{self.ctype} {self.name};"

    def in_param(self):
        return f"const uint8_t {self.name}[{self.array}]" if self.array else \
               f"{self.ctype} {self.name}"

    def out_param(self):
        return f"uint8_t out_{self.name}[{self.array}]" if self.array else \
               f"{self.ctype} *out_{self.name}"


class Method:
    def __init__(self, ordinal, name, args, results, doc):
        self.ordinal, self.name, self.args, self.results, self.doc = \
            ordinal, name, args, results, doc


class Protocol:
    def __init__(self, src, name, pid, methods):
        self.src, self.name, self.pid, self.methods = src, name, pid, methods

    def wire(self, m):
        return (self.pid << 16) | m.ordinal


def fail(src, lineno, msg):
    sys.exit(f"{src}:{lineno}: {msg}")


def parse_fields(src, lineno, text, what, allow_handles=False):
    text = text.strip()
    if not (text.startswith("(") and text.endswith(")")):
        fail(src, lineno, f"{what}: want '(<type> <name>, ...)' or '()'")
    body = text[1:-1].strip()
    fields = []
    if not body:
        return fields
    for part in body.split(","):
        toks = part.split()
        if len(toks) != 2:
            fail(src, lineno, f"{what}: bad field '{part.strip()}' (want '<type> <name>')")
        t, name = toks
        if not IDENT.match(name) or name in C_KEYWORDS:
            fail(src, lineno, f"{what}: bad name '{name}'")
        if name in RESERVED or name.startswith("idl_") or name.startswith("out_"):
            fail(src, lineno, f"{what}: name '{name}' is reserved "
                              f"({', '.join(sorted(RESERVED))}, idl_*, out_*)")
        if any(f.name == name for f in fields):
            fail(src, lineno, f"{what}: '{name}' twice")
        a = ARRAY.match(t)
        if t == "handle":
            if not allow_handles:
                fail(src, lineno, f"{what}: handle arguments aren't supported (if a call fails "
                                  "it can't tell whether they were moved); return handles "
                                  "as results, or send them with channel_write")
            fields.append(Field("handle_t", name, 0, 0, handle=True))
        elif a:
            n = int(a.group(1))
            if not 1 <= n <= ARRAY_MAX:
                fail(src, lineno, f"{what}: array size {n} not in 1..{ARRAY_MAX}")
            fields.append(Field("uint8_t", name, n, n))
        elif t in SCALARS:
            ctype, size = SCALARS[t]
            fields.append(Field(ctype, name, size, 0))
        else:
            fail(src, lineno, f"{what}: unknown type '{t}' (want {' '.join(SCALARS)}, u8[N] "
                              "or handle)")
    return fields


def parse(src):
    name, pid, methods, doc = None, None, [], []
    ordinals, names = set(), set()
    for lineno, raw in enumerate(open(src), 1):
        line = raw.strip()
        if line.startswith("#"):
            doc.append(line[1:].strip())
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            doc = []
            continue
        if line.startswith("protocol"):
            toks = line.split()
            if name is not None:
                fail(src, lineno, "a second 'protocol' line")
            if len(toks) != 3 or not IDENT.match(toks[1]) or toks[1] in C_KEYWORDS or \
                    not toks[2].isdigit():
                fail(src, lineno, "want 'protocol <name> <id>'")
            name, pid = toks[1], int(toks[2])
            if not 1 <= pid <= 65535:
                fail(src, lineno, f"protocol id {pid} not in 1..65535")
            if os.path.basename(src) != name + ".idl":
                fail(src, lineno, f"protocol '{name}' must live in {name}.idl")
            doc = []
            continue
        if name is None:
            fail(src, lineno, "the first statement must be 'protocol <name> <id>'")
        m = re.match(r"(\d+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(\(.*?\))\s*->\s*(\(.*\))$", line)
        if not m:
            fail(src, lineno, "want '<ordinal> <method> (<args>) -> (<results>)'")
        ordinal, mname = int(m.group(1)), m.group(2)
        if mname in C_KEYWORDS:
            fail(src, lineno, f"bad method name '{mname}'")
        if not 1 <= ordinal <= 65535:
            fail(src, lineno, f"ordinal {ordinal} not in 1..65535")
        if ordinal in ordinals:
            fail(src, lineno, f"ordinal {ordinal} used twice")
        if mname in names:
            fail(src, lineno, f"method '{mname}' defined twice")
        if mname in ("dispatch", "serve", "serve_one", "ops"):
            fail(src, lineno, f"method name '{mname}' is reserved")
        ordinals.add(ordinal)
        names.add(mname)
        args = parse_fields(src, lineno, m.group(3), f"{mname} arguments")
        results = parse_fields(src, lineno, m.group(4), f"{mname} results", allow_handles=True)
        if sum(1 for f in results if f.handle) > REP_HANDLES_MAX:
            fail(src, lineno, f"{mname}: more than {REP_HANDLES_MAX} handle results")
        for size, what in ((sum(f.size for f in args), "request"),
                           (sum(f.size for f in results), "reply")):
            if HDR + size > MSG_MAX:
                fail(src, lineno, f"{mname}: {what} is {HDR + size} bytes (max {MSG_MAX})")
        methods.append(Method(ordinal, mname, args, results, doc))
        doc = []
    if name is None:
        sys.exit(f"{src}: no 'protocol' line")
    if not methods:
        sys.exit(f"{src}: no methods")
    return Protocol(src, name, pid, sorted(methods, key=lambda m: m.ordinal))


def c_comment(lines, indent=""):
    if not lines:
        return []
    if len(lines) == 1:
        return [f"{indent}/* {lines[0]} */"]
    out = [f"{indent}/* {lines[0]}"]
    out += [f"{indent} * {l}" if l else f"{indent} *" for l in lines[1:]]
    out[-1] += " */"
    return out


def gen_common():
    return "\n".join([
        f"/* {BANNER.format(src='tools/genidl.py')}",
        " *",
        " * What every generated protocol header (<idl/<name>.h>) shares: the",
        " * message headers and the server's handling of messages no method can",
        " * take. The format is described at the top of tools/genidl.py. */",
        "#pragma once",
        "",
        "#include <jam/driver.h>",
        "",
        "/* Every request starts with this, every reply with idl_rep_hdr. */",
        "struct idl_req_hdr {",
        "    uint32_t txid;       /* stamped by channel_call */",
        "    uint32_t ordinal;    /* (protocol id << 16) | method ordinal */",
        "} __attribute__((packed));",
        "",
        "struct idl_rep_hdr {",
        "    uint32_t txid;       /* the request's, echoed */",
        "    int32_t  status;     /* OK: the results follow */",
        "} __attribute__((packed));",
        "",
        "/* Handles a server reads with a request (all of them are closed: no",
        " * method takes handle arguments). */",
        "#define IDL_READ_HANDLES 8",
        "/* Handles one reply can carry (methods' handle results). */",
        f"#define IDL_REP_HANDLES {REP_HANDLES_MAX}",
        "",
        "/* Client: the status of a reply of n bytes to a call that wants `want`",
        " * bytes back on success. A server that breaks the format (a positive",
        " * status, a wrong size) is ERR_INTERNAL. */",
        "static inline status_t idl_rep_status(const void *rep, uint32_t n, uint32_t want)",
        "{",
        "    const struct idl_rep_hdr *h = (const struct idl_rep_hdr *)rep;",
        "    if (n < sizeof(*h) || h->status > 0)",
        "        return ERR_INTERNAL;",
        "    if (h->status != OK)",
        "        return n == sizeof(*h) ? h->status : ERR_INTERNAL;",
        "    return n == want ? OK : ERR_INTERNAL;",
        "}",
        "",
        "static inline void idl_close_all(const handle_t *hs, uint32_t n)",
        "{",
        "    for (uint32_t idl_i = 0; idl_i < n; idl_i++)",
        "        drv_handle_close(hs[idl_i]);",
        "}",
        "",
        "/* Server: answer the request whose first n bytes are at req with a bare",
        " * status. No txid (n < 4): no reply. A reply that can't be written",
        " * (the client is gone, or its queue is full) is dropped. */",
        "static inline void idl_reply_status(handle_t ch, const void *req, uint32_t n, status_t st)",
        "{",
        "    if (n < sizeof(uint32_t))",
        "        return;",
        "    struct idl_rep_hdr idl_r;",
        "    idl_r.txid = ((const struct idl_req_hdr *)req)->txid;",
        "    idl_r.status = st;",
        "    drv_channel_write(ch, &idl_r, sizeof(idl_r), NULL, 0);",
        "}",
        "",
        "/* Server: the next message didn't fit (n bytes, nh handles): bigger than",
        " * any request of the protocol. Take it off the queue anyway (or it would",
        " * block every later one), close its handles, answer ERR_INVALID_ARGS. */",
        "static inline status_t idl_drain(handle_t ch, uint32_t n, uint32_t nh)",
        "{",
        "    uint8_t *idl_b = (uint8_t *)drv_malloc(n ? n : 1);",
        "    handle_t *idl_hs = (handle_t *)drv_malloc(nh ? nh * sizeof(handle_t) : 1);",
        "    status_t idl_st = idl_b && idl_hs ? OK : ERR_NO_MEMORY;",
        "    uint32_t idl_n = 0, idl_nh = 0;",
        "    if (idl_st == OK)",
        "        idl_st = drv_channel_read(ch, idl_b, n, &idl_n, idl_hs, nh, &idl_nh);",
        "    if (idl_st == OK) {",
        "        idl_close_all(idl_hs, idl_nh);",
        "        idl_reply_status(ch, idl_b, idl_n, ERR_INVALID_ARGS);",
        "    } else if (idl_st == ERR_BUFFER_TOO_SMALL || idl_st == ERR_SHOULD_WAIT) {",
        "        idl_st = OK;   /* another reader took it meanwhile: look again */",
        "    }",
        "    drv_free(idl_hs);",
        "    drv_free(idl_b);",
        "    return idl_st;",
        "}",
        "",
    ])


def gen_protocol(p):
    P, U = p.name, p.name.upper()
    src = os.path.relpath(p.src)
    out = [f"/* {BANNER.format(src=src)}",
           " *",
           f" * Protocol `{P}` (id {p.pid}). Client: {P}_<method>(ch, args..., &results...)",
           f" * (and {P}_<method>_until with a deadline) over drv_channel_call. Server:",
           f" * fill a struct {P}_ops and run {P}_serve(ch, &ops, ctx), or",
           f" * {P}_serve_one / {P}_dispatch for a loop of your own. */",
           "#pragma once", "", "#include <idl/common.h>", "",
           f"#define {U}_PROTOCOL_ID {p.pid}u"]
    for m in p.methods:
        out.append(f"#define {U}_{m.name.upper():<16} 0x{p.wire(m):08x}u")
    out.append("")

    req_max = max(HDR + sum(f.size for f in m.args) for m in p.methods)
    rep_max = max(HDR + sum(f.size for f in m.results) for m in p.methods)
    out.append("/* Messages (packed: no padding bytes ever cross the channel). */")
    for m in p.methods:
        out.append(f"struct {P}_{m.name}_req {{")
        out.append("    uint32_t txid;")
        out.append("    uint32_t ordinal;")
        out += [f"    {f.member()}" for f in m.args if not f.handle]
        out.append("} __attribute__((packed));")
        out.append(f"struct {P}_{m.name}_rep {{")
        out.append("    uint32_t txid;")
        out.append("    int32_t  status;")
        out += [f"    {f.member()}" for f in m.results if not f.handle]
        out.append("} __attribute__((packed));")
    out += ["", f"#define {U}_REQ_MAX {req_max}u   /* bytes: the biggest request */",
            f"#define {U}_REP_MAX {rep_max}u   /* bytes: the biggest reply */", ""]

    # client
    out.append("/* ---- client ---------------------------------------------------------- */")
    for m in p.methods:
        params = ["handle_t ch", "uint64_t deadline_ns"] + [f.in_param() for f in m.args] + \
                 [f.out_param() for f in m.results]
        out.append("")
        out += c_comment(m.doc)
        out.append(f"static inline status_t {P}_{m.name}_until({', '.join(params)})")
        out.append("{")
        out.append(f"    struct {P}_{m.name}_req idl_q;")
        out.append(f"    struct {P}_{m.name}_rep idl_r;")
        out.append("    uint32_t idl_n = 0;")
        out.append("    idl_q.txid = 0;")
        out.append(f"    idl_q.ordinal = {U}_{m.name.upper()};")
        for f in m.args:
            if f.array:
                out.append(f"    for (uint32_t idl_i = 0; idl_i < {f.array}; idl_i++)")
                out.append(f"        idl_q.{f.name}[idl_i] = {f.name}[idl_i];")
            else:
                out.append(f"    idl_q.{f.name} = {f.name};")
        hres = [f for f in m.results if f.handle]
        if hres:
            out.append(f"    handle_t idl_rh[{len(hres)}];")
            out.append("    uint32_t idl_rhn = 0;")
            out.append("    status_t idl_st = drv_channel_call_h(ch, &idl_q, sizeof(idl_q), &idl_r, "
                       "sizeof(idl_r), &idl_n,")
            out.append(f"                                         idl_rh, {len(hres)}, &idl_rhn, "
                       "deadline_ns);")
            out.append("    if (idl_st == OK)")
            out.append("        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));")
            out.append(f"    if (idl_st == OK && idl_rhn != {len(hres)})")
            out.append("        idl_st = ERR_INTERNAL;")
            out.append("    if (idl_st != OK)")
            out.append("        idl_close_all(idl_rh, idl_rhn);")
        else:
            out.append("    status_t idl_st = drv_channel_call(ch, &idl_q, sizeof(idl_q), &idl_r, "
                       "sizeof(idl_r), &idl_n,")
            out.append("                                       deadline_ns);")
            out.append("    if (idl_st == OK)")
            out.append("        idl_st = idl_rep_status(&idl_r, idl_n, sizeof(idl_r));")
        for k, f in enumerate(hres):
            out.append(f"    if (idl_st == OK) {{")
            out.append(f"        if (out_{f.name})")
            out.append(f"            *out_{f.name} = idl_rh[{k}];")
            out.append("        else")
            out.append(f"            drv_handle_close(idl_rh[{k}]);")
            out.append("    }")
        for f in m.results:
            if f.handle:
                continue
            if f.array:
                out.append(f"    for (uint32_t idl_i = 0; idl_st == OK && out_{f.name} && "
                           f"idl_i < {f.array}; idl_i++)")
                out.append(f"        out_{f.name}[idl_i] = idl_r.{f.name}[idl_i];")
            else:
                out.append(f"    if (idl_st == OK && out_{f.name})")
                out.append(f"        *out_{f.name} = idl_r.{f.name};")
        out.append("    return idl_st;")
        out.append("}")
        plain = ["handle_t ch"] + [f.in_param() for f in m.args] + [f.out_param() for f in m.results]
        names = ["ch", "DEADLINE_NEVER"] + [f.name for f in m.args] + \
                [f"out_{f.name}" for f in m.results]
        out.append(f"static inline status_t {P}_{m.name}({', '.join(plain)})")
        out.append("{")
        out.append(f"    return {P}_{m.name}_until({', '.join(names)});")
        out.append("}")
    out.append("")

    # server
    out.append("/* ---- server ---------------------------------------------------------- */")
    out.append("")
    out.append(f"/* Handlers: return OK and fill the results, or an ERR_* for the client.")
    out.append(" * A NULL handler answers ERR_NOT_SUPPORTED. */")
    out.append(f"struct {P}_ops {{")
    for m in p.methods:
        params = ["void *ctx"] + [f.in_param() for f in m.args] + [f.out_param() for f in m.results]
        out.append(f"    status_t (*{m.name})({', '.join(params)});")
    out.append("};")
    out.append("")
    out += [
        f"/* Decode the request of n bytes at req, call its handler, encode the reply",
        f" * into rep ({U}_REP_MAX bytes) and the handles it carries into rhs",
        " * (IDL_REP_HANDLES slots; *rhn of them). Returns the reply's length: 0",
        " * means no reply (the request has no txid). No I/O; the caller sends the",
        " * reply with the handles, or closes them if it can't. */",
        f"static inline uint32_t {P}_dispatch(const struct {P}_ops *ops, void *ctx, "
        "const void *req, uint32_t n,",
        " " * len(f"static inline uint32_t {P}_dispatch(") + "void *rep, handle_t *rhs, uint32_t *rhn)",
        "{",
        "    struct idl_rep_hdr *idl_h = (struct idl_rep_hdr *)rep;",
        "    *rhn = 0;",
        "    (void)rhs;",
        "    if (n < sizeof(uint32_t))",
        "        return 0;",
        "    idl_h->txid = ((const struct idl_req_hdr *)req)->txid;",
        "    idl_h->status = ERR_INVALID_ARGS;",
        "    if (n < sizeof(struct idl_req_hdr))",
        "        return sizeof(*idl_h);",
        "    switch (((const struct idl_req_hdr *)req)->ordinal) {",
    ]
    for m in p.methods:
        out.append(f"    case {U}_{m.name.upper()}: {{")
        out.append(f"        const struct {P}_{m.name}_req *idl_q = "
                   f"(const struct {P}_{m.name}_req *)req;")
        out.append(f"        struct {P}_{m.name}_rep *idl_r = (struct {P}_{m.name}_rep *)rep;")
        for f in m.results:
            if f.handle:
                out.append(f"        handle_t out_{f.name} = HANDLE_INVALID;")
            elif f.array:
                out.append(f"        uint8_t out_{f.name}[{f.array}];")
                out.append(f"        for (uint32_t idl_i = 0; idl_i < {f.array}; idl_i++)")
                out.append(f"            out_{f.name}[idl_i] = 0;")
            else:
                out.append(f"        {f.ctype} out_{f.name} = 0;")
        if not m.results:
            out.append("        (void)idl_r;")
        out.append("        if (n != sizeof(*idl_q))")
        out.append("            return sizeof(*idl_h);")
        out.append(f"        if (!ops->{m.name}) {{")
        out.append("            idl_h->status = ERR_NOT_SUPPORTED;")
        out.append("            return sizeof(*idl_h);")
        out.append("        }")
        call = ["ctx"] + [f"idl_q->{f.name}" for f in m.args] + \
               [f"out_{f.name}" if f.array else f"&out_{f.name}" for f in m.results]
        out.append(f"        status_t idl_st = ops->{m.name}({', '.join(call)});")
        out.append("        idl_h->status = idl_st > 0 ? ERR_INTERNAL : idl_st;")
        hres = [f for f in m.results if f.handle]
        if hres:
            ok = " && ".join(f"out_{f.name} != HANDLE_INVALID" for f in hres)
            out.append(f"        if (idl_h->status == OK && !({ok}))")
            out.append("            idl_h->status = ERR_INTERNAL;   /* a handle result left unset */")
            out.append("        if (idl_h->status != OK) {")
            for f in hres:
                out.append(f"            if (out_{f.name} != HANDLE_INVALID)")
                out.append(f"                drv_handle_close(out_{f.name});")
            out.append("            return sizeof(*idl_h);")
            out.append("        }")
            for k, f in enumerate(hres):
                out.append(f"        rhs[{k}] = out_{f.name};")
            out.append(f"        *rhn = {len(hres)};")
        else:
            out.append("        if (idl_h->status != OK)")
            out.append("            return sizeof(*idl_h);")
        for f in m.results:
            if f.handle:
                continue
            if f.array:
                out.append(f"        for (uint32_t idl_i = 0; idl_i < {f.array}; idl_i++)")
                out.append(f"            idl_r->{f.name}[idl_i] = out_{f.name}[idl_i];")
            else:
                out.append(f"        idl_r->{f.name} = out_{f.name};")
        out.append("        return sizeof(*idl_r);")
        out.append("    }")
    out += [
        "    }",
        "    idl_h->status = ERR_NOT_SUPPORTED;",
        "    return sizeof(*idl_h);",
        "}",
        "",
        "/* Take one message off ch and answer it. OK once a message was handled",
        " * (its reply may still have been dropped: the client is gone, or never",
        " * called); otherwise drv_channel_read's status: ERR_SHOULD_WAIT when",
        " * nothing is queued, ERR_PEER_CLOSED when the client is gone for good. */",
        f"static inline status_t {P}_serve_one(handle_t ch, const struct {P}_ops *ops, void *ctx)",
        "{",
        f"    _Alignas(8) uint8_t idl_q[{U}_REQ_MAX];",
        f"    _Alignas(8) uint8_t idl_r[{U}_REP_MAX];",
        "    handle_t idl_hs[IDL_READ_HANDLES];",
        "    uint32_t idl_n = 0, idl_nh = 0;",
        "    status_t idl_st = drv_channel_read(ch, idl_q, sizeof(idl_q), &idl_n, idl_hs, "
        "IDL_READ_HANDLES,",
        "                                       &idl_nh);",
        "    if (idl_st == ERR_BUFFER_TOO_SMALL)",
        "        return idl_drain(ch, idl_n, idl_nh);",
        "    if (idl_st != OK)",
        "        return idl_st;",
        "    if (idl_nh) {",
        "        idl_close_all(idl_hs, idl_nh);",
        "        idl_reply_status(ch, idl_q, idl_n, ERR_INVALID_ARGS);",
        "        return OK;",
        "    }",
        "    handle_t idl_rhs[IDL_REP_HANDLES];",
        "    uint32_t idl_rhn = 0;",
        f"    uint32_t idl_rn = {P}_dispatch(ops, ctx, idl_q, idl_n, idl_r, idl_rhs, &idl_rhn);",
        "    if (!idl_rn || drv_channel_write(ch, idl_r, idl_rn, idl_rhs, idl_rhn) != OK)",
        "        idl_close_all(idl_rhs, idl_rhn);   /* not sent: they're still ours */",
        "    return OK;",
        "}",
        "",
        "/* Serve ch until the client closes it (OK), or a wait or read fails",
        " * (that status: ERR_CANCELED when the driver is being killed). */",
        f"static inline status_t {P}_serve(handle_t ch, const struct {P}_ops *ops, void *ctx)",
        "{",
        "    for (;;) {",
        f"        status_t idl_st = {P}_serve_one(ch, ops, ctx);",
        "        if (idl_st == OK)",
        "            continue;",
        "        if (idl_st == ERR_PEER_CLOSED)",
        "            return OK;",
        "        if (idl_st != ERR_SHOULD_WAIT)",
        "            return idl_st;",
        "        signals_t idl_seen = 0;",
        "        idl_st = drv_object_wait_one(ch, SIG_READABLE | SIG_PEER_CLOSED, DEADLINE_NEVER,",
        "                                     &idl_seen);",
        "        if (idl_st != OK)",
        "            return idl_st;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in ("gen", "check"):
        sys.exit(__doc__)
    protos = [parse(f) for f in sorted(glob.glob(os.path.join(IDL_DIR, "*.idl")))]
    ids = {}
    for p in protos:
        if p.pid in ids:
            sys.exit(f"{p.src}: protocol id {p.pid} is also {ids[p.pid]}'s")
        ids[p.pid] = p.name
    outputs = {os.path.join(OUT_DIR, "common.h"): gen_common()}
    for p in protos:
        if p.name == "common":
            sys.exit(f"{p.src}: 'common' is reserved")
        outputs[os.path.join(OUT_DIR, p.name + ".h")] = gen_protocol(p)
    stale = []
    for path, text in outputs.items():
        try:
            old = open(path).read()
        except FileNotFoundError:
            old = None
        if old == text:
            continue
        if sys.argv[1] == "gen":
            os.makedirs(OUT_DIR, exist_ok=True)
            open(path, "w").write(text)
            print(f"genidl: wrote {path}")
        else:
            stale.append(path)
    for path in sorted(glob.glob(os.path.join(OUT_DIR, "*.h"))):
        if path not in outputs:
            if sys.argv[1] == "gen":
                os.remove(path)
                print(f"genidl: removed {path} (no .idl for it)")
            else:
                stale.append(path + " (no .idl for it)")
    if stale:
        sys.exit("genidl: generated files are stale or edited by hand "
                 f"({', '.join(stale)}):\nrun `make idl` and commit the result")


if __name__ == "__main__":
    main()
