#!/usr/bin/env python3
"""Keep #include lines in the order CODING-GUIDE.md asks for.

Within each run of consecutive #include lines (a blank line, a comment line
or any other directive ends a run, so deliberate grouping and #ifdef'd
includes are left alone), the order is:

  1. <std*.h>, the compiler's freestanding headers (stdint.h, stdbool.h, ...)
  2. every other <...> header (<jam/...>, <idl/...>, <os.h>, ...)
  3. "..." headers, the program's own

and alphabetical inside each group. Generated files ("Generated by ... Do
not edit") and third_party/ are skipped: their generators own them.

  python3 tools/sortincludes.py           check: list files out of order, exit 1
  python3 tools/sortincludes.py --fix     rewrite them in place
  (`make check` runs the check; `make includes` runs --fix.)
"""
import os
import re
import sys

ROOTS = ("kernel", "drivers", "user")
INCLUDE = re.compile(r'\s*#\s*include\s*([<"])([^>"]+)[>"]')


def key(line):
    m = INCLUDE.match(line)
    bracket, path = m.group(1), m.group(2)
    if bracket == "<" and path.startswith("std"):
        group = 0
    elif bracket == "<":
        group = 1
    else:
        group = 2
    return (group, path)


def sort_runs(lines):
    out, run = [], []
    for line in lines + [None]:
        if line is not None and INCLUDE.match(line):
            run.append(line)
            continue
        out.extend(sorted(run, key=key))
        run = []
        if line is not None:
            out.append(line)
    return out


def generated(text):
    head = text[:300].lower()
    return "generated by" in head and "do not edit" in head


def files(root):
    for top in ROOTS:
        for d, _, names in os.walk(os.path.join(root, top)):
            for n in sorted(names):
                if n.endswith((".c", ".h")):
                    yield os.path.join(d, n)


def main():
    fix = "--fix" in sys.argv[1:]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    bad = []
    for path in files(root):
        with open(path) as f:
            text = f.read()
        if generated(text):
            continue
        lines = text.split("\n")
        new = sort_runs(lines)
        if new != lines:
            rel = os.path.relpath(path, root)
            bad.append(rel)
            if fix:
                with open(path, "w") as f:
                    f.write("\n".join(new))
    if not bad:
        print("sortincludes: every #include run is in order")
        return 0
    if fix:
        print(f"sortincludes: sorted {len(bad)} file(s):")
        for b in bad:
            print("  " + b)
        return 0
    print(f"sortincludes: {len(bad)} file(s) with #includes out of order "
          "(`make includes` fixes them):")
    for b in bad:
        print("  " + b)
    return 1


if __name__ == "__main__":
    sys.exit(main())
